Repository truera/trulens, pull requests merged in 2024-03, with the labels that each got.

#948 Add reranking comparison to Canopy quickstart notebook
  trulens_eval/examples/expositional/frameworks/canopy/canopy_quickstart.ipynb
Labels: documentation, size:L

#949 update tru virtual docs
  docs/trulens_eval/api/app/truvirtual.md
  trulens_eval/examples/experimental/virtual_example.ipynb
  trulens_eval/trulens_eval/pages/Evaluations.py
  trulens_eval/trulens_eval/tru_virtual.py
Labels: documentation, size:L, lgtm

#954 [MLNN-1217] Improve regex matching for structured output extraction from LLM feedback function providers
  trulens_eval/examples/quickstart/py_script_quickstarts/all_tools.py
  trulens_eval/tests/unit/test_feedback_score_generation.py
  trulens_eval/trulens_eval/utils/generated.py
Labels: size:M, lgtm

#956 Commit outputs to Canopy quickstart notebook
  trulens_eval/examples/expositional/frameworks/canopy/canopy_quickstart.ipynb
Labels: documentation, size:XL, lgtm

#958 Create reranker chat engine from code instead of using config
  trulens_eval/examples/expositional/frameworks/canopy/canopy_quickstart.ipynb
Labels: documentation, size:L

#953 instrumentation notebook updates and fixes
  docs/trulens_eval/tracking/instrumentation/index.ipynb
  docs/trulens_eval/tracking/instrumentation/langchain.ipynb
  docs/trulens_eval/tracking/instrumentation/llama_index.ipynb
  trulens_eval/tests/docs_notebooks/notebooks_to_test/langchain_instrumentation.ipynb
  trulens_eval/tests/docs_notebooks/notebooks_to_test/llama_index_instrumentation.ipynb
  trulens_eval/tests/docs_notebooks/notebooks_to_test/trulens_instrumentation.ipynb
  trulens_eval/tests/unit/static/test_static.py
  trulens_eval/trulens_eval/instruments.py
  trulens_eval/trulens_eval/requirements.optional.txt
  trulens_eval/trulens_eval/tru_basic_app.py
  trulens_eval/trulens_eval/tru_chain.py
  trulens_eval/trulens_eval/tru_llama.py
  trulens_eval/trulens_eval/utils/imports.py
  trulens_eval/trulens_eval/utils/llama.py
  trulens_eval/trulens_eval/utils/python.py
  trulens_eval/trulens_eval/utils/text.py
Labels: documentation, size:XXL, lgtm

#960 [Canopy quickstart notebook] - Use free tier for Pinecone
  trulens_eval/examples/expositional/frameworks/canopy/canopy_quickstart.ipynb
Labels: documentation, size:L

#824 add nemo guardrails integrations
  docs/trulens_eval/api/app/trurails.md
  docs/trulens_eval/api/feedback.md
  docs/trulens_eval/evaluation/feedback_providers/index.md
  docs/trulens_eval/tracking/instrumentation/.gitignore
  docs/trulens_eval/tracking/instrumentation/llama_index.ipynb
  docs/trulens_eval/tracking/instrumentation/nemo.ipynb
  mkdocs.yml
  trulens_eval/examples/__init__.py
  trulens_eval/examples/expositional/__init__.py
  trulens_eval/examples/expositional/end2end_apps/__init__.py
  trulens_eval/examples/expositional/frameworks/nemoguardrails/.gitignore
  trulens_eval/examples/expositional/frameworks/nemoguardrails/kb
  trulens_eval/examples/expositional/frameworks/nemoguardrails/nemoguardrails_custom_action_with_feedback_example.ipynb
  trulens_eval/examples/expositional/frameworks/nemoguardrails/nemoguardrails_feedback_action_example.ipynb
  trulens_eval/examples/expositional/frameworks/nemoguardrails/nemoguardrails_trurails_example.ipynb
  trulens_eval/tests/e2e/test_tru_chain.py
  trulens_eval/tests/unit/static/test_static.py
  trulens_eval/trulens_eval/__init__.py
  trulens_eval/trulens_eval/app.py
  trulens_eval/trulens_eval/feedback/__init__.py
  trulens_eval/trulens_eval/feedback/feedback.py
  trulens_eval/trulens_eval/requirements.optional.txt
  trulens_eval/trulens_eval/schema.py
  trulens_eval/trulens_eval/tru_chain.py
  trulens_eval/trulens_eval/tru_rails.py
  trulens_eval/trulens_eval/utils/containers.py
  trulens_eval/trulens_eval/utils/imports.py
  trulens_eval/trulens_eval/utils/langchain.py
  trulens_eval/trulens_eval/utils/notebook_utils.py
  trulens_eval/trulens_eval/utils/pyschema.py
  trulens_eval/trulens_eval/utils/serial.py
Labels: size:XXL, lgtm

#962 Fix release test pipeline
  .github/workflows/combine_nb_to_docs_testing.sh
  docs/trulens_eval/getting_started/quickstarts/index.md
  docs/trulens_eval/getting_started/quickstarts/prototype_evals.ipynb
  docs/trulens_eval/prototype_evals.ipynb
  trulens_eval/examples/quickstart/py_script_quickstarts/all_tools.py
  trulens_eval/examples/quickstart/py_script_quickstarts/langchain_quickstart.py
  trulens_eval/examples/quickstart/py_script_quickstarts/llama_index_quickstart.py
  trulens_eval/examples/quickstart/py_script_quickstarts/quickstart.py
  trulens_eval/examples/quickstart/py_script_quickstarts/text2text_quickstart.py
  trulens_eval/generated_files/all_tools.ipynb
  trulens_eval/generated_files/all_tools.py
  trulens_eval/generated_files/langchain_quickstart.py
  trulens_eval/generated_files/llama_index_quickstart.py
  trulens_eval/generated_files/text2text_quickstart.py
  trulens_eval/trulens_eval/requirements.optional.txt
Labels: documentation, size:XXL, lgtm

#865 Generate Test Set: extract response attr if app returns object with that attr
  trulens_eval/trulens_eval/generate_test_set.py
Labels: size:S, lgtm

#963 fix links in docs
  docs/trulens_eval/contributing/index.md
  docs/trulens_eval/getting_started/core_concepts/core_concepts_rag_triad.md
  docs/trulens_eval/getting_started/core_concepts/rag_triad.md
  docs/trulens_eval/getting_started/index.md
  docs/trulens_eval/index.md
  docs/trulens_explain/index.md
  trulens_eval/trulens_eval/schema.py
  trulens_eval/trulens_eval/tru_virtual.py
Labels: documentation, size:M, lgtm

#965 adjust all_tools symlink
  trulens_eval/tests/docs_notebooks/notebooks_to_test/all_tools.ipynb
Labels: documentation, size:XS, lgtm

#966 TruLens-Eval 0.25.0
  trulens_eval/trulens_eval/__init__.py
Labels: size:XS, lgtm

#925 canopy quickstart
  trulens_eval/examples/expositional/frameworks/canopy/canopy_quickstart.ipynb
Labels: size:XL, lgtm

#967 add missing virtual app setup and redirects from old core concept links
  docs/trulens_eval/evaluation/running_feedback_functions/existing_data.md
  mkdocs.yml
Labels: documentation, size:M, lgtm

#968 fix links in docs
  README.md
  docs/overrides/home.html
  docs/trulens_eval/gh_top_intro.md
  docs/trulens_eval/intro.md
  mkdocs.yml
  trulens_eval/README.md
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_multimodal.ipynb
Labels: documentation, size:M, lgtm

#973 Update typo in pip install on azure_openai.ipynb
  trulens_eval/examples/expositional/models/azure_openai.ipynb
Labels: documentation, size:XS, lgtm

#972 readd redirects
  docs/docs_requirements.txt
  docs/trulens_eval/tracking/instrumentation/index.ipynb
  docs/trulens_eval/tracking/instrumentation/langchain.ipynb
  docs/trulens_eval/tracking/instrumentation/llama_index.ipynb
  docs/trulens_eval/tracking/instrumentation/nemo.ipynb
  mkdocs.yml
  trulens_eval/examples/quickstart/langchain_quickstart.ipynb
Labels: documentation, dependencies, size:L, lgtm

#980 fix colab link - langchain ensemble notebook
  trulens_eval/examples/expositional/frameworks/langchain/langchain_ensemble_retriever.ipynb
Labels: documentation, size:XS, lgtm

#974 Fix TruChain instrumentation issue introduced in 0.24.1
  trulens_eval/trulens_eval/tru_chain.py
Labels: size:XS, lgtm

#982 notebook patch
  trulens_eval/examples/expositional/frameworks/langchain/langchain_ensemble_retriever.ipynb
Labels: documentation, size:XS, lgtm

#977 QS Relevance -> Context Relevance
  trulens_eval/examples/quickstart/langchain_quickstart.ipynb
  trulens_eval/examples/quickstart/llama_index_quickstart.ipynb
  trulens_eval/examples/quickstart/quickstart.ipynb
  trulens_eval/examples/quickstart/text2text_quickstart.ipynb
  trulens_eval/trulens_eval/feedback/prompts.py
  trulens_eval/trulens_eval/feedback/provider/base.py
  trulens_eval/trulens_eval/feedback/v2/feedback.py
Labels: documentation, size:L, lgtm

#981 TruLens-Eval 0.25.1
  trulens_eval/trulens_eval/__init__.py
Labels: size:XS, lgtm

#976 existing data quickstart
  docs/trulens_eval/getting_started/quickstarts/existing_data_quickstart.ipynb
  mkdocs.yml
  trulens_eval/examples/quickstart/existing_data_quickstart.ipynb
Labels: documentation, size:L, lgtm

#984 Adds Azure Quickstart for LangChain
  trulens_eval/examples/expositional/models/azure_openai_langchain.ipynb
  trulens_eval/examples/expositional/models/azure_openai_llama_index.ipynb
Labels: documentation, size:XL, lgtm

#987 fix more docs links
  README.md
  docs/trulens_eval/gh_top_intro.md
  docs/trulens_eval/intro.md
  trulens_eval/README.md
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_multimodal.ipynb
Labels: documentation, size:S, lgtm

#990 update doc-building requirements
  docs/docs_requirements.txt
Labels: documentation, dependencies, size:XS, lgtm

#961 verify feedback selectors on recorder init
  README.md
  docs/trulens_eval/gh_top_intro.md
  docs/trulens_eval/intro.md
  docs/trulens_explain/gh_top_intro.md
  trulens_eval/README.md
  trulens_eval/examples/experimental/dev_notebook.ipynb
  trulens_eval/trulens_eval/app.py
  trulens_eval/trulens_eval/feedback/feedback.py
  trulens_eval/trulens_eval/requirements.txt
  trulens_eval/trulens_eval/schema.py
  trulens_eval/trulens_eval/utils/json.py
  trulens_eval/trulens_eval/utils/serial.py
Labels: documentation, size:XL, lgtm

#985 relax llama version
  trulens_eval/trulens_eval/requirements.optional.txt
Labels: dependencies, size:XS, lgtm

#988 Allow VirtualRecords to have multiple calls to the same component.
  .azure_pipelines/ci-eval-pr.yaml
  docs/trulens_eval/api/feedback.md
  docs/trulens_eval/contributing/techdebt.md
  trulens_eval/examples/experimental/virtual_example.ipynb
  trulens_eval/trulens_eval/__init__.py
  trulens_eval/trulens_eval/app.py
  trulens_eval/trulens_eval/feedback/feedback.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/openai.py
  trulens_eval/trulens_eval/feedback/provider/openai.py
  trulens_eval/trulens_eval/schema.py
  trulens_eval/trulens_eval/tru_llama.py
  trulens_eval/trulens_eval/tru_virtual.py
  trulens_eval/trulens_eval/utils/imports.py
  trulens_eval/trulens_eval/utils/serial.py
Labels: documentation, size:L, lgtm

#994 Fix broken colab links
  trulens_eval/examples/expositional/frameworks/langchain/langchain_async.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_hybrid_retriever.ipynb
  trulens_eval/examples/expositional/models/alpaca7b_local_llm.ipynb
  trulens_eval/examples/expositional/models/anthropic_quickstart.ipynb
  trulens_eval/examples/expositional/models/bedrock.ipynb
  trulens_eval/examples/expositional/vector-dbs/pinecone/pinecone_quickstart.ipynb
Labels: documentation, size:L, lgtm

#996 docs updates/additions
  docs/trulens_eval/api/app/index.md
  docs/trulens_eval/api/app/truchain.md
  docs/trulens_eval/contributing/index.md
  docs/trulens_eval/contributing/standards.md
  mkdocs.yml
  trulens_eval/trulens_eval/app.py
  trulens_eval/trulens_eval/database/sqlalchemy_db.py
  trulens_eval/trulens_eval/db.py
  trulens_eval/trulens_eval/instruments.py
  trulens_eval/trulens_eval/schema.py
  trulens_eval/trulens_eval/tru.py
  trulens_eval/trulens_eval/tru_basic_app.py
  trulens_eval/trulens_eval/tru_chain.py
  trulens_eval/trulens_eval/tru_custom_app.py
  trulens_eval/trulens_eval/tru_llama.py
  trulens_eval/trulens_eval/tru_rails.py
  trulens_eval/trulens_eval/tru_virtual.py
  trulens_eval/trulens_eval/utils/imports.py
  trulens_eval/trulens_eval/utils/pyschema.py
  trulens_eval/trulens_eval/utils/python.py
Labels: documentation, size:L, lgtm

#995 add install redirect in docs
  mkdocs.yml
Labels: documentation, size:XS, lgtm

#999 Update feedback docs
  docs/trulens_eval/evaluation/feedback_aggregation/index.md
  docs/trulens_eval/evaluation/feedback_functions/anatomy.md
  docs/trulens_eval/evaluation/feedback_functions/guide.md
  docs/trulens_eval/evaluation/feedback_selectors/index.md
  docs/trulens_eval/evaluation/feedback_selectors/selecting_components.md
  docs/trulens_eval/evaluation/generate_test_cases/index.md
  mkdocs.yml
  trulens_eval/trulens_eval/feedback/provider/base.py
Labels: documentation, size:XL, lgtm

#1003 Allow Feedback.run with args even if they had selectors specified.
  trulens_eval/trulens_eval/feedback/feedback.py
  trulens_eval/trulens_eval/feedback/provider/litellm.py
  trulens_eval/trulens_eval/requirements.optional.txt
Labels: size:M, lgtm

#1004 TruLens-Eval 0.26.0
  trulens_eval/trulens_eval/__init__.py
Labels: size:XS, lgtm

#1012 Python 3.12 support
  .azure_pipelines/ci-eval-pr.yaml
  trulens_eval/setup.py
  trulens_eval/tests/unit/static/test_static.py
  trulens_eval/trulens_eval/requirements.optional.txt
Labels: dependencies, size:S, lgtm

#1015 documentation nits and moves
  docs/trulens_eval/api/db.md
  docs/trulens_eval/api/instruments.md
  docs/trulens_eval/api/record.md
  docs/trulens_eval/contributing/design.md
  docs/trulens_eval/contributing/index.md
  mkdocs.yml
  trulens_eval/trulens_eval/instruments.py
Labels: documentation, size:L, lgtm

#1019 Fix shield link to docs
  README.md
  docs/trulens_eval/gh_top_intro.md
Labels: documentation, size:S, lgtm

#1021 Create pull_request_template.md
  docs/pull_request_template.md
Labels: documentation, size:XS, lgtm

#1023 Fix DB Issues
  trulens_eval/trulens_eval/database/sqlalchemy_db.py
  trulens_eval/trulens_eval/feedback/feedback.py
Labels: size:L, lgtm

#1022 fix typo in rag_triad.md
  docs/trulens_eval/getting_started/core_concepts/rag_triad.md
Labels: documentation, size:XS, lgtm

#1024 Fix paul_graham_essay.txt links to new location
  docs/trulens_eval/all_tools.ipynb
  trulens_eval/examples/experimental/dev_notebook.ipynb
  trulens_eval/examples/quickstart/llama_index_quickstart.ipynb
  trulens_eval/generated_files/all_tools.py
  trulens_eval/tests/e2e/test_tru.py
  trulens_eval/tests/e2e/test_tru_llama.py
Labels: documentation, size:S, lgtm

#1014 updated App.select_context to support MultiQueryRetriever of langchain
  trulens_eval/examples/experimental/MultiQueryRetrievalLangchain.ipynb
  trulens_eval/trulens_eval/tru_chain.py
Labels: size:L, lgtm

#950 Add Vectara Hallucination Detection Model
  trulens_eval/examples/expositional/models/Vectara_HHEM_evaluator.ipynb
  trulens_eval/trulens_eval/feedback/provider/hugs.py
Labels: documentation, size:XL

#1026 Parametrize temperature for create chat completion
  trulens_eval/trulens_eval/feedback/provider/base.py
Labels: size:S, lgtm

#1027 0.27.0 version bump
  trulens_eval/trulens_eval/__init__.py
Labels: size:XS, lgtm

#1030 pipelines readme
  .azure_pipelines/README.md
  .azure_pipelines/ci-eval-pr.yaml
  .azure_pipelines/ci-eval.yaml
  .azure_pipelines/ci.yaml
Labels: documentation, size:S, lgtm

#997 docs | standards on proper names
  README.md
  docs/trulens_eval/contributing/standards.md
  docs/trulens_eval/gh_top_intro.md
  docs/trulens_eval/intro.md
Labels: documentation, size:S, lgtm

#1029 docs glossary
  Makefile
  docs/trulens_eval/getting_started/core_concepts/feedback_functions.md
  docs/trulens_eval/getting_started/core_concepts/index.md
  mkdocs.yml
  trulens_eval/Makefile
  trulens_explain/Makefile
Labels: documentation, size:L, lgtm

#1035 Fix TruLens docs link in hybrid retriever notebook
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_hybrid_retriever.ipynb
Labels: documentation, size:XS, lgtm

#1034 docs README
  docs/README.md
Labels: documentation, size:S, lgtm

#1036 docs: fix typo
  docs/trulens_eval/evaluation/running_feedback_functions/with_app.md
Labels: documentation, size:XS, lgtm

#1033 more pipelines docs
  .azure_pipelines/README.md
  .azure_pipelines/ci-docs-pr.yaml
  .azure_pipelines/ci-eval-pr.yaml
  .azure_pipelines/ci-eval.yaml
  .azure_pipelines/ci.yaml
Labels: documentation, size:M, lgtm

#1037 Fix azure docs pipeline
  .azure_pipelines/ci-docs-pr.yaml
Labels: documentation, size:S
