Repository truera/trulens, pull requests merged in 2024-10, with the labels that each got.

#1524 SQLAlchemy joinedload on record.app relationship
  src/core/trulens/core/database/sqlalchemy.py
Labels: size:XS, lgtm

#1526 Set criteria for feedbacks correctly.
  src/feedback/trulens/feedback/llm_provider.py
Labels: size:XS, lgtm

#1527 Allow using Snowflake Connector for the actual DB Connector instead of the connection parameters.
  docs/component_guides/logging/where_to_log/log_in_snowflake.md
  docs/reference/connectors/index.md
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  src/connectors/snowflake/trulens/connectors/snowflake/utils/server_side_evaluation_artifacts.py
  tests/e2e/test_snowflake_feedback_evaluation.py
  tests/util/snowflake_test_case.py
Labels: documentation, size:L, lgtm

#1531 fix to sql query bug in dashboard
  src/core/trulens/core/database/connector/base.py
  src/core/trulens/core/database/orm.py
  src/core/trulens/core/session.py
Labels: size:L, lgtm

#1534 trulens-connectors-snowflake for python < 3.12
  src/connectors/snowflake/poetry.lock
  src/connectors/snowflake/pyproject.toml
Labels: dependencies, size:S, lgtm

#1485 OTEL import/export
  examples/experimental/export_dummy_example.ipynb
  examples/experimental/export_llamaindex_example.ipynb
  poetry.lock
  pyproject.toml
  src/apps/langchain/poetry.lock
  src/apps/llamaindex/poetry.lock
  src/apps/llamaindex/trulens/apps/llamaindex/tru_llama.py
  src/apps/nemo/poetry.lock
  src/benchmark/poetry.lock
  src/core/poetry.lock
  src/core/trulens/core/app.py
  src/core/trulens/core/experimental/__init__.py
  src/core/trulens/core/feedback/feedback.py
  src/core/trulens/core/instruments.py
  src/core/trulens/core/schema/base.py
  src/core/trulens/core/schema/record.py
  src/core/trulens/core/schema/select.py
  src/core/trulens/core/schema/types.py
  src/core/trulens/core/session.py
  src/core/trulens/core/utils/containers.py
  src/core/trulens/core/utils/imports.py
  src/core/trulens/core/utils/json.py
  src/core/trulens/core/utils/pyschema.py
  src/core/trulens/core/utils/python.py
  src/core/trulens/core/utils/serial.py
  src/core/trulens/experimental/README.md
  src/core/trulens/experimental/otel_tracing/README.md
  src/core/trulens/experimental/otel_tracing/core/_utils/wrap.py
  src/core/trulens/experimental/otel_tracing/core/app.py
  src/core/trulens/experimental/otel_tracing/core/instruments.py
  src/core/trulens/experimental/otel_tracing/core/otel.py
  src/core/trulens/experimental/otel_tracing/core/session.py
  src/core/trulens/experimental/otel_tracing/core/trace.py
  src/dashboard/poetry.lock
  src/feedback/poetry.lock
  src/providers/bedrock/poetry.lock
  src/providers/cortex/poetry.lock
  src/providers/huggingface/poetry.lock
  src/providers/langchain/poetry.lock
  src/providers/litellm/poetry.lock
  src/providers/openai/poetry.lock
  src/trulens_eval/poetry.lock
  tests/e2e/golden/customapp.json
  tests/e2e/golden/customapp_context_relevance.def.json
  tests/e2e/golden/customapp_context_relevance.result.json
  tests/e2e/golden/customapp_language_match.def.json
  tests/e2e/golden/customapp_language_match.result.json
  tests/e2e/golden/customapp_record.json
  tests/e2e/golden/dummy.json
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
  tests/utils.py
Labels: dependencies, size:XXL, lgtm

#1528 split off python compatibility utilities
  .grit/dealias_trulens_eval.grit
  src/apps/llamaindex/trulens/apps/llamaindex/tru_llama.py
  src/core/trulens/core/_utils/pycompat.py
  src/core/trulens/core/app.py
  src/core/trulens/core/database/connector/base.py
  src/core/trulens/core/feedback/feedback.py
  src/core/trulens/core/schema/app.py
  src/core/trulens/core/schema/record.py
  src/core/trulens/core/schema/select.py
  src/core/trulens/core/schema/types.py
  src/core/trulens/core/session.py
  src/core/trulens/core/utils/imports.py
  src/core/trulens/core/utils/python.py
  src/core/trulens/core/utils/threading.py
  src/core/trulens/experimental/otel_tracing/core/otel.py
  src/providers/huggingface/trulens/providers/huggingface/provider.py
  src/trulens_eval/trulens_eval/utils/python.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
  tests/utils.py
Labels: size:L, lgtm

#1541 output scoring fixes
  src/feedback/trulens/feedback/llm_provider.py
  src/feedback/trulens/feedback/prompts.py
  src/feedback/trulens/feedback/v2/feedback.py
Labels: size:L, lgtm

#1535 Fix homepage blog link
  docs/overrides/home.html
Labels: documentation, size:XS, lgtm

#1545 Information retrieval (search) metrics computation with ground truth datasets - notebook + metrics implementation
  examples/quickstart/groundtruth_evals_for_retrieval_systems.ipynb
  src/feedback/trulens/feedback/groundtruth.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: size:XL, lgtm

#1551 handle partial functions for feedback functions
  src/core/trulens/core/utils/pyschema.py
Labels: size:XS, lgtm

#1553 Fix Selector AttributeError
  src/core/trulens/core/schema/select.py
Labels: size:XS, lgtm

#1550 use 0-3 output scaling for relevance by default
  src/feedback/trulens/feedback/v2/feedback.py
Labels: size:XS, lgtm

#1549 More error handling for groundedness internal steps
  src/feedback/trulens/feedback/llm_provider.py
Labels: size:M, lgtm

#1523 Endpoints as Multitons and Singletons represented as metaclasses
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/feedback/endpoint.py
  src/core/trulens/core/session.py
  src/core/trulens/core/utils/python.py
  src/core/trulens/core/utils/threading.py
  src/core/trulens/experimental/otel_tracing/core/trace.py
  src/feedback/trulens/feedback/dummy/endpoint.py
  src/providers/bedrock/trulens/providers/bedrock/endpoint.py
  src/providers/bedrock/trulens/providers/bedrock/provider.py
  src/providers/cortex/trulens/providers/cortex/endpoint.py
  src/providers/huggingface/trulens/providers/huggingface/endpoint.py
  src/providers/langchain/trulens/providers/langchain/endpoint.py
  src/providers/litellm/trulens/providers/litellm/endpoint.py
  src/providers/openai/trulens/providers/openai/endpoint.py
  src/trulens_eval/trulens_eval/utils/python.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
  tests/utils.py
Labels: size:XL, lgtm

#1554 Simplify system prompt generation conditions with output space and criteria
  src/feedback/trulens/feedback/llm_provider.py
Labels: size:L

#1544 Fix SnowflakeConnector connection URL
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
Labels: size:M, lgtm

#1462 RAG triads llm as judges benchmark - adding meta-eval metrics for correlation measurement and experiment notebooks
  .gitignore
  src/benchmark/trulens/benchmark/benchmark_frameworks/dataset/beir_loader.py
  src/benchmark/trulens/benchmark/benchmark_frameworks/experiments/rag_triad_baselines.ipynb
  src/benchmark/trulens/benchmark/benchmark_frameworks/tru_benchmark_experiment.py
  src/core/trulens/core/feedback/feedback.py
  src/core/trulens/core/schema/feedback.py
  src/feedback/trulens/feedback/groundtruth.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: size:XXL, lgtm

#1556 Add option to filter trivial statements for groundedness measure
  src/feedback/trulens/feedback/llm_provider.py
Labels: size:XS, lgtm

#1555 Store endpoints in list with weakref.ref
  src/core/trulens/core/utils/python.py
Labels: size:S, lgtm

#1537 (some) release pipeline fixes
  Makefile
  poetry.lock
  src/apps/langchain/poetry.lock
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/poetry.lock
  src/apps/nemo/poetry.lock
  src/benchmark/poetry.lock
  src/core/poetry.lock
  src/dashboard/poetry.lock
  src/feedback/poetry.lock
  src/providers/bedrock/poetry.lock
  src/providers/cortex/poetry.lock
  src/providers/huggingface/poetry.lock
  src/providers/langchain/poetry.lock
  src/providers/langchain/pyproject.toml
  src/providers/litellm/poetry.lock
  src/providers/openai/poetry.lock
  src/trulens_eval/poetry.lock
  tests/e2e/test_endpoints.py
  tests/legacy/test_trulens_eval_notebooks.py
Labels: dependencies, size:M, lgtm

#1557 bumping conda package build to 1.1.0
  src/connectors/snowflake/meta.yaml
  src/core/meta.yaml
  src/feedback/meta.yaml
  src/providers/cortex/meta.yaml
Labels: dependencies, size:S, lgtm

#1558 Fix ground truth dataset persistence notebook after the ground truth search metrics update
  examples/quickstart/groundtruth_dataset_persistence.ipynb
  src/feedback/trulens/feedback/v2/feedback.py
Labels: size:S, lgtm

#1565 warning and docpage for bad context
  docs/component_guides/other/no_context_warning.md
  examples/dev/dummy_app/app.py
  examples/dev/dummy_app/tool.py
  examples/experimental/dummy_example.ipynb
  src/core/trulens/core/app.py
  src/core/trulens/core/feedback/endpoint.py
  src/core/trulens/core/instruments.py
  src/core/trulens/core/schema/record.py
  src/core/trulens/core/utils/containers.py
  src/core/trulens/core/utils/python.py
  src/feedback/trulens/feedback/dummy/endpoint.py
  tests/unit/static/golden/api.trulens.3.11.yaml
Labels: documentation, size:XL, lgtm

#1559 Comparison notebook: TruLens groundedness vs RAGAS faithfulness. and add dataset preprocessing utils
  poetry.lock
  src/benchmark/trulens/benchmark/benchmark_frameworks/experiments/competitive_analysis.ipynb
  src/benchmark/trulens/benchmark/benchmark_frameworks/experiments/dataset_preprocessing.py
  src/benchmark/trulens/benchmark/benchmark_frameworks/experiments/rag_triad_baselines.ipynb
Labels: dependencies, size:XXL, lgtm

#1566 test dummy endpoints
  examples/experimental/dummy_example.ipynb
  src/core/trulens/core/feedback/endpoint.py
  src/feedback/trulens/feedback/dummy/endpoint.py
  src/feedback/trulens/feedback/dummy/provider.py
  tests/e2e/test_endpoints.py
Labels: size:L, lgtm

#1576 fix docs
  docs/component_guides/logging/where_to_log/log_in_snowflake.md
Labels: documentation, size:S

#1570 Use conda channel trulens packages by default.
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  src/connectors/snowflake/trulens/connectors/snowflake/utils/server_side_evaluation_artifacts.py
  tests/util/snowflake_test_case.py
  zip_wheels.sh
Labels: size:M, lgtm

#1561 Fix 'reason not generated'
  src/feedback/trulens/feedback/v2/feedback.py
Labels: size:XS, lgtm

#1568 import rename listings
  docs/contributing/standards.md
  src/core/trulens/_mods.py
  src/dashboard/trulens/dashboard/Leaderboard.py
  src/trulens_eval/trulens_eval/Leaderboard.py
  tests/_mods.py
  tests/e2e/test_tru_chain.py
  tests/unit/static/test_static.py
  tests/unit/test_feedback.py
  tests/utils.py
Labels: documentation, size:L, lgtm

#1580 Use `SnowflakeConnector` in stored proc.
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  src/connectors/snowflake/trulens/connectors/snowflake/utils/server_side_evaluation_stored_procedure.py
Labels: size:M, lgtm

#1536 Reuse Snowpark session during most tests.
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  tests/e2e/test_snowflake_connection.py
  tests/e2e/test_snowflake_feedback_evaluation.py
  tests/util/snowflake_test_case.py
Labels: size:M, lgtm

#1581 Have `run_leaderboard` should fail more clearly if it's unable to authenticate at Snowflake due to being created by a `snowpark_session`.
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  src/dashboard/trulens/dashboard/run.py
  tests/e2e/test_snowflake_connection.py
Labels: size:L, lgtm

#1583 Add quickstarts to docs
  examples/quickstart/add_dataframe_quickstart.ipynb
  examples/quickstart/custom_stream.ipynb
  examples/quickstart/groundtruth_dataset_persistence.ipynb
  examples/quickstart/groundtruth_evals_for_retrieval_systems.ipynb
  mkdocs.yml
Labels: documentation, size:S, lgtm

#1577 Add tags to schema during snowflake app creation
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  src/core/trulens/core/database/base.py
  src/core/trulens/core/database/sqlalchemy.py
Labels: size:M

#1584 Blocking guardrails
  docs/component_guides/guardrails/index.md
  docs/component_guides/guardrails/input_blocking_guardrails.png
  examples/quickstart/blocking_guardrails.ipynb
  src/core/trulens/core/guardrails/base.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
  tests/unit/test_guardrails.py
Labels: documentation, size:XL, lgtm

#1587 Use proper golden set format.
  examples/expositional/frameworks/llama_index/llama_index_groundtruth.ipynb
Labels: size:S, lgtm

#1585 Use ggshield for local secret scanning
  DEVELOPMENT.md
  Makefile
Labels: size:S, lgtm

#1539 TruLens v1.1.0
  docs/blog/posts/trulens_1_1_dashboard_updates.md
  poetry.lock
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/pyproject.toml
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  src/core/pyproject.toml
  src/dashboard/pyproject.toml
  src/feedback/pyproject.toml
  src/feedback/trulens/feedback/llm_provider.py
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M, lgtm

#1588 Fix bad merge for snowflake connector.
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
Labels: size:XS, lgtm

#1590 Fix `poetry.lock` `boto3` dependency hashes.
  poetry.lock
Labels: dependencies, size:XS

#1589 Always ensure endpoint context variable is cleaned up.
  src/core/trulens/core/feedback/endpoint.py
  tests/e2e/test_context_variables.py
Labels: size:L, lgtm

#1586 defaults for each contextvar
  poetry.lock
  src/apps/langchain/poetry.lock
  src/apps/llamaindex/poetry.lock
  src/apps/nemo/poetry.lock
  src/benchmark/poetry.lock
  src/core/poetry.lock
  src/core/trulens/core/app.py
  src/core/trulens/core/feedback/endpoint.py
  src/core/trulens/core/instruments.py
  src/core/trulens/core/utils/serial.py
  src/dashboard/poetry.lock
  src/feedback/poetry.lock
  src/providers/bedrock/poetry.lock
  src/providers/cortex/poetry.lock
  src/providers/huggingface/poetry.lock
  src/providers/langchain/poetry.lock
  src/providers/litellm/poetry.lock
  src/providers/openai/poetry.lock
  src/trulens_eval/poetry.lock
  tests/unit/static/golden/api.trulens.3.11.yaml
Labels: size:S, lgtm

#1594 Make sure to clean before uploading docs.
  Makefile
Labels: size:XS, lgtm

#1597 Update dev guide with git lfs instructions
  DEVELOPMENT.md
Labels: documentation, size:XS, lgtm

#1598 TruLens v1.2.0
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/pyproject.toml
  src/core/pyproject.toml
  src/dashboard/pyproject.toml
  src/feedback/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M, lgtm

#1600 Don't check for user and account in snowpark sessions because Streamlit apps might hide them.
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
Labels: size:XS, lgtm

#1592 catch source code not available in `code_line`
  src/core/trulens/core/utils/python.py
Labels: size:XS, lgtm

#1595 use float nan in place of numpy for skipped evals
  src/core/trulens/core/feedback/feedback.py
Labels: size:S, lgtm

#1601 Fix the misspelled trulens-providers-openai package in examples
  examples/quickstart/groundtruth_dataset_persistence.ipynb
  examples/quickstart/groundtruth_evals.ipynb
  examples/quickstart/groundtruth_evals_for_retrieval_systems.ipynb
Labels: size:XS, lgtm

#1605 fix assertion to nan
  tests/unit/test_feedback.py
Labels: size:XS, lgtm

#1603 TruLens v1.2.1
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/pyproject.toml
  src/core/pyproject.toml
  src/dashboard/pyproject.toml
  src/feedback/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M, lgtm

#1604 Use snowflake connector over snowpark session in trulens Snowflake DB connector as snowpark session isn't thread-safe.
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  src/connectors/snowflake/trulens/connectors/snowflake/utils/server_side_evaluation_artifacts.py
Labels: size:M, lgtm

#1609 Don't open extra Snowflake connections and don't recycle connections as quickly.
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
Labels: size:M, lgtm

#1611 Remove unnecessary deps from `trulens-connectors-snowflake`.
  poetry.lock
  src/apps/langchain/poetry.lock
  src/apps/llamaindex/poetry.lock
  src/apps/nemo/poetry.lock
  src/benchmark/poetry.lock
  src/connectors/snowflake/poetry.lock
  src/connectors/snowflake/pyproject.toml
  src/core/poetry.lock
  src/dashboard/poetry.lock
  src/feedback/poetry.lock
  src/providers/bedrock/poetry.lock
  src/providers/cortex/poetry.lock
  src/providers/huggingface/poetry.lock
  src/providers/langchain/poetry.lock
  src/providers/litellm/poetry.lock
  src/providers/openai/poetry.lock
  src/trulens_eval/poetry.lock
  tests/util/snowflake_test_case.py
Labels: dependencies, size:S, lgtm

#1613 Bump version to 1.2.2.
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/pyproject.toml
  src/core/pyproject.toml
  src/dashboard/pyproject.toml
  src/feedback/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M, lgtm

#1618 Bump conda versions (i.e. update `meta.yaml` files) to 1.2.2.
  src/connectors/snowflake/meta.yaml
  src/core/meta.yaml
  src/feedback/meta.yaml
  src/providers/cortex/meta.yaml
Labels: dependencies, size:S, lgtm

#1617 Allow Cortex provider to only take a connection object.
  examples/expositional/frameworks/cortexchat/cortex_chat_quickstart.ipynb
  src/providers/cortex/trulens/providers/cortex/provider.py
Labels: size:XS

#1610 Fix code example formatting in docs
  docs/component_guides/evaluation/feedback_aggregation.md
  docs/component_guides/evaluation/feedback_anatomy.md
  docs/component_guides/evaluation/feedback_selectors/index.md
  docs/component_guides/evaluation/feedback_selectors/selecting_components.md
  docs/component_guides/evaluation/feedback_selectors/selector_shortcuts.md
  docs/component_guides/evaluation/generate_test_cases.md
  docs/component_guides/evaluation/running_feedback_functions/existing_data.md
  docs/component_guides/evaluation/running_feedback_functions/with_app.md
  docs/component_guides/guardrails/index.md
  docs/component_guides/other/no_context_warning.md
  docs/component_guides/other/uninstalling.md
  src/core/trulens/apps/custom.py
  src/core/trulens/apps/virtual.py
  src/providers/cortex/trulens/providers/cortex/provider.py
  src/providers/huggingface/trulens/providers/huggingface/provider.py
Labels: documentation, size:XL

#1622 Fix old references to mae in GroundTruthAgreement feedback function
  examples/experimental/cortex_finetuning_groundedness_ff.ipynb
  src/benchmark/trulens/benchmark/answer_relevance_benchmark_small.ipynb
  src/benchmark/trulens/benchmark/comprehensiveness_benchmark.ipynb
  src/benchmark/trulens/benchmark/context_relevance_benchmark_small.ipynb
Labels: size:S, lgtm

#1623 Add try on tag creation since its an enterprise feature
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
Labels: size:M, lgtm

#1624 try catch on tag creation (#1623)
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
Labels: size:M, lgtm

#1625 Bump version to 1.2.3
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/pyproject.toml
  src/core/pyproject.toml
  src/dashboard/pyproject.toml
  src/feedback/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M, lgtm
