Repository truera/trulens, pull requests merged in 2024-08, with the labels that each got.

#1313 Fix issue with streamlit leaderboard component
  trulens_eval/trulens_eval/streamlit.py
Labels: size:XS, lgtm

#1318 Fix embeddings-based feedback functions
  trulens_eval/tests/e2e/test_embedding_feedback.py
  trulens_eval/trulens_eval/feedback/embeddings.py
  trulens_eval/trulens_eval/requirements.optional.txt
Labels: size:L, lgtm

#1314 [SNOW-1565351] Allow connection through Snowflake.
  .azure_pipelines/ci-eval-pr.yaml
  docs/trulens_eval/tracking/logging/where_to_log/log_in_snowflake.md
  trulens_eval/tests/e2e/test_snowflake_connection.py
  trulens_eval/trulens_eval/requirements.optional.txt
  trulens_eval/trulens_eval/tru.py
Labels: size:L, lgtm

#1321 Update vscode formatting to use Ruff for Python.
  .vscode/extensions.json
  .vscode/settings.json
Labels: size:XS, lgtm

#1282 [SNOW-1531256] Benchmarking - meta-evaluation as app + v1 prompt param + aggregator metrics
  trulens_eval/trulens_eval/feedback/__init__.py
  trulens_eval/trulens_eval/feedback/benchmark_frameworks/meta_evaluation_examples.ipynb
  trulens_eval/trulens_eval/feedback/benchmark_frameworks/tru_benchmark_experiment.py
  trulens_eval/trulens_eval/feedback/feedback.py
  trulens_eval/trulens_eval/feedback/groundtruth.py
  trulens_eval/trulens_eval/feedback/prompts.py
  trulens_eval/trulens_eval/feedback/provider/base.py
  trulens_eval/trulens_eval/feedback/provider/bedrock.py
  trulens_eval/trulens_eval/feedback/v2/feedback.py
  trulens_eval/trulens_eval/requirements.txt
  trulens_eval/trulens_eval/schema/feedback.py
  trulens_eval/trulens_eval/tests/benchmark_frameworks/eval_as_recommendation.py
  trulens_eval/trulens_eval/tests/context_relevance_benchmark_calibration.ipynb
  trulens_eval/trulens_eval/tests/results/Claude-2_score_groundtruth_pairs.csv
  trulens_eval/trulens_eval/tests/results/GPT-3.5-Turbo_score_groundtruth_pairs.csv
  trulens_eval/trulens_eval/tests/results/GPT-4-Turbo-latest_score_groundtruth_pairs.csv
  trulens_eval/trulens_eval/tests/results/GPT-4-Turbo_score_groundtruth_pairs.csv
  trulens_eval/trulens_eval/tests/results/all_context_relevance_benchmark.csv
  trulens_eval/trulens_eval/tests/results/results_comprehensiveness_benchmark.csv
  trulens_eval/trulens_eval/tests/results/results_temp_scaling_gpt-3.5.csv
  trulens_eval/trulens_eval/tests/results/results_temp_scaling_gpt-4.csv
  trulens_eval/trulens_eval/tests/results/results_verbalized_ece_t_0.3.csv
  trulens_eval/trulens_eval/tests/results/results_verbalized_ece_t_0.7.csv
  trulens_eval/trulens_eval/tests/results/results_verbalized_ece_t_0.csv
  trulens_eval/trulens_eval/tests/results/results_verbalized_ece_t_1.csv
  trulens_eval/trulens_eval/tru.py
  trulens_eval/trulens_eval/utils/generated.py
Labels: dependencies, size:XXL, lgtm

#1330 Bug-fix: use 0 - 10 for default score range for ff other than context relevance
  trulens_eval/trulens_eval/feedback/provider/base.py
Labels: size:XS, lgtm

#1327 Spellchecking
  .azure_pipelines/templates/run-tests.yaml
  docs/trulens/contributing/design.md
  docs/trulens/evaluation/feedback_selectors/selecting_components.md
  docs/trulens/evaluation_benchmarks/index.md
  docs/trulens/tracking/instrumentation/langchain.ipynb
  docs/trulens/tracking/instrumentation/llama_index.ipynb
  docs/trulens/tracking/instrumentation/nemo.ipynb
  examples/experimental/MultiQueryRetrievalLangchain.ipynb
  examples/experimental/deferred_example.ipynb
  examples/experimental/dummy_example.ipynb
  examples/experimental/generate_test_set.ipynb
  examples/experimental/random_evaluation.ipynb
  examples/expositional/frameworks/canopy/canopy_quickstart.ipynb
  examples/expositional/frameworks/langchain/langchain_retrieval_agent.ipynb
  examples/expositional/frameworks/llama_index/llama_index_queryplanning.ipynb
  examples/expositional/frameworks/openai_assistants/openai_assistants_api.ipynb
  examples/expositional/models/Vectara_HHEM_evaluator.ipynb
  mkdocs.yml
  poetry.lock
  src/benchmark/trulens/benchmark/context_relevance_benchmark_calibration.ipynb
  src/benchmark/trulens/benchmark/groundedness_benchmark.ipynb
  src/benchmark/trulens/benchmark/groundedness_benchmark_abstentions.ipynb
  src/benchmark/trulens/benchmark/groundedness_benchmark_snowflake_arctic.ipynb
  src/core/poetry.lock
  src/core/trulens/core/app/base.py
  src/core/trulens/core/app/custom.py
  src/core/trulens/core/database/base.py
  src/core/trulens/core/database/migrations/__init__.py
  src/core/trulens/core/database/orm.py
  src/core/trulens/core/feedback/endpoint.py
  src/core/trulens/core/feedback/feedback.py
  src/core/trulens/core/instruments.py
  src/core/trulens/core/schema/app.py
  src/core/trulens/core/schema/select.py
  src/core/trulens/core/tru.py
  src/core/trulens/core/utils/imports.py
  src/core/trulens/core/utils/json.py
  src/core/trulens/core/utils/pyschema.py
  src/core/trulens/core/utils/serial.py
  src/dashboard/react_components/record_viewer/src/utils/colors.ts
  src/feedback/trulens/feedback/feedback.py
  src/feedback/trulens/feedback/llm_provider.py
  src/instrument/langchain/poetry.lock
  src/instrument/llamaindex/poetry.lock
  src/instrument/nemo/poetry.lock
  src/providers/bedrock/poetry.lock
  src/providers/langchain/poetry.lock
  src/providers/litellm/poetry.lock
  src/providers/openai/poetry.lock
  src/providers/openai/trulens/providers/openai/provider.py
  tests/integration/test_database.py
Labels: documentation, size:M, lgtm

#1317 Batch write records to server side.
  src/core/trulens/core/app/base.py
  src/core/trulens/core/database/base.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/schema/app.py
  src/core/trulens/core/schema/feedback.py
  src/core/trulens/core/tru.py
Labels: size:L, lgtm

#1324 Adding conda metadata to build a conda package
  .pre-commit-config.yaml
  src/core/meta.yaml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
Labels: size:L, lgtm

#1335 Fix run-dashboard notebooks
  examples/experimental/db_populate.ipynb
  examples/experimental/deferred_example.ipynb
  examples/experimental/dummy_example.ipynb
  examples/experimental/streamlit_appui_example.ipynb
  examples/expositional/end2end_apps/trubot/trubot_example_no_hugs.ipynb
  examples/expositional/end2end_apps/trubot/trubot_populate_db.ipynb
  examples/expositional/use_cases/summarization_eval.ipynb
Labels: size:S, lgtm

#1334 Scoring adjustment bug fix when adapting to new configurable scoring range
  src/feedback/trulens/feedback/generated.py
Labels: size:XS, lgtm

#1333 fail if npm subcommands fail
  src/dashboard/setup.py
Labels: size:S, lgtm

#1340 Fix env variable used in Makefile for optional tests.
  Makefile
Labels: size:XS, lgtm

#1341 Distinguish between the different optional test suites as it's hard to tell what kinda tests are failing.
  .azure_pipelines/templates/run-optional-tests.yaml
Labels: size:XS, lgtm

#1344 Introduce batch record ingestion mode
  src/core/trulens/core/app/base.py
  src/core/trulens/core/schema/app.py
  src/core/trulens/core/schema/feedback.py
Labels: size:M, lgtm

#1328 Conda build changes
  .pre-commit-config.yaml
  Makefile
  examples/expositional/end2end_apps/trubot/webindex.ipynb
  examples/expositional/frameworks/canopy/canopy_quickstart.ipynb
  poetry.lock
  src/benchmark/poetry.lock
  src/benchmark/pyproject.toml
  src/core/poetry.lock
  src/core/pyproject.toml
  src/core/trulens/core/database/base.py
  src/core/trulens/core/database/legacy/migration.py
  src/core/trulens/core/feedback/feedback.py
  src/core/trulens/core/schema/app.py
  src/core/trulens/core/tru.py
  src/core/trulens/core/utils/json.py
  src/core/trulens/core/utils/keys.py
  src/core/trulens/core/utils/serial.py
  src/core/trulens/core/utils/text.py
  src/dashboard/pyproject.toml
  src/dashboard/trulens/dashboard/Leaderboard.py
  src/dashboard/trulens/dashboard/streamlit.py
  src/feedback/poetry.lock
  src/feedback/pyproject.toml
  src/instrument/langchain/poetry.lock
  src/instrument/langchain/pyproject.toml
  src/instrument/llamaindex/poetry.lock
  src/instrument/llamaindex/pyproject.toml
  src/instrument/nemo/poetry.lock
  src/instrument/nemo/pyproject.toml
  src/providers/bedrock/poetry.lock
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/poetry.lock
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/poetry.lock
  src/providers/huggingface/pyproject.toml
  src/providers/huggingface/trulens/providers/huggingface/provider.py
  src/providers/langchain/poetry.lock
  src/providers/langchain/pyproject.toml
  src/providers/litellm/poetry.lock
  src/providers/litellm/pyproject.toml
  src/providers/openai/poetry.lock
  src/providers/openai/pyproject.toml
  tests/unit/core/utils/test_json_utils.py
  tests/unit/core/utils/test_text_utils.py
Labels: size:L, lgtm

#1347 Fix up migration script and docs.
  docs/trulens/contributing/migration.md
  src/core/trulens/core/database/migrations/data.py
  src/core/trulens/core/database/migrations/script.py.mako
Labels: documentation, size:M, lgtm

#1352 Format Fixes
  .vscode/settings.json
  docs/trulens/tracking/instrumentation/llama_index.ipynb
  examples/experimental/appui_example.ipynb
  examples/experimental/cortex_finetuning_groundedness_ff.ipynb
  examples/experimental/dashboard_appui.ipynb
  examples/experimental/db_populate.ipynb
  examples/experimental/dev_notebook.ipynb
  examples/experimental/streamlit_appui_example.ipynb
  pyproject.toml
  src/benchmark/trulens/benchmark/benchmark_frameworks/meta_evaluation_examples.ipynb
  src/benchmark/trulens/benchmark/comprehensiveness_benchmark.ipynb
  src/benchmark/trulens/benchmark/context_relevance_benchmark.ipynb
  src/benchmark/trulens/benchmark/groundedness_benchmark_abstentions.ipynb
  src/core/trulens/core/database/migrations/__init__.py
  src/core/trulens/core/feedback/endpoint.py
  src/core/trulens/core/tru.py
  src/core/trulens/core/utils/json.py
  src/core/trulens/core/utils/keys.py
  src/core/trulens/core/utils/serial.py
  src/dashboard/setup.py
  src/dashboard/trulens/dashboard/appui.py
  src/dashboard/trulens/dashboard/notebook_utils.py
  src/dashboard/trulens/dashboard/pages/Evaluations.py
  src/dashboard/trulens/dashboard/ux/styles.py
  src/providers/bedrock/trulens/providers/bedrock/provider.py
  tests/e2e/test_dummy.py
  tests/e2e/test_providers.py
  tests/e2e/test_serial.py
  tests/e2e/test_tru_chain.py
  tests/e2e/test_tru_llama.py
  tests/test.py
  tests/unit/core/utils/test_json_utils.py
Labels: size:XL, lgtm

#1337 Prompt improvement: COT should go before score in template
  src/feedback/trulens/feedback/prompts.py
Labels: size:XS, lgtm

#1350 Dummy Provider Docs Fixes
  docs/gen_ref_pages.py
  docs/trulens_eval/api/dev/dummy_app.md
  docs/trulens_eval/api/endpoint/dummy.md
  docs/trulens_eval/api/provider/dummy.md
  examples/dev/dummy_app/__init__.py
  examples/dev/dummy_app/llm.py
  mkdocs.yml
  src/dashboard/trulens/dashboard/components/__init__.py
  src/feedback/trulens/feedback/dummy/__init__.py
  src/feedback/trulens/feedback/dummy/endpoint.py
  src/feedback/trulens/feedback/dummy/provider.py
Labels: documentation, size:S, lgtm

#1355 Fix alembic migration env.py: un-set default sqlalchemy_url in alembic.ini
  src/core/trulens/core/database/migrations/alembic.ini
Labels: size:XS, lgtm

#1362 install --pre in noteobooks
  examples/experimental/MultiQueryRetrievalLangchain.ipynb
  examples/experimental/random_evaluation.ipynb
  examples/expositional/frameworks/canopy/canopy_quickstart.ipynb
  examples/expositional/frameworks/langchain/langchain_agents.ipynb
  examples/expositional/frameworks/langchain/langchain_async.ipynb
  examples/expositional/frameworks/langchain/langchain_ensemble_retriever.ipynb
  examples/expositional/frameworks/langchain/langchain_groundtruth.ipynb
  examples/expositional/frameworks/langchain/langchain_math_agent.ipynb
  examples/expositional/frameworks/langchain/langchain_model_comparison.ipynb
  examples/expositional/frameworks/langchain/langchain_retrieval_agent.ipynb
  examples/expositional/frameworks/langchain/langchain_summarize.ipynb
  examples/expositional/frameworks/llama_index/llama_index_agents.ipynb
  examples/expositional/frameworks/llama_index/llama_index_async.ipynb
  examples/expositional/frameworks/llama_index/llama_index_complex_evals.ipynb
  examples/expositional/frameworks/llama_index/llama_index_groundtruth.ipynb
  examples/expositional/frameworks/llama_index/llama_index_hybrid_retriever.ipynb
  examples/expositional/frameworks/llama_index/llama_index_multimodal.ipynb
  examples/expositional/frameworks/llama_index/llama_index_queryplanning.ipynb
  examples/expositional/frameworks/llama_index/llama_index_retrievalquality.ipynb
  examples/expositional/frameworks/nemoguardrails/nemoguardrails_custom_action_with_feedback_example.ipynb
  examples/expositional/frameworks/nemoguardrails/nemoguardrails_feedback_action_example.ipynb
  examples/expositional/frameworks/nemoguardrails/nemoguardrails_trurails_example.ipynb
  examples/expositional/frameworks/openai_assistants/openai_assistants_api.ipynb
  examples/expositional/models/Vectara_HHEM_evaluator.ipynb
  examples/expositional/models/arctic_quickstart.ipynb
  examples/expositional/models/azure_openai_langchain.ipynb
  examples/expositional/models/azure_openai_llama_index.ipynb
  examples/expositional/models/bedrock.ipynb
  examples/expositional/models/bedrock_finetuning_experiments.ipynb
  examples/expositional/models/claude3_quickstart.ipynb
  examples/expositional/models/gemini_multi_modal.ipynb
  examples/expositional/models/google_vertex_quickstart.ipynb
  examples/expositional/models/litellm_quickstart.ipynb
  examples/expositional/models/local_vs_remote_huggingface_feedback_functions.ipynb
  examples/expositional/models/ollama_quickstart.ipynb
  examples/expositional/use_cases/iterate_on_rag/1_rag_prototype.ipynb
  examples/expositional/use_cases/iterate_on_rag/2_honest_rag.ipynb
  examples/expositional/use_cases/iterate_on_rag/3_harmless_eval.ipynb
  examples/expositional/use_cases/iterate_on_rag/4_harmless_rag.ipynb
  examples/expositional/use_cases/iterate_on_rag/5_helpful_eval.ipynb
  examples/expositional/use_cases/language_verification.ipynb
  examples/expositional/use_cases/model_comparison.ipynb
  examples/expositional/use_cases/moderation.ipynb
  examples/expositional/use_cases/pii_detection.ipynb
  examples/expositional/use_cases/summarization_eval.ipynb
  examples/expositional/vector-dbs/faiss/langchain_faiss_example.ipynb
  examples/expositional/vector-dbs/milvus/milvus_evals_build_better_rags.ipynb
  examples/expositional/vector-dbs/milvus/milvus_simple.ipynb
  examples/expositional/vector-dbs/mongodb_atlas/atlas_quickstart.ipynb
  examples/expositional/vector-dbs/pinecone/pinecone_evals_build_better_rags.ipynb
  examples/expositional/vector-dbs/pinecone/pinecone_quickstart.ipynb
  examples/quickstart/existing_data_quickstart.ipynb
  examples/quickstart/groundtruth_evals.ipynb
  examples/quickstart/human_feedback.ipynb
  examples/quickstart/langchain_quickstart.ipynb
  examples/quickstart/llama_index_quickstart.ipynb
  examples/quickstart/prototype_evals.ipynb
  examples/quickstart/quickstart.ipynb
  examples/quickstart/text2text_quickstart.ipynb
Labels: size:M, lgtm

#1348 GroundTruth dataset implementation (ORM and DAO layers)
  src/benchmark/trulens/benchmark/benchmark_frameworks/tru_benchmark_experiment.py
  src/core/trulens/core/database/base.py
  src/core/trulens/core/database/migrations/data.py
  src/core/trulens/core/database/migrations/env.py
  src/core/trulens/core/database/migrations/versions/3_add_groundtruth_and_dataset_tables.py
  src/core/trulens/core/database/orm.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/schema/dataset.py
  src/core/trulens/core/schema/groundtruth.py
  src/core/trulens/core/schema/types.py
  src/feedback/trulens/feedback/groundtruth.py
Labels: documentation, size:XL, lgtm

#1354 Regardless of `FeedbackMode`, always defer feedbacks that are run on Snowflake.
  src/core/trulens/core/app/base.py
  tests/e2e/test_snowflake_feedback_evaluation.py
Labels: size:M, lgtm

#1361 Fix delete app API
  src/core/trulens/core/database/sqlalchemy.py
Labels: size:XS, lgtm

#1353 GroundTruth eval: API changes
  examples/quickstart/groundtruth_dataset_persistence.ipynb
  examples/quickstart/groundtruth_evals.ipynb
  src/benchmark/trulens/benchmark/benchmark_frameworks/tru_benchmark_experiment.py
  src/benchmark/trulens/benchmark/test_cases.py
  src/core/trulens/core/database/migrations/env.py
  src/core/trulens/core/dataset/beir_loader.py
  src/core/trulens/core/tru.py
  src/feedback/trulens/feedback/groundtruth.py
Labels: documentation, size:XL, lgtm

#1345 trulens-legacy
  Makefile
  poetry.lock
  pyproject.toml
  src/core/poetry.lock
  src/core/trulens/core/utils/deprecation.py
  src/core/trulens/core/utils/imports.py
  src/core/trulens/core/utils/requirements.optional.txt
  src/core/trulens/core/utils/requirements.txt
  src/instrument/langchain/poetry.lock
  src/instrument/llamaindex/poetry.lock
  src/instrument/nemo/poetry.lock
  src/providers/bedrock/poetry.lock
  src/providers/huggingface/poetry.lock
  src/providers/huggingface/trulens/providers/huggingface/provider.py
  src/providers/langchain/poetry.lock
  src/providers/litellm/poetry.lock
  src/providers/openai/poetry.lock
  src/trulens_eval/README.md
  src/trulens_eval/poetry.lock
  src/trulens_eval/pyproject.toml
  src/trulens_eval/trulens_eval/__init__.py
  src/trulens_eval/trulens_eval/database/__init__.py
  src/trulens_eval/trulens_eval/database/migrations/__init__.py
  src/trulens_eval/trulens_eval/feedback/__init__.py
  src/trulens_eval/trulens_eval/feedback/provider/__init__.py
  src/trulens_eval/trulens_eval/feedback/provider/endpoint/__init__.py
  src/trulens_eval/trulens_eval/react_components/__init__.py
  src/trulens_eval/trulens_eval/react_components/record_viewer/__init__.py
  src/trulens_eval/trulens_eval/schema/__init__.py
  src/trulens_eval/trulens_eval/utils/__init__.py
  tests/e2e/golden/customapp_context_relevance.def.json
  tests/e2e/golden/customapp_language_match.def.json
  tests/unit/static/test_deprecation.py
Labels: dependencies, size:XL, lgtm

#1366 Have Makefile upload target should first build packages.
  Makefile
Labels: size:XS, lgtm

#1309 API dump and deeper trulens_eval compatibility test
  .pre-commit-config.yaml
  .vscode/settings.json
  Makefile
  docs/trulens_eval/api/dev/dummy_app.md
  docs/trulens_eval/api/dev/index.md
  docs/trulens_eval/api/dev/test.md
  examples/experimental/dummy_example.ipynb
  poetry.lock
  pyproject.toml
  src/core/trulens/core/__init__.py
  src/core/trulens/core/database/migrations/versions/6_populate_app_name_and_version_data.py
  src/core/trulens/core/schema/app.py
  src/core/trulens/core/session.py
  src/core/trulens/core/utils/imports.py
  src/core/trulens/core/utils/python.py
  src/dashboard/trulens/dashboard/pages/Apps.py
  src/feedback/trulens/feedback/v2/provider/base.py
  src/instrument/langchain/poetry.lock
  src/instrument/llamaindex/poetry.lock
  src/instrument/nemo/poetry.lock
  src/providers/bedrock/poetry.lock
  src/providers/huggingface/poetry.lock
  src/providers/langchain/poetry.lock
  src/providers/litellm/poetry.lock
  src/providers/openai/poetry.lock
  src/trulens_eval/poetry.lock
  tests/api.ipynb
  tests/test.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.12.yaml
  tests/unit/static/test_api.py
  tests/unit/static/test_static.py
  tests/utils.py
Labels: size:XXL, lgtm

#1365 Remove trivial statements before evaluating groundedness
  examples/quickstart/quickstart.ipynb
  src/feedback/trulens/feedback/llm_provider.py
  src/feedback/trulens/feedback/prompts.py
  src/feedback/trulens/feedback/v2/feedback.py
Labels: size:M, lgtm

#1363 Better groundedness UI display
  src/dashboard/trulens/dashboard/pages/Evaluations.py
Labels: size:M, lgtm

#1378 Fix issues with the `Tru` to `TruSession` migration.
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  src/core/trulens/core/app/base.py
  src/core/trulens/core/database/migrations/versions/5_add_app_name_and_version_fields.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/feedback/feedback.py
  src/core/trulens/core/schema/app.py
  src/core/trulens/core/session.py
  tests/util/snowflake_test_case.py
Labels: size:L, lgtm

#1375 langchain provider: predict/predict_messages -> invoke
  src/providers/langchain/trulens/providers/langchain/provider.py
Labels: size:XS, lgtm

#1343 Auth updates for Cortex Provider and database connections + streamlit component updates + dashboard build
  .pre-commit-config.yaml
  docs/trulens/tracking/logging/where_to_log/index.md
  docs/trulens/tracking/logging/where_to_log/log_in_snowflake.md
  examples/expositional/frameworks/langchain/langchain_ensemble_retriever.ipynb
  examples/expositional/models/local_and_OSS_models/local_vs_remote_huggingface_feedback_functions.ipynb
  examples/expositional/use_cases/snowflake_auth_methods.ipynb
  examples/quickstart/langchain_quickstart.ipynb
  examples/quickstart/llama_index_quickstart.ipynb
  examples/quickstart/quickstart.ipynb
  src/core/trulens/core/database/connector/default.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/utils/trulens.py
  src/dashboard/.gitignore
  src/dashboard/setup.py
  src/dashboard/trulens/dashboard/components/record_viewer/dist/assets/SourceCodePro-Bold-839f42df.ttf
  src/dashboard/trulens/dashboard/components/record_viewer/dist/assets/SourceCodePro-Regular-6e5dd049.ttf
  src/dashboard/trulens/dashboard/components/record_viewer/dist/assets/SourceCodePro-SemiBold-ccfba566.ttf
  src/dashboard/trulens/dashboard/components/record_viewer/dist/assets/index-00b8e16d.css
  src/dashboard/trulens/dashboard/components/record_viewer/dist/assets/index-923e1c7a.js
  src/dashboard/trulens/dashboard/components/record_viewer/dist/index.html
  src/dashboard/trulens/dashboard/display.py
  src/dashboard/trulens/dashboard/streamlit.py
  src/providers/cortex/trulens/providers/cortex/provider.py
  tests/unit/static/golden/api.trulens.3.11.yaml
Labels: documentation, size:XL, lgtm

#1382 Fix Groundedness by upgrading and fixing nltk version to >=3.8.2
  src/feedback/pyproject.toml
  src/feedback/trulens/feedback/llm_provider.py
  src/providers/huggingface/pyproject.toml
  src/providers/huggingface/trulens/providers/huggingface/provider.py
  src/providers/litellm/poetry.lock
  src/providers/openai/poetry.lock
Labels: dependencies, size:S, lgtm

#1383 Bump nltk version from 3.8.2 to 3.9.1
  src/feedback/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/litellm/poetry.lock
  src/providers/openai/poetry.lock
Labels: dependencies, size:XS

#1368 [DOCS] coding standards around imports
  docs/trulens/contributing/standards.md
Labels: documentation, size:L, lgtm

#1385 Fix NLTK dependency in release 0.32.0
  trulens_eval/trulens_eval/feedback/provider/base.py
  trulens_eval/trulens_eval/feedback/provider/hugs.py
  trulens_eval/trulens_eval/requirements.txt
Labels: dependencies, size:XS, lgtm

#1386 Fix NLTK dependency in release 0.33.0
  trulens_eval/trulens_eval/feedback/provider/base.py
  trulens_eval/trulens_eval/feedback/provider/hugs.py
  trulens_eval/trulens_eval/requirements.txt
Labels: dependencies, size:XS, lgtm

#1387 Fix NLTK dependency in release 0.31.0
  trulens_eval/trulens_eval/feedback/provider/base.py
  trulens_eval/trulens_eval/feedback/provider/hugs.py
  trulens_eval/trulens_eval/requirements.txt
Labels: dependencies, size:S, lgtm

#1390 version bump 0.33.0 -> 0.33.1
  trulens_eval/trulens_eval/__init__.py
Labels: size:XS

#1389 version bump 0.31.0 -> 0.31.1
  trulens_eval/trulens_eval/__init__.py
Labels: size:XS

#1381 Update connection parameters typing for Cortex provider
  src/providers/cortex/trulens/providers/cortex/provider.py
Labels: size:XS, lgtm

#1377 Set up server-side evaluations.
  .gitignore
  Makefile
  src/connectors/snowflake/pyproject.toml
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  src/connectors/snowflake/trulens/connectors/snowflake/utils/__init__.py
  src/connectors/snowflake/trulens/connectors/snowflake/utils/server_side_evaluation_artifacts.py
  src/connectors/snowflake/trulens/connectors/snowflake/utils/server_side_evaluation_stored_procedure.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/feedback/feedback.py
  src/core/trulens/core/session.py
  src/core/trulens/core/utils/imports.py
  src/providers/cortex/trulens/providers/cortex/provider.py
  tests/e2e/test_snowflake_feedback_evaluation.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.12.yaml
  tests/util/snowflake_test_case.py
  zip_wheels.sh
Labels: size:XL, lgtm

#1393 Stop using internal `pip` module (i.e. `pip._internal.parse_requirements`).
  src/core/trulens/core/utils/imports.py
Labels: size:S, lgtm, 1.0-release

#1396 generate in new module + docs and examples
  docs/trulens/evaluation/generate_test_cases/index.md
  examples/experimental/generate_test_set.ipynb
  examples/experimental/random_evaluation.ipynb
  examples/expositional/vector_stores/mongodb/atlas_quickstart.ipynb
  src/benchmark/trulens/benchmark/generate/__init__.py
  src/benchmark/trulens/benchmark/generate/generate_test_set.py
  tests/unit/static/golden/api.trulens.3.11.yaml
Labels: documentation, size:L, lgtm, 1.0-release

#1394 Clean up migration scripts.
  src/core/trulens/core/database/migrations/versions/1_first_revision.py
  src/core/trulens/core/database/migrations/versions/2_add_run_location_column_to_feedback_defs_table.py
  src/core/trulens/core/database/migrations/versions/3_add_groundtruth_and_dataset_tables.py
  src/core/trulens/core/database/migrations/versions/4_set_ff_id_not_null.py
  src/core/trulens/core/database/migrations/versions/5_add_app_name_and_version_fields.py
  src/core/trulens/core/database/migrations/versions/6_populate_app_name_and_version_data.py
  src/core/trulens/core/database/migrations/versions/7_app_name_version_not_null.py
Labels: size:L, lgtm

#1397 Get e2e optional tests to actually run.
  poetry.lock
  pyproject.toml
  src/benchmark/poetry.lock
  src/connectors/snowflake/pyproject.toml
  src/core/poetry.lock
  src/dashboard/pyproject.toml
  src/feedback/poetry.lock
  src/instrument/langchain/poetry.lock
  src/instrument/llamaindex/poetry.lock
  src/instrument/nemo/poetry.lock
  src/providers/bedrock/poetry.lock
  src/providers/cortex/poetry.lock
  src/providers/huggingface/poetry.lock
  src/providers/langchain/poetry.lock
  src/providers/litellm/poetry.lock
  src/providers/openai/poetry.lock
  src/trulens_eval/poetry.lock
  tests/e2e/test_serial.py
Labels: dependencies, size:XS, lgtm

#1369 Cost tracking with credit usage for Cortex evals
  examples/expositional/models/snowflake_cortex/arctic_quickstart.ipynb
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/schema/base.py
  src/providers/cortex/trulens/providers/cortex/config/cortex_model_costs.json
  src/providers/cortex/trulens/providers/cortex/endpoint.py
  src/providers/cortex/trulens/providers/cortex/provider.py
  tests/e2e/test_endpoints.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.12.yaml
Labels: size:L, lgtm, 1.0-release

#1401 Revert "version bump 0.33.0 -> 0.33.1"
  trulens_eval/trulens_eval/__init__.py
Labels: size:XS, lgtm

#1402 Revert "version bump 0.31.0 -> 0.31.1"
  trulens_eval/trulens_eval/__init__.py
Labels: size:XS, lgtm

#1398 Fix all references to Cortex provider to use the Snowflake connector.
  examples/experimental/cortex_finetuning_groundedness_ff.ipynb
  examples/expositional/models/snowflake_cortex/arctic_quickstart.ipynb
  examples/expositional/use_cases/snowflake_auth_methods.ipynb
  src/benchmark/trulens/benchmark/benchmark_frameworks/meta_evaluation_examples.ipynb
  src/benchmark/trulens/benchmark/benchmark_frameworks/tru_benchmark_experiment.py
  src/benchmark/trulens/benchmark/context_relevance_benchmark_calibration.ipynb
  src/feedback/trulens/feedback/groundtruth.py
  src/providers/cortex/trulens/providers/cortex/provider.py
  tests/e2e/test_endpoints.py
  tests/e2e/test_snowflake_feedback_evaluation.py
Labels: size:L, lgtm

#1403 typos and lint errors
  src/core/trulens/core/app/custom.py
  src/core/trulens/core/instruments.py
  src/core/trulens/core/schema/record.py
  src/core/trulens/core/utils/serial.py
  src/feedback/trulens/feedback/llm_provider.py
  src/feedback/trulens/feedback/prompts.py
  src/feedback/trulens/feedback/v2/feedback.py
  src/trulens_eval/trulens_eval/feedback/prompts.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.12.yaml
Labels: size:M, lgtm

#1391 package dashboard with poetry
  Makefile
  src/dashboard/poetry.lock
  src/dashboard/pyproject.toml
  src/dashboard/setup.py
Labels: dependencies, size:L, lgtm

#1408 Davidkurokawa/handle zips correctly
  Makefile
  src/connectors/snowflake/pyproject.toml
  zip_wheels.sh
Labels: size:S, lgtm

#1374 Filtering for the leaderboard + UI changes for app name/version
  examples/dev/dummy_app/filter_apps.ipynb
  src/core/trulens/core/database/connector/base.py
  src/dashboard/trulens/dashboard/Leaderboard.py
  src/dashboard/trulens/dashboard/pages/Evaluations.py
  src/dashboard/trulens/dashboard/streamlit.py
  src/dashboard/trulens/dashboard/ux/components.py
  tests/unit/static/golden/api.trulens.3.11.yaml
Labels: size:L, lgtm, 1.0-release

#1406 [CP] Stop using internal pip module (i.e. pip._internal.parse_requirements).
  trulens_eval/trulens_eval/utils/imports.py
Labels: size:S, lgtm

#1407 [CP] Stop using internal pip module (i.e. pip._internal.parse_requirements).
  trulens_eval/trulens_eval/utils/imports.py
Labels: size:S, lgtm

#1405 [CP] Stop using internal pip module (i.e. pip._internal.parse_requirements).
  trulens_eval/trulens_eval/utils/imports.py
Labels: size:S, lgtm

#1410 Leaderboard filters patch
  src/dashboard/trulens/dashboard/Leaderboard.py
Labels: size:XS

#1418 docs updates and fixes
  POLICIES.md
  RELEASES.md
  docs/gen_ref_pages.py
  docs/reference/apps/index.md
  docs/reference/connectors/index.md
  docs/reference/index.md
  docs/reference/providers/index.md
  docs/reference/trulens_eval/index.md
  docs/trulens/contributing/development.md
  docs/trulens/contributing/index.md
  docs/trulens/contributing/policies.md
  docs/trulens/contributing/standards.md
  docs/trulens/contributing/techdebt.md
  docs/trulens/getting_started/index.md
  mkdocs.yml
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  src/providers/langchain/trulens/providers/langchain/__init__.py
Labels: documentation, size:XL, lgtm

#1414 packaging + quickstart fixes
  .gitignore
  Makefile
  examples/quickstart/quickstart.ipynb
  src/core/trulens/apps/basic.py
  src/core/trulens/apps/custom.py
  src/core/trulens/apps/virtual.py
  src/core/trulens/core/instruments.py
  src/feedback/trulens/feedback/__init__.py
  src/feedback/trulens/feedback/embeddings.py
  src/trulens_eval/README.md
  tests/unit/static/test_static.py
Labels: dependencies, size:L, lgtm

#1412 Ensure all parts of the `Makefile`'s upload targets work.
  Makefile
Labels: size:S, lgtm

#1413 Never suspend server-side evaluation task.
  src/connectors/snowflake/trulens/connectors/snowflake/utils/server_side_evaluation_artifacts.py
Labels: size:XS, lgtm

#1423 Update docs for generic logging with DefaultDBConnector
  docs/trulens/tracking/logging/where_to_log/index.md
Labels: documentation, size:S, lgtm

#1421 Groundedness with option to not use nltk punk sentence tokenizer
  src/feedback/trulens/feedback/llm_provider.py
  src/feedback/trulens/feedback/prompts.py
  src/feedback/trulens/feedback/v2/feedback.py
Labels: size:M, lgtm, 1.0-release

#1416 [SNOW-1644010] Feedback cost tracking + currency UI changes
  examples/expositional/models/snowflake_cortex/arctic_quickstart.ipynb
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/schema/base.py
  src/dashboard/trulens/dashboard/Leaderboard.py
  src/dashboard/trulens/dashboard/pages/Evaluations.py
  src/providers/cortex/trulens/providers/cortex/endpoint.py
  tests/e2e/test_endpoints.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.12.yaml
Labels: size:L, lgtm, 1.0-release

#1399 Fix back-compat issues with old notebooks
  .gitignore
  Makefile
  POLICIES.md
  docs/reference/index.md
  poetry.lock
  pyproject.toml
  src/apps/nemo/poetry.lock
  src/core/trulens/core/app.py
  src/core/trulens/core/database/connector/base.py
  src/core/trulens/core/guardrails/base.py
  src/core/trulens/core/schema/app.py
  src/core/trulens/core/utils/deprecation.py
  src/core/trulens/core/utils/imports.py
  src/feedback/trulens/feedback/__init__.py
  src/feedback/trulens/feedback/embeddings.py
  src/feedback/trulens/feedback/groundtruth.py
  src/providers/bedrock/poetry.lock
  src/providers/huggingface/poetry.lock
  src/providers/litellm/poetry.lock
  src/providers/openai/poetry.lock
  tests/e2e/test_trulens_eval_notebooks.py
  tests/unit/static/test_static.py
  tests/unit/test_app.py
Labels: dependencies, size:L, lgtm, 1.0-release

#1420 Fix how golden tests are specified.
  tests/e2e/test_dummy.py
  tests/e2e/test_serial.py
  tests/test.py
  tests/unit/static/test_api.py
Labels: size:M, lgtm

#1424 Records app_id data migration
  src/core/trulens/core/database/migrations/versions/8_update_records_app_id.py
Labels: size:M, lgtm, 1.0-release

#1419 Grit pattern for trulens_eval migration
  .grit/dealias_trulens_eval.grit
  .grit/dealias_trulens_eval.py
  .grit/grit.yaml
  .grit/patterns/trulens_eval_migration.md
  docs/trulens/guides/trulens_eval_migration.md
  src/core/trulens/core/session.py
Labels: size:XL, lgtm

#1426 codespell and spellcheck fixes
  Makefile
  docs/reference/index.md
  docs/trulens/tracking/instrumentation/langchain.md
  docs/trulens/tracking/instrumentation/llama_index.md
  docs/trulens/tracking/instrumentation/nemo.md
  examples/dev/__init__.py
  examples/dev/dummy_app/app.py
  examples/dev/dummy_app/dummy_app_example.ipynb
  examples/dev/dummy_app/memory.py
  examples/dev/dummy_app/tool.py
  examples/experimental/deferred_example.ipynb
  examples/expositional/frameworks/langchain/langchain_retrieval_agent.ipynb
  examples/expositional/frameworks/llama_index/llama_index_agents.ipynb
  examples/expositional/frameworks/llama_index/llama_index_complex_evals.ipynb
  examples/expositional/models/google/gemini_multi_modal.ipynb
  examples/expositional/models/local_and_OSS_models/litellm_quickstart.ipynb
  examples/quickstart/groundtruth_dataset_persistence.ipynb
  examples/quickstart/langchain_quickstart.ipynb
  examples/quickstart/llama_index_quickstart.ipynb
  poetry.lock
  pyproject.toml
  src/benchmark/trulens/benchmark/benchmark_frameworks/dataset/beir_loader.py
  src/feedback/trulens/feedback/dummy/endpoint.py
  src/feedback/trulens/feedback/groundtruth.py
  src/providers/bedrock/trulens/providers/bedrock/endpoint.py
  src/trulens_eval/trulens_eval/database/__init__.py
  tests/e2e/test_serial.py
  tests/e2e/test_trulens_eval_notebooks.py
  tests/unit/test_feedback.py
Labels: documentation, size:M, lgtm

#1428 Story updates to quickstart, groundtruth notebooks and Abstention tweak
  examples/quickstart/groundtruth_dataset_persistence.ipynb
  examples/quickstart/groundtruth_evals.ipynb
  examples/quickstart/quickstart.ipynb
  src/feedback/trulens/feedback/v2/feedback.py
Labels: size:L, lgtm

#1430 Pre-release 1.0.1a6
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/pyproject.toml
  src/core/pyproject.toml
  src/dashboard/pyproject.toml
  src/feedback/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M, lgtm

#1371 release announcement + homepage updates
  .grit/patterns/trulens_eval_migration.md
  docs/assets/images/trulens_1_release_graphic_modular.png
  docs/assets/images/trulens_1_release_graphic_split.png
  docs/img/trulens-get-started.png
  docs/img/trulens-get-started.svg
  docs/overrides/home.html
  docs/stylesheets/extra.css
  docs/trulens/getting_started/install.md
  docs/trulens/getting_started/quickstarts/groundtruth_dataset_persistence.ipynb
  docs/trulens/guides/trulens_eval_migration.md
  docs/trulens/intro.md
  docs/trulens/release_blog_1dot.md
  examples/dev/dummy_app/filter_apps.ipynb
Labels: documentation, size:XXL, lgtm, 1.0-release
