Repository truera/trulens, pull requests merged in 2024-11, with the labels that each got.

#1620 Stop using `snowflake.snowpark.session.Session::sql` and use `snowflake.connector.cursor.SnowflakeCursor::execute` instead as its thread-safe.
  examples/expositional/models/snowflake_cortex/arctic_quickstart.ipynb
  examples/expositional/models/snowflake_cortex/cortex_finetuning_experiments.ipynb
Labels: documentation, size:M, lgtm

#1602 logos section on homepage
  docs/assets/images/logos/cubeserv.svg
  docs/assets/images/logos/equinix.svg
  docs/assets/images/logos/kbc.png
  docs/assets/images/logos/snowflake.svg
  docs/assets/images/logos/tribbleai.png
  docs/overrides/home.html
  docs/stylesheets/style.css
Labels: size:S, lgtm

#1626 Don't check if Cortex providers can be deserialized for deferred feedback functions.
  src/core/trulens/core/app.py
Labels: size:S, lgtm

#1627 Ensure `make clean` does indeed clean or it will fail out.
  Makefile
  tests/e2e/test_context_variables.py
Labels: size:XS, lgtm

#1619 Create smoke test for Snowflake notebooks.
  tests/e2e/data/environment.yml
  tests/e2e/data/simple.ipynb
  tests/e2e/test_snowflake_connection.py
  tests/e2e/test_snowflake_notebooks.py
  tests/util/snowflake_test_case.py
Labels: size:L, lgtm

#1628 For snowflake dialects, when inserting a feedback result with a NULL result, first insert a -1, then update it.
  src/connectors/snowflake/trulens/connectors/snowflake/utils/server_side_evaluation_artifacts.py
  src/core/trulens/core/database/sqlalchemy.py
  tests/e2e/data/environment.yml
  tests/e2e/data/staged_packages.ipynb
  tests/e2e/test_snowflake_notebooks.py
Labels: size:L, lgtm

#1630 update link for migration page
  src/core/trulens/core/utils/deprecation.py
Labels: documentation, size:XS, lgtm

#1629 human feedback with metadata
  examples/quickstart/human_feedback.ipynb
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/schema/feedback.py
Labels: size:L, lgtm

#1632 Bump version to 1.2.5.
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M, lgtm

#1634 Move print message up to not invoke error when we can't create a tag.
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
Labels: size:XS, lgtm

#1635 Bump version to 1.2.6.
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M, lgtm

#1569 cost tracking for otel_tracing
  examples/experimental/dummy_example.ipynb
  examples/experimental/export_dummy_example.ipynb
  examples/experimental/export_llamaindex_example.ipynb
  src/core/pyproject.toml
  src/core/trulens/core/_utils/optional.py
  src/core/trulens/core/app.py
  src/core/trulens/core/experimental/__init__.py
  src/core/trulens/core/feedback/endpoint.py
  src/core/trulens/core/feedback/feedback.py
  src/core/trulens/core/instruments.py
  src/core/trulens/core/schema/base.py
  src/core/trulens/core/schema/record.py
  src/core/trulens/core/schema/select.py
  src/core/trulens/core/session.py
  src/core/trulens/core/utils/containers.py
  src/core/trulens/core/utils/imports.py
  src/core/trulens/core/utils/pace.py
  src/core/trulens/core/utils/python.py
  src/core/trulens/core/utils/requirements.txt
  src/core/trulens/experimental/otel_tracing/_feature.py
  src/core/trulens/experimental/otel_tracing/core/_utils/wrap.py
  src/core/trulens/experimental/otel_tracing/core/app.py
  src/core/trulens/experimental/otel_tracing/core/feedback/endpoint.py
  src/core/trulens/experimental/otel_tracing/core/otel.py
  src/core/trulens/experimental/otel_tracing/core/session.py
  src/core/trulens/experimental/otel_tracing/core/trace.py
  src/feedback/trulens/feedback/dummy/endpoint.py
  src/providers/bedrock/trulens/providers/bedrock/endpoint.py
  src/providers/huggingface/trulens/providers/huggingface/endpoint.py
  src/providers/huggingface/trulens/providers/huggingface/provider.py
  src/providers/litellm/trulens/providers/litellm/endpoint.py
  src/providers/openai/pyproject.toml
  src/providers/openai/trulens/providers/openai/endpoint.py
  tests/e2e/test_endpoints.py
  tests/test.py
  tests/unit/static/golden/api.trulens.3.11.yaml
Labels: size:XXL, lgtm

#1633 example: context filters with different speeds (models)
  examples/expositional/use_cases/context_filters.ipynb
Labels: documentation, size:L, lgtm

#1640 Fix docs typo about aggregate
  docs/component_guides/evaluation/feedback_aggregation.md
  docs/component_guides/evaluation/running_feedback_functions/with_app.md
  src/feedback/README.md
Labels: documentation, size:S, lgtm

#1643 Add Datec logo to homepage
  docs/assets/images/logos/datec.png
  docs/overrides/home.html
Labels: size:XS, lgtm

#1637 If the Snowflake connector supplied to us has a "pyformat" paramstyle, fail fast and give helpful advice to fix it.
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  tests/e2e/test_snowflake_connection.py
  tests/e2e/test_snowflake_notebooks.py
  tests/util/snowflake_test_case.py
Labels: size:M, lgtm

#1653 Remove all but root `poetry.lock` file.
  .gitignore
  .pre-commit-config.yaml
  Makefile
  poetry.lock
  pyproject.toml
  src/apps/langchain/poetry.lock
  src/apps/llamaindex/poetry.lock
  src/apps/nemo/poetry.lock
  src/benchmark/poetry.lock
  src/connectors/snowflake/poetry.lock
  src/core/poetry.lock
  src/dashboard/poetry.lock
  src/feedback/poetry.lock
  src/providers/bedrock/poetry.lock
  src/providers/cortex/poetry.lock
  src/providers/huggingface/poetry.lock
  src/providers/langchain/poetry.lock
  src/providers/litellm/poetry.lock
  src/providers/openai/poetry.lock
  src/trulens_eval/poetry.lock
Labels: dependencies, size:M

#1645 fix missing description
  examples/expositional/models/snowflake_cortex/cortex_finetuning_experiments.ipynb
Labels: size:XS, lgtm

#1656 change instrumentation arg `self` -> `_self`
  src/core/trulens/core/instruments.py
Labels: size:XS

#1657 Trulens 1.2.8
  .gitignore
  poetry.lock
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/pyproject.toml
  src/core/pyproject.toml
  src/dashboard/pyproject.toml
  src/feedback/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1658 Update conda build files for 1.2.8
  src/connectors/snowflake/meta.yaml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/providers/cortex/meta.yaml
Labels: dependencies, size:S, lgtm

#1661 adding jenkins file for e2e tests
  tests/Jenkinsfile
Labels: size:M

#1659 Memoize base endpoint creation for cost tracking
  src/core/trulens/core/feedback/endpoint.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: size:L

#1662 add importlib resources to conda build
  src/core/meta.yaml
Labels: dependencies, size:XS

#1650 Switch from SQL function to REST API backend for Cortex Complete - cost tracking of both feedback computations and app generation
  examples/experimental/cortex_finetuning_groundedness_ff.ipynb
  examples/experimental/snowflake_feedbacks.ipynb
  examples/expositional/frameworks/cortexchat/cortex_chat_quickstart.ipynb
  examples/expositional/models/snowflake_cortex/arctic_quickstart.ipynb
  examples/expositional/models/snowflake_cortex/cortex_finetuning_experiments.ipynb
  examples/expositional/use_cases/snowflake_auth_methods.ipynb
  src/benchmark/trulens/benchmark/benchmark_frameworks/experiments/rag_triad_baselines.ipynb
  src/benchmark/trulens/benchmark/benchmark_frameworks/tru_benchmark_experiment.py
  src/benchmark/trulens/benchmark/context_relevance_benchmark_calibration.ipynb
  src/connectors/snowflake/trulens/connectors/snowflake/utils/server_side_evaluation_artifacts.py
  src/connectors/snowflake/trulens/connectors/snowflake/utils/server_side_evaluation_stored_procedure.py
  src/core/trulens/core/app.py
  src/core/trulens/core/utils/requirements.optional.txt
  src/feedback/trulens/feedback/groundtruth.py
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/cortex/trulens/providers/cortex/endpoint.py
  src/providers/cortex/trulens/providers/cortex/provider.py
  tests/e2e/test_endpoints.py
  tests/e2e/test_snowflake_feedback_evaluation.py
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: dependencies, size:L

#1663 fix meta.yaml spacing
  src/core/meta.yaml
  src/dashboard/pyproject.toml
Labels: size:XS

#1666 Fix Cortex provider for tests.
  Makefile
  src/providers/cortex/trulens/providers/cortex/provider.py
  tests/e2e/data/staged_packages.ipynb
  tests/util/snowflake_test_case.py
Labels: size:M

#1664 relax snowflake-ml-python version
  src/providers/cortex/pyproject.toml
Labels: dependencies, size:XS

#1668 Fix encoding issues in dashboard
  src/core/trulens/core/database/sqlalchemy.py
  src/dashboard/trulens/dashboard/utils/dashboard_utils.py
Labels: size:XS
