Repository truera/trulens, pull requests merged in 2024-09, with the labels that each got.

#1436 az badge update
  README.md
Labels: documentation, size:XS, lgtm

#1434 docs nits
  docs/trulens/release_blog_1dot.md
Labels: documentation, size:S

#1437 Dark mode for Trace viewer
  src/dashboard/react_components/record_viewer/package-lock.json
  src/dashboard/react_components/record_viewer/package.json
  src/dashboard/react_components/record_viewer/src/JSONViewer/JSONViewer.tsx
  src/dashboard/react_components/record_viewer/src/Panel/Panel.tsx
  src/dashboard/react_components/record_viewer/src/RecordInfo.tsx
  src/dashboard/react_components/record_viewer/src/RecordTable/RecordTable.tsx
  src/dashboard/react_components/record_viewer/src/RecordTable/RecordTableRow.tsx
  src/dashboard/react_components/record_viewer/src/RecordTree/Details/RootDetails.tsx
  src/dashboard/react_components/record_viewer/src/RecordTree/Details/styles.ts
  src/dashboard/react_components/record_viewer/src/RecordTree/RecordTreeCell.tsx
  src/dashboard/react_components/record_viewer/src/RecordTree/RecordTreeCellRecursive.tsx
  src/dashboard/react_components/record_viewer/src/RecordViewer.tsx
  src/dashboard/react_components/record_viewer/src/StyledTooltip/StyledTooltip.tsx
  src/dashboard/react_components/record_viewer/src/Tabs/Tabs/Tabs.tsx
  src/dashboard/react_components/record_viewer/src/Tag/Tag.tsx
  src/dashboard/react_components/record_viewer/src/main.tsx
  src/dashboard/react_components/record_viewer/src/utils/ThemeProvider.tsx
  src/dashboard/react_components/record_viewer/src/utils/TrueraTheme.ts
  src/dashboard/react_components/record_viewer/src/utils/colors.ts
  src/dashboard/react_components/record_viewer/src/utils/theme.ts
  src/dashboard/trulens/dashboard/components/record_viewer/dist/assets/index-923e1c7a.js
  src/dashboard/trulens/dashboard/components/record_viewer/dist/assets/index-b321be19.js
  src/dashboard/trulens/dashboard/components/record_viewer/dist/index.html
Labels: dependencies, size:XL, lgtm

#1435 release pipeline related fixes
  .gitignore
  Makefile
  examples/experimental/async_example.ipynb
  poetry.lock
  pyproject.toml
  src/apps/langchain/trulens/apps/langchain/tru_chain.py
  src/apps/llamaindex/poetry.lock
  src/apps/llamaindex/pyproject.toml
  src/core/trulens/core/app.py
  src/core/trulens/core/database/connector/default.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/instruments.py
  src/core/trulens/core/schema/base.py
  src/core/trulens/core/schema/record.py
  src/core/trulens/core/utils/deprecation.py
  src/core/trulens/core/utils/python.py
  src/dashboard/poetry.lock
  src/providers/bedrock/poetry.lock
  src/providers/cortex/trulens/providers/cortex/endpoint.py
  src/providers/litellm/poetry.lock
  src/providers/openai/trulens/providers/openai/endpoint.py
  src/trulens_eval/poetry.lock
  tests/e2e/golden/customapp.json
  tests/e2e/golden/customapp_context_relevance.def.json
  tests/e2e/golden/customapp_context_relevance.result.json
  tests/e2e/golden/customapp_language_match.def.json
  tests/e2e/golden/customapp_language_match.result.json
  tests/e2e/golden/customapp_record.json
  tests/e2e/golden/dummy.json
  tests/e2e/test_dummy.py
  tests/e2e/test_endpoints.py
  tests/e2e/test_serial.py
  tests/e2e/test_tru_chain.py
  tests/e2e/test_tru_session.py
  tests/e2e/test_trulens_eval_notebooks.py
  tests/test.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.12.yaml
  tests/unit/static/test_api.py
  tests/unit/static/test_deprecation.py
Labels: dependencies, size:XXL, lgtm

#1438 remove debug printouts
  src/core/trulens/core/utils/python.py
Labels: size:XS, lgtm

#1439 Make styling more compatible with dark mode for feedback functions
  src/dashboard/trulens/dashboard/ux/styles.py
Labels: size:S, lgtm

#1442 Josh/center homepage image text + change app versions compared
  docs/img/trulens-get-started.png
  docs/img/trulens-get-started.svg
Labels: size:XS, lgtm

#1440 Add missing UX components to streamlit feedback component
  src/dashboard/trulens/dashboard/display.py
  src/dashboard/trulens/dashboard/pages/Evaluations.py
  src/dashboard/trulens/dashboard/streamlit.py
  src/dashboard/trulens/dashboard/ux/styles.py
Labels: size:L, lgtm

#1427 experimental flags
  POLICIES.md
  src/apps/langchain/trulens/apps/langchain/tru_chain.py
  src/core/trulens/core/database/base.py
  src/core/trulens/core/database/connector/base.py
  src/core/trulens/core/database/connector/default.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/experimental/__init__.py
  src/core/trulens/core/session.py
  src/core/trulens/core/utils/python.py
  src/core/trulens/core/utils/text.py
Labels: size:XL, lgtm

#1445 Default to use LLM to split sentences for Groundedness eval
  src/feedback/trulens/feedback/llm_provider.py
Labels: size:XS

#1448 fix trulens_eval migration link
  src/core/trulens/core/utils/deprecation.py
Labels: size:XS, lgtm

#1446 Cortex Chat Quickstart
  examples/expositional/frameworks/cortexchat/cortex_chat_quickstart.ipynb
Labels: documentation, size:L, lgtm

#1463 fix typo in Makefile
  Makefile
Labels: size:XS

#1458 Add progress bars to data migration scripts
  src/core/trulens/core/database/migrations/versions/6_populate_app_name_and_version_data.py
  src/core/trulens/core/database/migrations/versions/8_update_records_app_id.py
  src/core/trulens/core/database/migrations/versions/9_update_app_json.py
  src/core/trulens/core/session.py
Labels: size:S, lgtm

#1447 cortex instrumentation fixes
  .gitignore
  poetry.lock
  pyproject.toml
  src/apps/langchain/poetry.lock
  src/apps/llamaindex/poetry.lock
  src/apps/nemo/poetry.lock
  src/benchmark/poetry.lock
  src/connectors/snowflake/poetry.lock
  src/connectors/snowflake/pyproject.toml
  src/core/poetry.lock
  src/core/pyproject.toml
  src/core/trulens/core/utils/requirements.optional.txt
  src/dashboard/poetry.lock
  src/dashboard/pyproject.toml
  src/dashboard/trulens/dashboard/Leaderboard.py
  src/dashboard/trulens/dashboard/constants.py
  src/dashboard/trulens/dashboard/pages/Compare.py
  src/dashboard/trulens/dashboard/pages/Records.py
  src/dashboard/trulens/dashboard/utils/dashboard_utils.py
  src/dashboard/trulens/dashboard/ux/styles.py
  src/feedback/poetry.lock
  src/providers/bedrock/poetry.lock
  src/providers/cortex/poetry.lock
  src/providers/huggingface/poetry.lock
  src/providers/langchain/poetry.lock
  src/providers/litellm/poetry.lock
  src/providers/openai/poetry.lock
  src/providers/openai/pyproject.toml
  src/trulens_eval/poetry.lock
Labels: dependencies, size:M, lgtm

#1461 json decode error workaround
  src/providers/cortex/trulens/providers/cortex/endpoint.py
Labels: size:S, lgtm

#1459 Support having a `Langchain` provider with a `BaseLLM` and not just `BaseChatModel`.
  src/providers/langchain/trulens/providers/langchain/provider.py
Labels: size:S, lgtm

#1468 Conda Meta Hash fix
  src/core/meta.yaml
  src/feedback/meta.yaml
  src/providers/cortex/meta.yaml
Labels: size:XS, lgtm

#1471 fix optionals in core
  src/core/poetry.lock
  src/core/pyproject.toml
Labels: dependencies, size:XS, lgtm

#1457 fix optional import message
  src/core/trulens/core/_utils/optional.py
  src/core/trulens/core/app.py
  src/core/trulens/core/session.py
  src/trulens_eval/trulens_eval/__init__.py
  src/trulens_eval/trulens_eval/utils/imports.py
Labels: size:M, lgtm

#1473 Docs Changes
  POLICIES.md
  RELEASES.md
  docs/gen_ref_pages.py
  docs/stylesheets/extra.css
  docs/trulens/contributing/release_history.md
  docs/trulens/getting_started/index.md
  mkdocs.yml
  poetry.lock
  pyproject.toml
  src/apps/llamaindex/trulens/apps/llamaindex/guardrails.py
  src/benchmark/trulens/benchmark/benchmark_frameworks/tru_benchmark_experiment.py
  src/benchmark/trulens/benchmark/generate/generate_test_set.py
  src/core/trulens/apps/custom.py
  src/core/trulens/core/app.py
  src/core/trulens/core/feedback/provider.py
  src/core/trulens/core/guardrails/base.py
  src/core/trulens/core/utils/deprecation.py
  src/core/trulens/core/utils/keys.py
  src/core/trulens/core/utils/serial.py
  src/dashboard/trulens/dashboard/components/record_viewer/__init__.py
  src/dashboard/trulens/dashboard/display.py
  src/dashboard/trulens/dashboard/run.py
  src/dashboard/trulens/dashboard/streamlit.py
  src/dashboard/trulens/dashboard/utils/__init__.py
  src/dashboard/trulens/dashboard/utils/records_utils.py
  src/feedback/trulens/feedback/embeddings.py
  src/feedback/trulens/feedback/groundtruth.py
  src/feedback/trulens/feedback/llm_provider.py
  src/feedback/trulens/feedback/v2/feedback.py
  src/providers/bedrock/trulens/providers/bedrock/provider.py
  src/providers/huggingface/trulens/providers/huggingface/provider.py
  src/providers/langchain/trulens/providers/langchain/provider.py
  src/providers/litellm/trulens/providers/litellm/provider.py
  src/providers/openai/trulens/providers/openai/provider.py
Labels: documentation, dependencies, size:L, lgtm

#1449 Allow for DBs that already have tables (at least if they're not sqlite databases).
  src/core/trulens/core/database/utils.py
  tests/e2e/test_snowflake_connection.py
  tests/e2e/test_snowflake_feedback_evaluation.py
  tests/util/snowflake_test_case.py
Labels: size:M, lgtm

#1478 Update threading.py, fix context loss in multi-threading
  src/core/trulens/core/utils/threading.py
Labels: size:XS, lgtm

#1479 Bumping conda meta to build a conda package 1.0.2
  src/core/meta.yaml
  src/feedback/meta.yaml
  src/providers/cortex/meta.yaml
Labels: size:S

#1476 Move requests/Endpoint.post to huggingface provider
  Makefile
  src/core/trulens/core/feedback/endpoint.py
  src/core/trulens/core/utils/requirements.optional.txt
  src/providers/huggingface/trulens/providers/huggingface/endpoint.py
  src/trulens_eval/trulens_eval/feedback/provider/endpoint/base.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.12.yaml
Labels: size:L, lgtm

#1460 updates to cortex chat quickstart
  examples/expositional/frameworks/cortexchat/cortex_chat_quickstart.ipynb
Labels: size:M, lgtm

#1482 relax minor package version constraints
  poetry.lock
  src/apps/langchain/poetry.lock
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/poetry.lock
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/poetry.lock
  src/apps/nemo/pyproject.toml
  src/benchmark/poetry.lock
  src/connectors/snowflake/poetry.lock
  src/core/poetry.lock
  src/dashboard/poetry.lock
  src/feedback/poetry.lock
  src/providers/bedrock/poetry.lock
  src/providers/cortex/poetry.lock
  src/providers/huggingface/poetry.lock
  src/providers/langchain/poetry.lock
  src/providers/langchain/pyproject.toml
  src/providers/litellm/poetry.lock
  src/providers/openai/poetry.lock
  src/trulens_eval/poetry.lock
Labels: dependencies, size:S, lgtm

#1483 init_server_side=False by default
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
Labels: size:XS, lgtm

#1489 endpoint kwargs
  src/core/trulens/core/utils/python.py
  src/feedback/trulens/feedback/llm_provider.py
  src/feedback/trulens/feedback/v2/feedback.py
  tests/unit/static/golden/api.trulens.3.11.yaml
Labels: size:XL, lgtm

#1496 Add mistral-large2 to the list of supported models in Cortex feedback provider
  src/providers/cortex/trulens/providers/cortex/config/cortex_model_costs.json
Labels: size:XS, lgtm

#1470 memory, threads, and async leakage testing
  src/core/trulens/core/utils/serial.py
  src/core/trulens/core/utils/text.py
  tests/test.py
Labels: size:L, lgtm

#1491 leaderboard list view fix
  src/dashboard/trulens/dashboard/Leaderboard.py
  src/dashboard/trulens/dashboard/pages/Records.py
Labels: size:M, lgtm

#1490 small perf improvements
  src/core/trulens/core/database/connector/base.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/utils/python.py
  tests/unit/static/golden/api.trulens.3.11.yaml
Labels: size:M, lgtm

#1497 website analytics and dark mode fixes
  POLICIES.md
  docs/assets/images/Honest_Harmless_Helpful_Evals.jpg
  docs/assets/images/Honest_Harmless_Helpful_Evals.png
  docs/assets/images/Neural_Network_Explainability.png
  docs/assets/images/RAG_Triad.jpg
  docs/assets/images/RAG_Triad.png
  docs/assets/images/Range_of_Feedback_Functions.png
  docs/assets/images/trulens_1_release_graphic_modular.png
  docs/overrides/home.html
  docs/stylesheets/extra.css
  docs/trulens/getting_started/core_concepts/honest_harmless_helpful_evals.md
  docs/trulens/getting_started/core_concepts/rag_triad.md
  docs/trulens/release_blog_1dot.md
  docs/trulens/tracking/instrumentation/index.md
  mkdocs.yml
  src/core/trulens/core/app.py
  src/core/trulens/core/experimental/__init__.py
  src/core/trulens/core/utils/python.py
Labels: documentation, size:L, lgtm

#1474 add_dataframe method + quickstart
  docs/trulens/getting_started/quickstarts/add_dataframe_quickstart.ipynb
  docs/trulens/getting_started/quickstarts/custom_stream.ipynb
  examples/quickstart/add_dataframe_quickstart.ipynb
  examples/quickstart/custom_stream.ipynb
  src/core/trulens/apps/virtual.py
Labels: documentation, size:L, lgtm

#1504 slight downgrade of minimum dep requirements
  src/dashboard/poetry.lock
  src/dashboard/pyproject.toml
Labels: dependencies, size:XS, lgtm

#1494 Cleanup main pyproject and relax minor versions
  .azure_pipelines/templates/run-precommits.yaml
  Makefile
  poetry.lock
  pyproject.toml
  src/apps/langchain/poetry.lock
  src/apps/llamaindex/poetry.lock
  src/apps/nemo/poetry.lock
  src/benchmark/poetry.lock
  src/connectors/snowflake/poetry.lock
  src/connectors/snowflake/pyproject.toml
  src/core/poetry.lock
  src/core/pyproject.toml
  src/dashboard/poetry.lock
  src/dashboard/pyproject.toml
  src/feedback/poetry.lock
  src/providers/bedrock/poetry.lock
  src/providers/cortex/poetry.lock
  src/providers/huggingface/poetry.lock
  src/providers/langchain/poetry.lock
  src/providers/litellm/poetry.lock
  src/providers/openai/poetry.lock
  src/trulens_eval/poetry.lock
Labels: dependencies, size:M, lgtm

#1453 Cortex Fine-tuning experiments notebook
  examples/expositional/models/snowflake_cortex/cortex_finetuning_experiments.ipynb
  src/providers/cortex/trulens/providers/cortex/provider.py
Labels: documentation, size:L, lgtm

#1510 Revert default sentence splitter for groundedness back to use punkt
  src/feedback/trulens/feedback/llm_provider.py
Labels: size:XS, lgtm

#1512 Get query planning nb working
  examples/expositional/frameworks/llama_index/llama_index_queryplanning.ipynb
Labels: dependencies, size:XS, lgtm

#1514 query planning nb updates
  examples/expositional/frameworks/llama_index/llama_index_queryplanning.ipynb
Labels: size:L, lgtm

#1517 Fix splitting key points issue: _assess_key_point_inclusion()
  src/feedback/trulens/feedback/llm_provider.py
Labels: size:XS, lgtm

#1518 Dashboard fixes
  src/dashboard/trulens/dashboard/display.py
  src/dashboard/trulens/dashboard/pages/Compare.py
  src/dashboard/trulens/dashboard/utils/records_utils.py
  src/feedback/trulens/feedback/llm_provider.py
Labels: size:M, lgtm

#1519 Fix splitting key_points issue: generalize the solution for splitting key points in _assess_key_point_inclusion()
  src/feedback/trulens/feedback/llm_provider.py
Labels: size:XS, lgtm

#1464 example for server side feedback + batching
  examples/experimental/snowflake_feedbacks.ipynb
Labels: size:L, lgtm

#1522 Fix leaderboard showing inconsistent latency readings
  src/core/trulens/core/database/connector/base.py
  src/core/trulens/core/database/sqlalchemy.py
Labels: size:S, lgtm

#1515 small record ingest formatting fix
  src/core/trulens/core/database/sqlalchemy.py
Labels: size:XS, lgtm
