Repository truera/trulens, pull requests merged in 2024-07, with the labels that each got.

#1273 fix typo
  docs/trulens_eval/intro.md
Labels: documentation, size:XS, lgtm

#1267 timeouts for wait_for_feedback_results
  trulens_eval/examples/experimental/dummy_example.ipynb
  trulens_eval/trulens_eval/app.py
  trulens_eval/trulens_eval/feedback/provider/cortex.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/cortex.py
  trulens_eval/trulens_eval/requirements.optional.txt
  trulens_eval/trulens_eval/schema/record.py
  trulens_eval/trulens_eval/utils/containers.py
Labels: size:L, lgtm

#1276 fix LlamaIndex streaming response import
  trulens_eval/trulens_eval/tru_llama.py
Labels: size:XS, lgtm

#1280 Allow unused port
  trulens_eval/trulens_eval/tru.py
Labels: size:XS, lgtm

#1281 Reflect Snowflake SQLAlchemy Release in "Connect to Snowflake" Docs
  docs/trulens_eval/tracking/logging/where_to_log/log_in_snowflake.md
  mkdocs.yml
Labels: documentation, size:M, lgtm

#1283 Stop using `all_tools.ipynb`/`all_tools.py`.
  .azure_pipelines/ci-eval.yaml
  .github/workflows/combine_nb_to_docs_testing.sh
  .github/workflows/github-actions-generated-files-from-docs.yml
  .gitignore
  docs/trulens_eval/all_tools.ipynb
  docs/trulens_eval/clear_trulens_module.ipynb
  docs/trulens_eval/evaluation/feedback_implementations/custom_feedback_functions.ipynb
  trulens_eval/examples/expositional/vector-dbs/faiss/langchain_faiss_example.ipynb
  trulens_eval/examples/quickstart/prototype_evals.ipynb
  trulens_eval/generated_files/README.md
  trulens_eval/generated_files/all_tools.py
  trulens_eval/tests/docs_notebooks/notebooks_to_test/all_tools.ipynb
  trulens_eval/tests/docs_notebooks/notebooks_to_test/logging.ipynb
  trulens_eval/tests/docs_notebooks/test_notebooks.py
Labels: size:XXL, lgtm

#1291 version bump 0.33.0
  trulens_eval/RELEASES.md
  trulens_eval/trulens_eval/__init__.py
Labels: documentation, size:S, lgtm

#1287 organize requirements files
  .azure_pipelines/ci-eval-pr.yaml
  .azure_pipelines/ci-eval.yaml
  Makefile
  docs/pull_request_template.md
  docs/trulens_eval/contributing/standards.md
  requirements.dev.txt
  requirements.docs.txt
  requirements.test.txt
Labels: dependencies, size:M, lgtm

#1294 Remove newsletter button from trulens.org
  docs/overrides/home.html
Labels: documentation, size:XS, lgtm

#1299 Deprecate qs relevance in favor of context relevance
  .gitignore
  docs/trulens_eval/evaluation/feedback_selectors/selecting_components.md
  docs/trulens_eval/evaluation/running_feedback_functions/existing_data.md
  docs/trulens_eval/evaluation/running_feedback_functions/with_app.md
  docs/trulens_eval/tracking/instrumentation/nemo.ipynb
  trulens_eval/examples/experimental/generate_test_set.ipynb
  trulens_eval/examples/experimental/random_evaluation.ipynb
  trulens_eval/examples/experimental/virtual_example.ipynb
  trulens_eval/examples/expositional/end2end_apps/trubot/App_TruBot.py
  trulens_eval/examples/expositional/end2end_apps/trubot/trubot.py
  trulens_eval/examples/expositional/end2end_apps/trubot/trubot_example.ipynb
  trulens_eval/examples/expositional/end2end_apps/trubot/trubot_example_no_hugs.ipynb
  trulens_eval/examples/expositional/frameworks/canopy/canopy_quickstart.ipynb
  trulens_eval/examples/expositional/frameworks/langchain/langchain_ensemble_retriever.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_retrievalquality.ipynb
  trulens_eval/examples/expositional/frameworks/nemoguardrails/nemoguardrails_custom_action_with_feedback_example.ipynb
  trulens_eval/examples/expositional/frameworks/nemoguardrails/nemoguardrails_feedback_action_example.ipynb
  trulens_eval/examples/expositional/models/azure_openai_langchain.ipynb
  trulens_eval/examples/expositional/models/azure_openai_llama_index.ipynb
  trulens_eval/examples/expositional/models/gemini_multi_modal.ipynb
  trulens_eval/examples/expositional/vector-dbs/faiss/langchain_faiss_example.ipynb
  trulens_eval/examples/expositional/vector-dbs/milvus/milvus_evals_build_better_rags.ipynb
  trulens_eval/examples/expositional/vector-dbs/milvus/milvus_simple.ipynb
  trulens_eval/examples/expositional/vector-dbs/pinecone/pinecone_evals_build_better_rags.ipynb
  trulens_eval/examples/feedbacks.ipynb
  trulens_eval/tests/e2e/test_providers.py
  trulens_eval/trulens_eval/Example_TruBot.py
  trulens_eval/trulens_eval/feedback/README.md
  trulens_eval/trulens_eval/feedback/feedback.py
  trulens_eval/trulens_eval/feedback/prompts.py
  trulens_eval/trulens_eval/feedback/provider/base.py
  trulens_eval/trulens_eval/feedback/v2/feedback.py
  trulens_eval/trulens_eval/feedback/v2/provider/base.py
  trulens_eval/trulens_eval/tests/context_relevance_benchmark_calibration.ipynb
  trulens_eval/trulens_eval/tests/context_relevance_benchmark_small.ipynb
  trulens_eval/trulens_eval/tru_basic_app.py
  trulens_eval/trulens_eval/tru_llama.py
  trulens_eval/trulens_eval/tru_virtual.py
Labels: size:L, lgtm

#1297 SDK: Group leaderboard results by metadata
  trulens_eval/trulens_eval/tru.py
Labels: documentation, size:S, lgtm

#1292 Use .ONESHELL in Makefiles .
  Makefile
  trulens_eval/Makefile
Labels: size:L, lgtm

#1302 Add docs for running dashboard, streamlit components
  docs/trulens_eval/getting_started/dashboard/index.md
  mkdocs.yml
Labels: documentation, size:L, lgtm

#1298 Improve handling of abstention for groundedness
  trulens_eval/trulens_eval/feedback/groundtruth.py
  trulens_eval/trulens_eval/feedback/prompts.py
  trulens_eval/trulens_eval/feedback/provider/base.py
  trulens_eval/trulens_eval/feedback/v2/feedback.py
  trulens_eval/trulens_eval/tests/groundedness_benchmark.ipynb
  trulens_eval/trulens_eval/tests/groundedness_benchmark_abstentions.ipynb
  trulens_eval/trulens_eval/tests/groundedness_benchmark_snowflake_arctic.ipynb
Labels: documentation, size:L, lgtm

#1304 docs: update README.md
  README.md
Labels: documentation, size:XS, lgtm

#1311 abstention scores 0 for answer relevance
  trulens_eval/trulens_eval/feedback/v2/feedback.py
Labels: size:XS, lgtm

#1312 Update openai provider model default to gpt-4o-mini
  trulens_eval/trulens_eval/feedback/provider/openai.py
Labels: size:XS, lgtm
