Repository truera/trulens, pull requests merged in 2024-02, with the labels that each got.

#860 streamlit experimental query params -> query params
  trulens_eval/trulens_eval/pages/Evaluations.py
Labels: size:XS, lgtm

#879 deferred progress status
  trulens_eval/examples/experimental/dummy_example.ipynb
  trulens_eval/examples/expositional/end2end_apps/custom_app/custom_app.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/base.py
  trulens_eval/trulens_eval/feedback/provider/hugs.py
  trulens_eval/trulens_eval/tru.py
  trulens_eval/trulens_eval/utils/imports.py
Labels: size:M, lgtm

#878 Allow different schemas for Bedrock provider calls
  trulens_eval/trulens_eval/feedback/provider/bedrock.py
Labels: size:M, lgtm

#881 make feedback_results backwards compatible
  trulens_eval/trulens_eval/app.py
  trulens_eval/trulens_eval/schema.py
  trulens_eval/trulens_eval/tru_virtual.py
Labels: size:M, lgtm

#883 fix st.query_params
  trulens_eval/trulens_eval/pages/Evaluations.py
  trulens_eval/trulens_eval/requirements.txt
Labels: size:XS, lgtm

#882 TruLens-Eval v0.22.1
  trulens_eval/examples/quickstart/groundtruth_evals.ipynb
  trulens_eval/examples/quickstart/human_feedback.ipynb
  trulens_eval/examples/quickstart/langchain_quickstart.ipynb
  trulens_eval/examples/quickstart/llama_index_quickstart.ipynb
  trulens_eval/examples/quickstart/prototype_evals.ipynb
  trulens_eval/examples/quickstart/py_script_quickstarts/all_tools.py
  trulens_eval/examples/quickstart/py_script_quickstarts/langchain_quickstart.py
  trulens_eval/examples/quickstart/py_script_quickstarts/llama_index_quickstart.py
  trulens_eval/examples/quickstart/py_script_quickstarts/quickstart.py
  trulens_eval/examples/quickstart/py_script_quickstarts/text2text_quickstart.py
  trulens_eval/examples/quickstart/quickstart.ipynb
  trulens_eval/examples/quickstart/text2text_quickstart.ipynb
  trulens_eval/trulens_eval/__init__.py
  trulens_eval/trulens_eval/tru.py
Labels: size:XXL, lgtm

#888 Metadata error fix
  trulens_eval/trulens_eval/pages/Evaluations.py
Labels: size:XS, lgtm

#884 Ensure agreement prompt outputs integer score only
  trulens_eval/trulens_eval/feedback/prompts.py
Labels: size:XS, lgtm

#893 pin llama-index temp
  trulens_eval/trulens_eval/requirements.optional.txt
Labels: size:XS, lgtm

#892 fix bug in optional imports
  trulens_eval/TECHDEBT.md
  trulens_eval/trulens_eval/utils/imports.py
Labels: size:S, lgtm

#887 Enable bedrock provider models
  trulens_eval/trulens_eval/feedback/provider/bedrock.py
Labels: size:S, lgtm

#894 TruLens-Eval 0.22.2
  trulens_eval/examples/quickstart/groundtruth_evals.ipynb
  trulens_eval/examples/quickstart/human_feedback.ipynb
  trulens_eval/examples/quickstart/langchain_quickstart.ipynb
  trulens_eval/examples/quickstart/llama_index_quickstart.ipynb
  trulens_eval/examples/quickstart/prototype_evals.ipynb
  trulens_eval/examples/quickstart/py_script_quickstarts/all_tools.py
  trulens_eval/examples/quickstart/py_script_quickstarts/langchain_quickstart.py
  trulens_eval/examples/quickstart/py_script_quickstarts/llama_index_quickstart.py
  trulens_eval/examples/quickstart/py_script_quickstarts/quickstart.py
  trulens_eval/examples/quickstart/py_script_quickstarts/text2text_quickstart.py
  trulens_eval/examples/quickstart/quickstart.ipynb
  trulens_eval/examples/quickstart/text2text_quickstart.ipynb
  trulens_eval/trulens_eval/__init__.py
Labels: size:L, lgtm

#904 fix for in-memory sqlite params
  trulens_eval/trulens_eval/database/sqlalchemy_db.py
  trulens_eval/trulens_eval/database/utils.py
Labels: size:M, lgtm

#900 Fix use case colab links
  trulens_eval/examples/expositional/use_cases/language_verification.ipynb
  trulens_eval/examples/expositional/use_cases/moderation.ipynb
  trulens_eval/examples/expositional/use_cases/pii_detection.ipynb
  trulens_eval/examples/expositional/use_cases/summarization_eval.ipynb
Labels: size:XS, lgtm

#903 few site-related fixes to recently merged pr
  Makefile
  docs/nn-explainability.html
  docs/overrides/home.html
  trulens_eval/trulens_eval/instruments.py
Labels: size:S, lgtm

#901 comprehensiveness updates
  trulens_eval/trulens_eval/feedback/prompts.py
  trulens_eval/trulens_eval/feedback/provider/base.py
Labels: size:M, lgtm

#905 fix forward refs with model_rebuild
  trulens_eval/TECHDEBT.md
  trulens_eval/trulens_eval/feedback/__init__.py
  trulens_eval/trulens_eval/feedback/feedback.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/base.py
  trulens_eval/trulens_eval/schema.py
  trulens_eval/trulens_eval/tru_virtual.py
  trulens_eval/trulens_eval/utils/pyschema.py
  trulens_eval/trulens_eval/utils/serial.py
Labels: size:M, lgtm

#873 Deeper Instrumentation for Hybrid Retrievers + examples
  trulens_eval/examples/expositional/frameworks/langchain/langchain_ensemble_retriever.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_hybrid_retriever.ipynb
  trulens_eval/trulens_eval/instruments.py
  trulens_eval/trulens_eval/requirements.optional.txt
  trulens_eval/trulens_eval/tru_llama.py
Labels: size:XL, lgtm

#907 various documentation fixes
  docs/trulens_eval/api/endpoint.md
  docs/trulens_eval/api/endpoint/base.md
  docs/trulens_eval/api/endpoint/openai.md
  docs/trulens_eval/api/provider/llmprovider.md
  docs/trulens_eval/api/utils/python.md
  mkdocs.yml
  trulens_eval/TECHDEBT.md
  trulens_eval/trulens_eval/feedback/groundedness.py
  trulens_eval/trulens_eval/feedback/provider/base.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/base.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/openai.py
  trulens_eval/trulens_eval/feedback/provider/hugs.py
  trulens_eval/trulens_eval/feedback/provider/openai.py
  trulens_eval/trulens_eval/requirements.optional.txt
  trulens_eval/trulens_eval/tru.py
  trulens_eval/trulens_eval/tru_basic_app.py
  trulens_eval/trulens_eval/tru_chain.py
  trulens_eval/trulens_eval/tru_custom_app.py
  trulens_eval/trulens_eval/tru_llama.py
  trulens_eval/trulens_eval/tru_virtual.py
  trulens_eval/trulens_eval/utils/asynchro.py
  trulens_eval/trulens_eval/utils/generated.py
Labels: size:XL, lgtm

#908 Releases/rc trulens eval 0.23.0
  trulens_eval/examples/expositional/frameworks/langchain/langchain_ensemble_retriever.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_hybrid_retriever.ipynb
  trulens_eval/examples/quickstart/groundtruth_evals.ipynb
  trulens_eval/examples/quickstart/human_feedback.ipynb
  trulens_eval/examples/quickstart/langchain_quickstart.ipynb
  trulens_eval/examples/quickstart/llama_index_quickstart.ipynb
  trulens_eval/examples/quickstart/prototype_evals.ipynb
  trulens_eval/examples/quickstart/py_script_quickstarts/all_tools.py
  trulens_eval/examples/quickstart/py_script_quickstarts/langchain_quickstart.py
  trulens_eval/examples/quickstart/py_script_quickstarts/llama_index_quickstart.py
  trulens_eval/examples/quickstart/py_script_quickstarts/quickstart.py
  trulens_eval/examples/quickstart/py_script_quickstarts/text2text_quickstart.py
  trulens_eval/examples/quickstart/quickstart.ipynb
  trulens_eval/examples/quickstart/text2text_quickstart.ipynb
  trulens_eval/trulens_eval/__init__.py
Labels: size:L, lgtm

#917 check packages on init
  trulens_eval/trulens_eval/__init__.py
  trulens_eval/trulens_eval/tru.py
  trulens_eval/trulens_eval/utils/imports.py
Labels: size:L, lgtm

#919 Increase provider test coverage to Huggingface feedback provider
  trulens_eval/tests/integration/test_providers.py
Labels: size:L, lgtm

#891 upgrade Llama-Index integration to 0.10
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_agents.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_async.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_complex_evals.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_groundtruth.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_hybrid_retriever.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_multimodal.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_queryplanning.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_retrievalquality.ipynb
  trulens_eval/examples/expositional/models/azure_openai.ipynb
  trulens_eval/examples/expositional/use_cases/iterate_on_rag/1_rag_prototype.ipynb
  trulens_eval/examples/expositional/use_cases/iterate_on_rag/2_honest_rag.ipynb
  trulens_eval/examples/expositional/use_cases/iterate_on_rag/3_harmless_eval.ipynb
  trulens_eval/examples/expositional/use_cases/iterate_on_rag/4_harmless_rag.ipynb
  trulens_eval/examples/expositional/use_cases/iterate_on_rag/5_helpful_eval.ipynb
  trulens_eval/examples/expositional/vector-dbs/pinecone/pinecone_quickstart.ipynb
  trulens_eval/examples/quickstart/llama_index_quickstart.ipynb
  trulens_eval/tests/integration/test_tru.py
  trulens_eval/tests/integration/test_tru_llama.py
  trulens_eval/trulens_eval/feedback/v2/feedback.py
  trulens_eval/trulens_eval/requirements.optional.txt
  trulens_eval/trulens_eval/tru_llama.py
Labels: size:XL, lgtm

#923 Update issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size:M, lgtm

#918 async handling adjustments
  .azure_pipelines/ci-eval.yaml
  docs/trulens_eval/api/instruments.md
  docs/trulens_eval/api/utils/json.md
  docs/trulens_eval/llama_index_instrumentation.ipynb
  format.sh
  mkdocs.yml
  trulens_eval/Makefile
  trulens_eval/examples/experimental/appui_example.ipynb
  trulens_eval/examples/experimental/dashboard_appui.ipynb
  trulens_eval/examples/experimental/db_populate.ipynb
  trulens_eval/examples/experimental/dev_notebook.ipynb
  trulens_eval/examples/experimental/streamlit_appui_example.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_complex_evals.ipynb
  trulens_eval/examples/expositional/models/gemini_multi_modal.ipynb
  trulens_eval/tests/e2e/test_endpoints.py
  trulens_eval/tests/e2e/test_providers.py
  trulens_eval/tests/e2e/test_tru.py
  trulens_eval/tests/e2e/test_tru_chain.py
  trulens_eval/tests/e2e/test_tru_llama.py
  trulens_eval/trulens_eval/__init__.py
  trulens_eval/trulens_eval/app.py
  trulens_eval/trulens_eval/feedback/embeddings.py
  trulens_eval/trulens_eval/feedback/feedback.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/base.py
  trulens_eval/trulens_eval/instruments.py
  trulens_eval/trulens_eval/requirements.optional.txt
  trulens_eval/trulens_eval/requirements.txt
  trulens_eval/trulens_eval/tru_chain.py
  trulens_eval/trulens_eval/tru_custom_app.py
  trulens_eval/trulens_eval/utils/asynchro.py
  trulens_eval/trulens_eval/utils/containers.py
  trulens_eval/trulens_eval/utils/json.py
  trulens_eval/trulens_eval/utils/pyschema.py
  trulens_eval/trulens_eval/utils/python.py
  trulens_eval/trulens_eval/utils/serial.py
Labels: size:XXL, lgtm

#931 update instrumentation notebooks and related nits
  docs/trulens_eval/langchain_instrumentation.ipynb
  docs/trulens_eval/llama_index_instrumentation.ipynb
  trulens_eval/trulens_eval/app.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/base.py
  trulens_eval/trulens_eval/tru_chain.py
  trulens_eval/trulens_eval/tru_llama.py
Labels: size:L, lgtm

#927 TruLens-Eval 0.24.0
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_hybrid_retriever.ipynb
  trulens_eval/examples/quickstart/groundtruth_evals.ipynb
  trulens_eval/examples/quickstart/human_feedback.ipynb
  trulens_eval/examples/quickstart/langchain_quickstart.ipynb
  trulens_eval/examples/quickstart/llama_index_quickstart.ipynb
  trulens_eval/examples/quickstart/prototype_evals.ipynb
  trulens_eval/examples/quickstart/py_script_quickstarts/all_tools.py
  trulens_eval/examples/quickstart/py_script_quickstarts/langchain_quickstart.py
  trulens_eval/examples/quickstart/py_script_quickstarts/llama_index_quickstart.py
  trulens_eval/examples/quickstart/py_script_quickstarts/quickstart.py
  trulens_eval/examples/quickstart/py_script_quickstarts/text2text_quickstart.py
  trulens_eval/examples/quickstart/quickstart.ipynb
  trulens_eval/examples/quickstart/text2text_quickstart.ipynb
  trulens_eval/trulens_eval/__init__.py
  trulens_eval/trulens_eval/version_bump.sh
Labels: size:XXL, lgtm

#926 Update selecting_components.md
  docs/trulens_eval/selecting_components.md
Labels: size:XS, lgtm

#933 bump patchlevel
  trulens_eval/trulens_eval/__init__.py
Labels: size:XS, lgtm

#934 makefile targets for release process
  Makefile
  trulens_eval/Makefile
Labels: size:S, lgtm

#938 Better selection of main input/output
  trulens_eval/trulens_eval/app.py
Labels: size:L, lgtm
