Repository truera/trulens, pull requests merged in 2024-06, with the labels that each got.

#1173 Very minor fix of print statement
  trulens_eval/trulens_eval/database/sqlalchemy.py
Labels: size:XS, lgtm

#1169 Fix sidebar logo formatting
  trulens_eval/trulens_eval/ux/page_config.py
Labels: size:XS, lgtm

#1180 Parallelize groundedness LLM calls for speedup
  trulens_eval/trulens_eval/feedback/provider/base.py
Labels: size:M, lgtm

#1181 fix readme
  README.md
Labels: size:XS

#1178 added option to make deferred evaluation quieter
  trulens_eval/trulens_eval/feedback/provider/base.py
  trulens_eval/trulens_eval/feedback/provider/hugs.py
  trulens_eval/trulens_eval/tru.py
Labels: size:S, lgtm

#1156 ❄️ Snowflake Arctic quickstart
  trulens_eval/examples/expositional/models/arctic_quickstart.ipynb
Labels: size:L, lgtm

#1187 feat: support for langchain >=0.2.x retrievers
  trulens_eval/trulens_eval/tru_chain.py
Labels: dependencies, size:XS, lgtm

#1176 [bugfix] prevent stack overflow in jsonify
  trulens_eval/trulens_eval/utils/json.py
Labels: size:L, lgtm

#1191 0.31.0 release
  trulens_eval/trulens_eval/__init__.py
Labels: size:XS

#1185 Benchmarking Snowflake arctic-instruct feedback function of groundedness
  trulens_eval/trulens_eval/tests/groundedness_benchmark_snowflake_arctic.ipynb
Labels: size:L, lgtm

#1190 Evaluation Benchmarks Page
  docs/javascript/tablesort.js
  docs/trulens_eval/evaluation/feedback_evaluations/answer_relevance_benchmark_small.ipynb
  docs/trulens_eval/evaluation/feedback_evaluations/comprehensiveness_benchmark.ipynb
  docs/trulens_eval/evaluation/feedback_evaluations/context_relevance_benchmark.ipynb
  docs/trulens_eval/evaluation/feedback_evaluations/context_relevance_benchmark_small.ipynb
  docs/trulens_eval/evaluation/feedback_evaluations/groundedness_benchmark.ipynb
  docs/trulens_eval/evaluation/feedback_evaluations/index.md
  docs/trulens_eval/evaluation_benchmarks/answer_relevance_benchmark_small.ipynb
  docs/trulens_eval/evaluation_benchmarks/comprehensiveness_benchmark.ipynb
  docs/trulens_eval/evaluation_benchmarks/context_relevance_benchmark.ipynb
  docs/trulens_eval/evaluation_benchmarks/context_relevance_benchmark_calibration.ipynb
  docs/trulens_eval/evaluation_benchmarks/context_relevance_benchmark_small.ipynb
  docs/trulens_eval/evaluation_benchmarks/groundedness_benchmark.ipynb
  docs/trulens_eval/evaluation_benchmarks/index.md
  mkdocs.yml
Labels: documentation, size:L, lgtm

#1199 fix links for eval benchmark code
  mkdocs.yml
Labels: size:S

#1194 improve langchain prompting using native messages
  trulens_eval/trulens_eval/feedback/provider/langchain.py
Labels: size:S, lgtm

#1193 fix groundedness with no supporting evidence
  trulens_eval/trulens_eval/feedback/provider/base.py
Labels: size:XS

#1204 Add in SPCS scripts and docker files.
  trulens_eval/examples/snowflake_demo/Dockerfile
  trulens_eval/examples/snowflake_demo/feedback.py
  trulens_eval/examples/snowflake_demo/requirements.txt
  trulens_eval/examples/snowflake_demo/run.sh
  trulens_eval/examples/snowflake_demo/spcs/docker_cmds.sh
  trulens_eval/examples/snowflake_demo/spcs/set_up.sql
  trulens_eval/examples/snowflake_demo/spcs/set_up_secrets.sql
  trulens_eval/examples/snowflake_demo/spcs/start_service.sql
Labels: size:L, lgtm

#1203 (feat): [Demo] Adding streaming feedback functions in streamlit chat demo
  trulens_eval/examples/snowflake_demo/app.py
  trulens_eval/examples/snowflake_demo/common_ui.py
  trulens_eval/examples/snowflake_demo/llm.py
  trulens_eval/examples/snowflake_demo/schema.py
Labels: size:L, lgtm

#1206 Testing
  testing
Labels: size:XS, lgtm

#1200 SkipEval exception
  Makefile
  docs/docs_requirements.txt
  docs/trulens_eval/api/feedback.md
  docs/trulens_eval/contributing/design.md
  docs/trulens_eval/contributing/techdebt.md
  docs/trulens_eval/evaluation/feedback_providers/index.md
  docs/trulens_eval/evaluation_benchmarks/index.md
  trulens_eval/Makefile
  trulens_eval/tests/unit/feedbacks.py
  trulens_eval/tests/unit/test_feedback.py
  trulens_eval/trulens_eval/feedback/feedback.py
  trulens_eval/trulens_eval/feedback/provider/hugs.py
Labels: size:L, lgtm

#1211 Remove context relevance benchmark from page
  docs/trulens_eval/evaluation_benchmarks/index.md
Labels: documentation, size:M

#1212 Enable formatting during PR build. Also format code that wasn't formatted.
  .azure_pipelines/ci-eval-pr.yaml
  trulens_eval/tests/unit/test_feedback.py
  trulens_eval/trulens_eval/Example_TruBot.py
  trulens_eval/trulens_eval/feedback/feedback.py
  trulens_eval/trulens_eval/feedback/provider/base.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/openai.py
  trulens_eval/trulens_eval/feedback/provider/langchain.py
  trulens_eval/trulens_eval/tru.py
  trulens_eval/trulens_eval/utils/imports.py
  trulens_eval/trulens_eval/utils/json.py
Labels: size:L, lgtm

#1217 Fix test cases generation - normalization step for SummEval score
  trulens_eval/trulens_eval/tests/test_cases.py
Labels: size:XS

#1219 Format `snowflake_demo` branch.
  trulens_eval/examples/snowflake_demo/app.py
  trulens_eval/examples/snowflake_demo/common_ui.py
  trulens_eval/examples/snowflake_demo/conversation_manager.py
  trulens_eval/examples/snowflake_demo/feedback.py
  trulens_eval/examples/snowflake_demo/launch_trulens_dashboard.py
  trulens_eval/examples/snowflake_demo/llm.py
  trulens_eval/examples/snowflake_demo/pages/about.py
  trulens_eval/examples/snowflake_demo/pages/account.py
  trulens_eval/examples/snowflake_demo/pages/analysis.py
  trulens_eval/examples/snowflake_demo/pages/auto_eval.py
  trulens_eval/examples/snowflake_demo/pages/trulens_leaderboard.py
  trulens_eval/examples/snowflake_demo/pages/users.py
  trulens_eval/examples/snowflake_demo/retrieve.py
  trulens_eval/examples/snowflake_demo/schema.py
  trulens_eval/trulens_eval/Example_TruBot.py
  trulens_eval/trulens_eval/database/sqlalchemy.py
  trulens_eval/trulens_eval/feedback/provider/base.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/openai.py
  trulens_eval/trulens_eval/tru.py
  trulens_eval/trulens_eval/utils/imports.py
Labels: size:XL, lgtm

#1221 clean nodes with lower split threshold and upsert to pinecone
  trulens_eval/examples/snowflake_demo/preprocess_load_vectorstore.ipynb
Labels: size:XS, lgtm

#1223 Enable regex to extract floats in score generation
  trulens_eval/tests/unit/test_feedback_score_generation.py
  trulens_eval/trulens_eval/utils/generated.py
Labels: size:S, lgtm

#1220 Add Corey's context relevance model as a "small local model" for context relevance feedback in the snowflake demo.
  trulens_eval/examples/snowflake_demo/custom_feedback/small_local_models.py
  trulens_eval/examples/snowflake_demo/feedback.py
  trulens_eval/examples/snowflake_demo/requirements.txt
  trulens_eval/examples/snowflake_demo/spcs/docker_cmds.sh
Labels: dependencies, size:L, lgtm

#1222 Insert streamlit docs instead of just into Pinecone, but also into a table in Snowflake as straight up chunked text.
  trulens_eval/examples/snowflake_demo/preprocess_load_vectorstore.ipynb
Labels: size:M, lgtm

#1228 Fix cost tracking in OpenAI and LiteLLM endpoints
  trulens_eval/trulens_eval/feedback/provider/endpoint/litellm.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/openai.py
Labels: size:XS, lgtm

#1225 Allow for Cortex Search instead of just Pinecone.
  trulens_eval/examples/snowflake_demo/.env.template
  trulens_eval/examples/snowflake_demo/Dockerfile
  trulens_eval/examples/snowflake_demo/common_ui.py
  trulens_eval/examples/snowflake_demo/llm.py
  trulens_eval/examples/snowflake_demo/requirements.txt
  trulens_eval/examples/snowflake_demo/retrieve.py
  trulens_eval/examples/snowflake_demo/schema.py
  trulens_eval/examples/snowflake_demo/spcs/set_up.sql
  trulens_eval/examples/snowflake_demo/spcs/start_service.sql
Labels: dependencies, size:M, lgtm

#1234 Update pull_request_template.md
  docs/pull_request_template.md
Labels: documentation, size:S, lgtm

#1233 remove deprecated legacy caching
  trulens_eval/trulens_eval/Leaderboard.py
Labels: size:XS, lgtm

#1216 Add snowflake sqlalchemy implementation
  docs/trulens_eval/tracking/logging/where_to_log/index.md
  docs/trulens_eval/tracking/logging/where_to_log/log_in_snowflake.md
  mkdocs.yml
  trulens_eval/trulens_eval/database/orm.py
  trulens_eval/trulens_eval/database/sqlalchemy.py
  trulens_eval/trulens_eval/pages/Evaluations.py
Labels: size:M, lgtm

#1235 [CP] Add snowflake sqlalchemy implementation (#1216)
  docs/trulens_eval/tracking/logging/where_to_log/index.md
  docs/trulens_eval/tracking/logging/where_to_log/log_in_snowflake.md
  mkdocs.yml
  trulens_eval/trulens_eval/database/orm.py
  trulens_eval/trulens_eval/database/sqlalchemy.py
  trulens_eval/trulens_eval/pages/Evaluations.py
Labels: documentation, size:M, lgtm

#1192 Context filtering guardrails
  docs/trulens_eval/api/guardrails/index.md
  docs/trulens_eval/api/guardrails/langchain.md
  docs/trulens_eval/api/guardrails/llama.md
  docs/trulens_eval/guardrails/guardrail_context_filtering.png
  docs/trulens_eval/guardrails/index.md
  docs/trulens_eval/guardrails/simple_guardrail_flow.png
  mkdocs.yml
  trulens_eval/examples/expositional/end2end_apps/trubot/trubot_example.ipynb
  trulens_eval/examples/quickstart/langchain_quickstart.ipynb
  trulens_eval/examples/quickstart/llama_index_quickstart.ipynb
  trulens_eval/examples/quickstart/quickstart.ipynb
  trulens_eval/tests/unit/static/test_static.py
  trulens_eval/trulens_eval/guardrails/__init__.py
  trulens_eval/trulens_eval/guardrails/base.py
  trulens_eval/trulens_eval/guardrails/langchain.py
  trulens_eval/trulens_eval/guardrails/llama.py
  trulens_eval/trulens_eval/tru_chain.py
  trulens_eval/trulens_eval/tru_llama.py
  trulens_eval/trulens_eval/utils/display.py
  trulens_eval/trulens_eval/utils/langchain.py
  trulens_eval/trulens_eval/utils/llama.py
Labels: size:XXL, lgtm

#1239 [cp] Context filtering guardrails (#1192)
  docs/trulens_eval/api/guardrails/index.md
  docs/trulens_eval/api/guardrails/langchain.md
  docs/trulens_eval/api/guardrails/llama.md
  docs/trulens_eval/guardrails/guardrail_context_filtering.png
  docs/trulens_eval/guardrails/index.md
  docs/trulens_eval/guardrails/simple_guardrail_flow.png
  mkdocs.yml
  trulens_eval/examples/expositional/end2end_apps/trubot/trubot_example.ipynb
  trulens_eval/examples/quickstart/langchain_quickstart.ipynb
  trulens_eval/examples/quickstart/llama_index_quickstart.ipynb
  trulens_eval/examples/quickstart/quickstart.ipynb
  trulens_eval/tests/unit/static/test_static.py
  trulens_eval/trulens_eval/guardrails/__init__.py
  trulens_eval/trulens_eval/guardrails/base.py
  trulens_eval/trulens_eval/guardrails/langchain.py
  trulens_eval/trulens_eval/guardrails/llama.py
  trulens_eval/trulens_eval/tru_chain.py
  trulens_eval/trulens_eval/tru_llama.py
  trulens_eval/trulens_eval/utils/display.py
  trulens_eval/trulens_eval/utils/langchain.py
  trulens_eval/trulens_eval/utils/llama.py
Labels: documentation, size:XXL, lgtm

#1241 remove copy signature
  trulens_eval/trulens_eval/guardrails/base.py
Labels: size:XS

#1242 remove copy signature
  trulens_eval/trulens_eval/guardrails/base.py
Labels: size:XS, lgtm

#1230 adjust optional imports assert_installed and optional imports docs.
  .azure_pipelines/ci-eval-pr.yaml
  docs/docs_requirements.txt
  docs/trulens_eval/contributing/index.md
  docs/trulens_eval/contributing/optional.md
  mkdocs.yml
  trulens_eval/trulens_eval/Example_TruBot.py
  trulens_eval/trulens_eval/appui.py
  trulens_eval/trulens_eval/feedback/provider/bedrock.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/bedrock.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/litellm.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/openai.py
  trulens_eval/trulens_eval/feedback/provider/litellm.py
  trulens_eval/trulens_eval/feedback/provider/openai.py
  trulens_eval/trulens_eval/tru_llama.py
  trulens_eval/trulens_eval/tru_rails.py
  trulens_eval/trulens_eval/utils/imports.py
  trulens_eval/trulens_eval/utils/llama.py
Labels: documentation, size:L, lgtm

#1202 Add Snowflake's Cortex LLM function as a new feedback provider + Cortex-Finetune on feedback providers
  .azure_pipelines/ci-eval-pr.yaml
  docs/trulens_eval/api/provider/cortex.md
  mkdocs.yml
  trulens_eval/examples/experimental/cortex_finetuning_groundedness_ff.ipynb
  trulens_eval/examples/expositional/models/arctic_quickstart.ipynb
  trulens_eval/tests/e2e/test_endpoints.py
  trulens_eval/tests/unit/static/test_static.py
  trulens_eval/trulens_eval/__init__.py
  trulens_eval/trulens_eval/feedback/__init__.py
  trulens_eval/trulens_eval/feedback/provider/__init__.py
  trulens_eval/trulens_eval/feedback/provider/cortex.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/__init__.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/base.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/cortex.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/litellm.py
  trulens_eval/trulens_eval/keys.py
  trulens_eval/trulens_eval/requirements.optional.txt
  trulens_eval/trulens_eval/tests/test_cases.py
  trulens_eval/trulens_eval/utils/imports.py
Labels: size:XL, lgtm

#1227 [CP] Add Cortex as new feedback provider
  .azure_pipelines/ci-eval-pr.yaml
  docs/trulens_eval/api/provider/cortex.md
  mkdocs.yml
  trulens_eval/examples/experimental/cortex_finetuning_groundedness_ff.ipynb
  trulens_eval/examples/expositional/models/arctic_quickstart.ipynb
  trulens_eval/examples/snowflake_demo/feedback.py
  trulens_eval/tests/e2e/test_endpoints.py
  trulens_eval/tests/unit/static/test_static.py
  trulens_eval/trulens_eval/__init__.py
  trulens_eval/trulens_eval/feedback/__init__.py
  trulens_eval/trulens_eval/feedback/provider/__init__.py
  trulens_eval/trulens_eval/feedback/provider/cortex.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/__init__.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/base.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/cortex.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/litellm.py
  trulens_eval/trulens_eval/keys.py
  trulens_eval/trulens_eval/requirements.optional.txt
  trulens_eval/trulens_eval/tests/test_cases.py
  trulens_eval/trulens_eval/utils/imports.py
Labels: size:XL, lgtm

#1245 Fix small typo in arctic quickstart notebook
  trulens_eval/examples/expositional/models/arctic_quickstart.ipynb
Labels: size:XS

#1246 Remove remaining streamlit legacy_caching.clear_cache() line
  trulens_eval/trulens_eval/pages/Apps.py
Labels: size:XS, lgtm

#1244 Use float instead of flooring in feedback score extraction + update docstring
  trulens_eval/tests/unit/test_feedback_score_generation.py
  trulens_eval/trulens_eval/utils/generated.py
Labels: documentation, size:S, lgtm

#1240 0.32.0 release
  trulens_eval/RELEASES.md
  trulens_eval/trulens_eval/__init__.py
Labels: size:L, lgtm

#1229 add configurable context filter to demo
  trulens_eval/examples/snowflake_demo/common_ui.py
  trulens_eval/examples/snowflake_demo/llm.py
  trulens_eval/examples/snowflake_demo/retrieve.py
Labels: size:M, lgtm

#1243 Create "local" version of Huggingface provider.
  trulens_eval/examples/expositional/models/local_vs_remote_huggingface_feedback_functions.ipynb
  trulens_eval/trulens_eval/__init__.py
  trulens_eval/trulens_eval/feedback/__init__.py
  trulens_eval/trulens_eval/feedback/provider/__init__.py
  trulens_eval/trulens_eval/feedback/provider/hugs.py
  trulens_eval/trulens_eval/requirements.optional.txt
Labels: size:XXL, lgtm

#1252 Change `context_filter` guard rail to take in an argument for what to use as the prompt as it was confusing and causing issues before.
  trulens_eval/trulens_eval/guardrails/base.py
Labels: size:S, lgtm

#1253 Change context_filter guard rail to take in an argument for what to use as the prompt as it was confusing and causing issues before.
  trulens_eval/examples/snowflake_demo/feedback.py
  trulens_eval/examples/snowflake_demo/llm.py
  trulens_eval/trulens_eval/guardrails/base.py
Labels: size:M, lgtm

#1251 Demo Provider Toggle
  trulens_eval/examples/snowflake_demo/.env.template
  trulens_eval/examples/snowflake_demo/app.py
  trulens_eval/examples/snowflake_demo/common_ui.py
  trulens_eval/examples/snowflake_demo/feedback.py
  trulens_eval/examples/snowflake_demo/launch_trulens_dashboard.py
  trulens_eval/examples/snowflake_demo/llm.py
  trulens_eval/examples/snowflake_demo/preprocess_load_vectorstore.ipynb
  trulens_eval/examples/snowflake_demo/retrieve.py
  trulens_eval/examples/snowflake_demo/schema.py
  trulens_eval/examples/snowflake_demo/spcs/docker_cmds.sh
  trulens_eval/examples/snowflake_demo/spcs/start_service.sql
  trulens_eval/trulens_eval/feedback/provider/cortex.py
  trulens_eval/trulens_eval/guardrails/base.py
Labels: size:L, lgtm

#1256 Fix small model scoring
  trulens_eval/examples/snowflake_demo/custom_feedback/small_local_models.py
Labels: size:S, lgtm

#1257 Cache TruCustomApp
  trulens_eval/examples/snowflake_demo/common_ui.py
Labels: size:S, lgtm

#1259 Establish snowflake connection every Cortex Search invocation.
  trulens_eval/examples/snowflake_demo/retrieve.py
Labels: size:M, lgtm

#1261 Read warehouse env var for cortex provider
  trulens_eval/trulens_eval/feedback/provider/cortex.py
Labels: size:XS, lgtm

#1262 [CP] Add warehouse env var to cortex llm provider
  trulens_eval/trulens_eval/feedback/provider/cortex.py
Labels: size:XS, lgtm

#1263 Streamlit in-app exception logging
  trulens_eval/examples/snowflake_demo/app.py
Labels: size:XL, lgtm

#1255 Demo changes (toggles, feedback list, preload nb updates)
  trulens_eval/examples/snowflake_demo/common_ui.py
  trulens_eval/examples/snowflake_demo/feedback.py
  trulens_eval/examples/snowflake_demo/llm.py
  trulens_eval/examples/snowflake_demo/preload_apps.ipynb
  trulens_eval/examples/snowflake_demo/schema.py
Labels: size:L, lgtm

#1265 Add Mistral Large as a new model provider
  trulens_eval/examples/snowflake_demo/llm.py
Labels: size:XS, lgtm

#1232 add row limit/offset to Tru.get_records_and_feedback
  docs/docs_requirements.txt
  trulens_eval/examples/experimental/dummy_example.ipynb
  trulens_eval/trulens_eval/database/base.py
  trulens_eval/trulens_eval/database/orm.py
  trulens_eval/trulens_eval/database/sqlalchemy.py
  trulens_eval/trulens_eval/pages/Evaluations.py
  trulens_eval/trulens_eval/tru.py
Labels: size:L, lgtm

#1266 virtual record should use supplied perf, cost
  trulens_eval/trulens_eval/tru_virtual.py
Labels: size:S, lgtm
