Repository truera/trulens, pull requests merged in 2024-05, with the labels that each got.

#1116 Remove references to running moderation endpoint on AzureOpenAI
  docs/trulens_eval/api/provider/openai/azureopenai.md
  trulens_eval/trulens_eval/feedback/provider/openai.py
Labels: documentation, size:S, lgtm

#1120 swap rag utility (qs)relevance
  trulens_eval/trulens_eval/feedback/feedback.py
Labels: size:XS, lgtm

#1123 log in snowflake docs
  docs/trulens_eval/tracking/logging/where_to_log/index.md
  docs/trulens_eval/tracking/logging/where_to_log/log_in_snowflake.md
Labels: size:S

#1128 Fix Link in Readme
  README.md
Labels: documentation, size:XS, lgtm

#1112 update groundedness prompt
  trulens_eval/trulens_eval/feedback/v2/feedback.py
Labels: size:XS, lgtm

#1129 Fix docs links in instrumentation
  docs/trulens_eval/tracking/instrumentation/langchain.ipynb
  docs/trulens_eval/tracking/instrumentation/llama_index.ipynb
  docs/trulens_eval/tracking/instrumentation/nemo.ipynb
Labels: documentation, size:L, lgtm

#1110 fix rag triad and awaitable calls
  trulens_eval/examples/expositional/frameworks/nemoguardrails/nemoguardrails_trurails_example.ipynb
  trulens_eval/trulens_eval/app.py
  trulens_eval/trulens_eval/instruments.py
  trulens_eval/trulens_eval/schema/record.py
  trulens_eval/trulens_eval/schema/types.py
  trulens_eval/trulens_eval/utils/serial.py
Labels: size:L, lgtm

#1119 [trurails] update __getattr__ in select_context
  trulens_eval/trulens_eval/tru_rails.py
Labels: size:S, lgtm

#1130 trurails: update to getattr
  trulens_eval/trulens_eval/tru_rails.py
Labels: size:S, lgtm

#1127 Remove placeholder feedback for asynchronous responses
  trulens_eval/trulens_eval/instruments.py
Labels: size:S, lgtm

#1122 Default names for rag triad utility
  trulens_eval/trulens_eval/feedback/feedback.py
Labels: size:S, lgtm

#1134 Lagging docs changes (custom functions)
  docs/trulens_eval/evaluation/feedback_implementations/custom_feedback_functions.ipynb
Labels: documentation, size:S, lgtm

#1136 Update README.md
  README.md
Labels: documentation, size:XS, lgtm

#1135 Unify groundedness interface
  trulens_eval/examples/expositional/frameworks/langchain/langchain_summarize.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_agents.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_complex_evals.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_groundtruth.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_hybrid_retriever.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_multimodal.ipynb
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_queryplanning.ipynb
  trulens_eval/examples/expositional/frameworks/openai_assistants/openai_assistants_api.ipynb
  trulens_eval/examples/expositional/models/azure_openai_langchain.ipynb
  trulens_eval/examples/expositional/models/bedrock_finetuning_experiments.ipynb
  trulens_eval/examples/expositional/models/claude3_quickstart.ipynb
  trulens_eval/examples/expositional/models/gemini_multi_modal.ipynb
  trulens_eval/examples/expositional/models/google_vertex_quickstart.ipynb
  trulens_eval/examples/expositional/models/litellm_quickstart.ipynb
  trulens_eval/examples/expositional/use_cases/iterate_on_rag/1_rag_prototype.ipynb
  trulens_eval/examples/expositional/use_cases/iterate_on_rag/2_honest_rag.ipynb
  trulens_eval/examples/expositional/use_cases/summarization_eval.ipynb
  trulens_eval/examples/expositional/vector-dbs/milvus/milvus_evals_build_better_rags.ipynb
  trulens_eval/examples/expositional/vector-dbs/mongodb_atlas/atlas_quickstart.ipynb
  trulens_eval/examples/expositional/vector-dbs/pinecone/pinecone_evals_build_better_rags.ipynb
  trulens_eval/examples/expositional/vector-dbs/pinecone/pinecone_quickstart.ipynb
  trulens_eval/examples/quickstart/existing_data_quickstart.ipynb
  trulens_eval/examples/quickstart/langchain_quickstart.ipynb
  trulens_eval/examples/quickstart/llama_index_quickstart.ipynb
  trulens_eval/examples/quickstart/quickstart.ipynb
  trulens_eval/trulens_eval/feedback/README.md
  trulens_eval/trulens_eval/feedback/__init__.py
  trulens_eval/trulens_eval/feedback/feedback.py
  trulens_eval/trulens_eval/feedback/groundedness.py
  trulens_eval/trulens_eval/feedback/prompts.py
  trulens_eval/trulens_eval/feedback/provider/base.py
  trulens_eval/trulens_eval/feedback/provider/hugs.py
  trulens_eval/trulens_eval/feedback/v2/feedback.py
  trulens_eval/trulens_eval/generate_test_set.py
Labels: size:XXL, lgtm

#1138 dont iterate streams in openai cost tracking
  trulens_eval/examples/experimental/dev_notebook.ipynb
  trulens_eval/trulens_eval/app.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/openai.py
  trulens_eval/trulens_eval/tru_chain.py
  trulens_eval/trulens_eval/utils/json.py
Labels: size:L, lgtm

#1139 Fix a few old groundedness references
  docs/trulens_eval/evaluation/feedback_selectors/selecting_components.md
  trulens_eval/examples/experimental/MultiQueryRetrievalLangchain.ipynb
  trulens_eval/examples/experimental/random_evaluation.ipynb
  trulens_eval/examples/expositional/frameworks/canopy/canopy_quickstart.ipynb
Labels: size:M

#1140 0.29.0 version bump
  docs/trulens_eval/api/providers.md
  docs/trulens_eval/evaluation/feedback_implementations/stock.md
  docs/trulens_eval/tracking/instrumentation/langchain.ipynb
  trulens_eval/examples/quickstart/langchain_quickstart.ipynb
  trulens_eval/generated_files/all_tools.py
  trulens_eval/trulens_eval/__init__.py
  trulens_eval/trulens_eval/feedback/provider/base.py
  trulens_eval/trulens_eval/feedback/provider/hugs.py
  trulens_eval/trulens_eval/feedback/provider/openai.py
Labels: size:XXL, lgtm

#1144 glossary additions
  docs/trulens_eval/getting_started/core_concepts/index.md
Labels: documentation, size:M, lgtm

#1146 Patch imports error
  trulens_eval/trulens_eval/requirements.txt
Labels: dependencies, size:XS, lgtm

#1154 add langchain_community to optional imports and checks for use of openai endpoint
  docs/trulens_eval/all_tools.ipynb
  trulens_eval/examples/expositional/end2end_apps/trubot/webindex.ipynb
  trulens_eval/examples/expositional/frameworks/langchain/langchain_groundtruth.ipynb
  trulens_eval/examples/expositional/frameworks/langchain/langchain_model_comparison.ipynb
  trulens_eval/examples/expositional/frameworks/langchain/langchain_summarize.ipynb
  trulens_eval/examples/expositional/models/Vectara_HHEM_evaluator.ipynb
  trulens_eval/examples/expositional/use_cases/pii_detection.ipynb
  trulens_eval/examples/expositional/vector-dbs/pinecone/pinecone_evals_build_better_rags.ipynb
  trulens_eval/examples/quickstart/langchain_quickstart.ipynb
  trulens_eval/trulens_eval/Example_TruBot.py
  trulens_eval/trulens_eval/feedback/provider/endpoint/openai.py
  trulens_eval/trulens_eval/requirements.optional.txt
  trulens_eval/trulens_eval/utils/imports.py
Labels: dependencies, size:M, lgtm

#1158 TruLens-Eval 0.30.0
  trulens_eval/trulens_eval/__init__.py
Labels: size:XS

#1159 0.30.1 bump
  trulens_eval/trulens_eval/__init__.py
Labels: size:XS

#1161 Fix a few more old groundedness references + llamaindex agent toolspec import
  trulens_eval/examples/expositional/frameworks/llama_index/llama_index_agents.ipynb
  trulens_eval/trulens_eval/tests/groundedness_benchmark.ipynb
Labels: size:XS, lgtm

#1165 Garett/pydantic json
  trulens_eval/examples/experimental/schema.ipynb
  trulens_eval/trulens_eval/react_components/record_viewer/src/schema/schema.json
  trulens_eval/trulens_eval/react_components/record_viewer/src/types/schema.ts
  trulens_eval/trulens_eval/trace/__init__.py
  trulens_eval/trulens_eval/trace/category.py
  trulens_eval/trulens_eval/trace/span.py
  trulens_eval/trulens_eval/trace/tracer.py
  trulens_eval/trulens_eval/utils/containers.py
Labels: size:XXL
