Repository truera/trulens, pull requests merged in 2024-12, with the labels that each got.

#1654 fix async pace
  examples/experimental/pace_example.ipynb
  src/core/trulens/core/utils/pace.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: documentation, size:L

#1670 Fix `poetry` environment issues.
  poetry.lock
  pyproject.toml
  src/feedback/pyproject.toml
Labels: dependencies, size:S

#1669 Create trulens-semconv package.
  src/connectors/snowflake/trulens/connectors/snowflake/utils/server_side_evaluation_artifacts.py
  src/core/pyproject.toml
  src/semconv/README.md
  src/semconv/pyproject.toml
  src/semconv/trulens/semconv/__init__.py
  src/semconv/trulens/semconv/trace.py
  tests/e2e/data/staged_packages.ipynb
  tests/e2e/test_context_variables.py
  zip_wheels.sh
Labels: size:XL

#1673 strip quotes from connection params
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
Labels: size:XS

#1671 TruLens 1.2.9
  poetry.lock
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: dependencies, size:M

#1672 decode app and record json in get_df_and_cols
  src/core/trulens/core/database/connector/base.py
  src/core/trulens/core/database/sqlalchemy.py
  src/dashboard/trulens/dashboard/pages/Compare.py
  src/dashboard/trulens/dashboard/pages/Records.py
  src/dashboard/trulens/dashboard/streamlit.py
Labels: size:M

#1676 reset_database only drops trulens tables
  src/core/trulens/core/database/sqlalchemy.py
Labels: size:S

#1677 trulens-dashboard: handle selected_rows is None and fix fallback to st.dataframe in SiS
  src/dashboard/trulens/dashboard/Leaderboard.py
  src/dashboard/trulens/dashboard/pages/Compare.py
Labels: size:M

#1679 Fix Cortex complete SDK response parsing.
  src/providers/cortex/pyproject.toml
  src/providers/cortex/trulens/providers/cortex/provider.py
Labels: size:S

#1681 Rename `trulens-semconv` to `trulens-otel-semconv`.
  poetry.lock
  pyproject.toml
  src/connectors/snowflake/trulens/connectors/snowflake/utils/server_side_evaluation_artifacts.py
  src/core/pyproject.toml
  src/otel/semconv/README.md
  src/otel/semconv/pyproject.toml
  src/otel/semconv/trulens/otel/semconv/__init__.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/e2e/data/staged_packages.ipynb
  zip_wheels.sh
Labels: size:M

#1678 trulens-semvar conda build files
  src/otel/semconv/meta.yaml
  src/otel/semconv/trulens/otel/semconv/__init__.py
Labels: dependencies, size:M

#1683 Add snowflake PrPr notebook
  examples/quickstart/snowflake_ai_observability_example.ipynb
Labels: size:XS

#1675 Support types for Python `< 3.9`.
  src/apps/langchain/trulens/apps/langchain/langchain.py
  src/apps/llamaindex/trulens/apps/llamaindex/llama.py
  src/core/trulens/core/_utils/pycompat.py
  src/core/trulens/core/instruments.py
  src/core/trulens/core/utils/python.py
  src/core/trulens/core/utils/trulens.py
  src/providers/openai/trulens/providers/openai/endpoint.py
  tests/test.py
  tests/utils.py
Labels: size:M

#1682 TruLens 1.2.10
  poetry.lock
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1686 Change issue assignee to Prudhvi to triage
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size:XS

#1660 TREC DL and LLM AggreFact experiments for relevance benchmark + prompts comparisons and groundedness vs Bespoke Minicheck 7B
  .gitignore
  src/benchmark/trulens/benchmark/benchmark_frameworks/experiments/competitive_analysis.ipynb
  src/benchmark/trulens/benchmark/benchmark_frameworks/experiments/context_relevance/trec_dl_passage_relevance_judges.ipynb
  src/benchmark/trulens/benchmark/benchmark_frameworks/experiments/dataset_preprocessing.py
  src/benchmark/trulens/benchmark/benchmark_frameworks/experiments/groundedness/llm_aggrefact_groundedness_benchmark.ipynb
  src/benchmark/trulens/benchmark/benchmark_frameworks/tru_benchmark_experiment.py
  src/core/trulens/core/feedback/feedback.py
Labels: size:XXL

#1621 Agents: Example of observability for CrewAI
  examples/expositional/frameworks/crewai/surprise_trip/.env.example
  examples/expositional/frameworks/crewai/surprise_trip/Makefile
  examples/expositional/frameworks/crewai/surprise_trip/README.md
  examples/expositional/frameworks/crewai/surprise_trip/poetry.lock
  examples/expositional/frameworks/crewai/surprise_trip/pyproject.toml
  examples/expositional/frameworks/crewai/surprise_trip/run_dashboard.py
  examples/expositional/frameworks/crewai/surprise_trip/src/surprise_travel/__init__.py
  examples/expositional/frameworks/crewai/surprise_trip/src/surprise_travel/config/agents.yaml
  examples/expositional/frameworks/crewai/surprise_trip/src/surprise_travel/config/tasks.yaml
  examples/expositional/frameworks/crewai/surprise_trip/src/surprise_travel/crew.py
  examples/expositional/frameworks/crewai/surprise_trip/src/surprise_travel/main.py
  examples/expositional/frameworks/crewai/surprise_trip/src/surprise_travel/notebook.ipynb
  examples/expositional/frameworks/crewai/surprise_trip/src/surprise_travel/tools/__init__.py
  examples/expositional/frameworks/crewai/surprise_trip/src/surprise_travel/tools/custom_tool.py
  src/apps/langchain/pyproject.toml
  src/core/trulens/apps/custom.py
  src/core/trulens/core/instruments.py
  src/core/trulens/core/utils/pyschema.py
  src/core/trulens/experimental/otel_tracing/core/trace.py
Labels: size:XL

#1695 Set langchain version for crewai example
  examples/expositional/frameworks/crewai/surprise_trip/pyproject.toml
  snowflake_buffered_ingestion_100.png
  src/apps/langchain/pyproject.toml
Labels: dependencies, size:S

#1697 TruLens 1.2.11
  poetry.lock
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1674 Feedback customization (including few-shot examples)
  docs/component_guides/evaluation/feedback_implementations/custom_feedback_functions.ipynb
  examples/experimental/feedback_with_fewshot_examples.ipynb
  src/core/trulens/core/feedback/feedback.py
  src/core/trulens/core/schema/feedback.py
  src/feedback/trulens/feedback/llm_provider.py
  src/feedback/trulens/feedback/v2/feedback.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: documentation, size:XXL

#1698 [SNOW-1733946] Allow existing tables to be used in ground truth datasets
  examples/quickstart/load_virtual_groundtruth.ipynb
  poetry.lock
  src/core/trulens/core/database/base.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/schema/__init__.py
  src/core/trulens/core/schema/groundtruth.py
  src/core/trulens/core/session.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: size:XL

#1692 Introduce Event table for ORM to prepare for OTEL traces
  docs/contributing/migration.md
  examples/experimental/otel_exporter.ipynb
  src/core/trulens/core/database/migrations/data.py
  src/core/trulens/core/database/migrations/versions/10_create_event_table.py
  src/core/trulens/core/database/orm.py
  src/core/trulens/core/schema/event.py
  src/core/trulens/core/schema/types.py
  tests/unit/static/golden/api.trulens.3.11.yaml
Labels: documentation, size:L

#1694 Prototype OTEL exporter
  examples/experimental/otel_exporter.ipynb
  src/core/trulens/core/database/base.py
  src/core/trulens/core/database/connector/base.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/experimental/otel_tracing/core/exporter.py
  src/core/trulens/experimental/otel_tracing/core/init.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: size:L

#1693 Prototype @instrument with OTEL
  Makefile
  examples/experimental/otel_exporter.ipynb
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/experimental/otel_tracing/core/instrument.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/test.py
  tests/unit/static/golden/test_otel_instrument__test_instrument_decorator.csv
  tests/unit/test_otel_instrument.py
  tests/util/df_comparison.py
Labels: size:XL
