Repository truera/trulens, pull requests merged in 2025-05, with the labels that each got.

#1949 When converting a span attribute to a string, try to JSONify before stringifying.
  src/core/trulens/experimental/otel_tracing/core/span.py
  tests/unit/static/golden/test_otel_feedback_computation__test_feedback_computation.csv
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
  tests/unit/test_otel_span.py
  tests/util/df_comparison.py
Labels: size:M

#1953 Updating gitignore files
  .gitignore
  examples/experimental/.gitignore
  examples/expositional/vector_stores/faiss/faiss_index/index.faiss
  examples/expositional/vector_stores/faiss/faiss_index/index.pkl
  tests/.gitignore
Labels: size:S

#1952 Add storybook tests
  src/dashboard/react_components/.gitignore
  src/dashboard/react_components/record_viewer_otel/.storybook/main.ts
  src/dashboard/react_components/record_viewer_otel/.storybook/preview.tsx
  src/dashboard/react_components/record_viewer_otel/.storybook/vitest.setup.ts
  src/dashboard/react_components/record_viewer_otel/README.md
  src/dashboard/react_components/record_viewer_otel/package-lock.json
  src/dashboard/react_components/record_viewer_otel/package.json
  src/dashboard/react_components/record_viewer_otel/setup.jsdom.ts
  src/dashboard/react_components/record_viewer_otel/src/JSONViewer/JSONViewer.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/LabelAndValue/LabelAndValue.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/Panel/Panel.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/Panel/Panel.tsx
  src/dashboard/react_components/record_viewer_otel/src/RecordTable/RecordTable.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/RecordTable/RecordTable.tsx
  src/dashboard/react_components/record_viewer_otel/src/SpanTooltip/SpanTooltip.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/StyledTooltip/StyledTooltip.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/Tabs/Tabs/Tabs.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/Tag/Tag.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/TraceAttributes/TraceAttributes.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/TraceAttributes/TraceAttributes.tsx
  src/dashboard/react_components/record_viewer_otel/src/TraceContent/TraceContent.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/TraceContent/TraceContent.tsx
  src/dashboard/react_components/record_viewer_otel/src/__testing__/createSpan.ts
  src/dashboard/react_components/record_viewer_otel/src/__testing__/createStackTreeNode.ts
  src/dashboard/react_components/record_viewer_otel/src/functions/createNodeMap.test.ts
  src/dashboard/react_components/record_viewer_otel/src/functions/createTreeFromCalls.test.ts
  src/dashboard/react_components/record_viewer_otel/src/functions/formatters.test.ts
  src/dashboard/react_components/record_viewer_otel/src/functions/processCostAttributes.test.ts
  src/dashboard/react_components/record_viewer_otel/src/functions/processTokenAttributes.test.tsx
  src/dashboard/react_components/record_viewer_otel/src/functions/processTokenAttributes.tsx
  src/dashboard/react_components/record_viewer_otel/src/utils/ThemeProvider.tsx
  src/dashboard/react_components/record_viewer_otel/src/utils/theme.ts
  src/dashboard/react_components/record_viewer_otel/tsconfig.json
  src/dashboard/react_components/record_viewer_otel/vite.config.ts
  src/dashboard/react_components/record_viewer_otel/vitest.shims.d.ts
  src/dashboard/react_components/record_viewer_otel/vitest.workspace.ts
Labels: size:XXL

#1955 Update OTEL semantic convention in `EVAL_ROOT` to hold more info about feedback function metadata.
  src/otel/semconv/trulens/otel/semconv/trace.py
Labels: size:S

#1957 Split `Selector` into its own file so it's easier for users to use and doesn't easily induce cyclic imports.
  src/core/trulens/core/feedback/selector.py
  src/feedback/trulens/feedback/computer.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/test_otel_feedback_computation.py
  tests/unit/test_otel_selector.py
Labels: size:XL

#1956 Add accordion functionality to Panel.
  src/dashboard/react_components/record_viewer_otel/src/Panel/Panel.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/Panel/Panel.tsx
Labels: javascript, size:M

#1958 Write app to App defn table in OTEL again.
  src/core/trulens/core/app.py
  tests/test.py
  tests/unit/data/test_otel_apps_table/test_smoke.json
  tests/unit/test_otel_apps_table.py
Labels: size:L

#1951 [SNOW-2081987] Enable OTEL record pagination based on unique, sorted record_ids from event table
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/schema/app.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/unit/data/test_otel_spans/eval_root_span.json
  tests/unit/data/test_otel_spans/eval_span_1.json
  tests/unit/data/test_otel_spans/eval_span_2.json
  tests/unit/data/test_otel_spans/generation_span.json
  tests/unit/data/test_otel_spans/record_root_span.json
  tests/unit/data/test_otel_spans/retrieval_span.json
  tests/unit/data/test_otel_spans/template_record_root_span.json
  tests/unit/test_otel_get_records_and_feedback.py
Labels: size:XL

#1950 Update Jenkinsfile to add Jest + Storybook tests
  Makefile
  src/dashboard/react_components/record_viewer_otel/.storybook/main.ts
  src/dashboard/react_components/record_viewer_otel/.storybook/preview-head.html
  src/dashboard/react_components/record_viewer_otel/Dockerfile.test
  src/dashboard/react_components/record_viewer_otel/README.md
  src/dashboard/react_components/record_viewer_otel/docker-compose.test.yml
  src/dashboard/react_components/record_viewer_otel/package-lock.json
  src/dashboard/react_components/record_viewer_otel/package.json
  src/dashboard/react_components/record_viewer_otel/src/JSONViewer/JSONViewer.tsx
  src/dashboard/react_components/record_viewer_otel/src/functions/formatters.test.ts
  src/dashboard/react_components/record_viewer_otel/test-wrapper.sh
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-jsonviewer--default.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-jsonviewer--empty.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-jsonviewer--with-array.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-jsonviewer--with-long-string.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-jsonviewer--with-nested-object.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-labelandvalue--default.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-labelandvalue--with-custom-alignment.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-labelandvalue--with-react-node-value.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-panel--default.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-spantooltip--custom-child.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-spantooltip--default.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-spantooltip--llm-span.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-spantooltip--unknown-span-type.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-styledtooltip--default.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-styledtooltip--long-content.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-styledtooltip--with-button.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-styledtooltip--with-rich-content.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tabs--custom-styling.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tabs--many-tabs.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tag--custom-styling.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tag--default.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tag--long-text.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tag--with-both-icons.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tag--with-left-icon.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tag--with-right-icon.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-traceattributes--empty.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-traceattributes--generation-attributes.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-traceattributes--retrieval-attributes.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tracecontent--array-of-long-strings.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tracecontent--array-of-strings.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tracecontent--boolean-value.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tracecontent--empty-string.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tracecontent--empty.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tracecontent--json-string.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tracecontent--nested-object.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tracecontent--number-value.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tracecontent--simple-object.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tracecontent--simple-string.png
  src/dashboard/react_components/record_viewer_otel/vite.config.ts
  src/dashboard/react_components/record_viewer_otel/vitest.setup.ts
  src/dashboard/react_components/record_viewer_otel/vitest.workspace.ts
  tests/Jenkinsfile
Labels: javascript, size:L

#1960 Span attributes for Snowflake tools Langgraph demo
  examples/experimental/multi-agent-collaboration-snowflake-tools.ipynb
  src/core/trulens/core/otel/instrument.py
Labels: size:M

#1940 langgraph + snowflake tools
  examples/experimental/multi-agent-collaboration-snowflake-tools.ipynb
  src/core/trulens/core/otel/instrument.py
Labels: size:XXL

#1966 Use the full function name for span attributes.
  src/core/trulens/core/otel/instrument.py
Labels: size:S

#1967 Write app id to span attributes.
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/core/schema/app.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  src/feedback/trulens/feedback/computer.py
  tests/unit/data/test_otel_spans/eval_root_span.json
  tests/unit/data/test_otel_spans/eval_span_1.json
  tests/unit/data/test_otel_spans/eval_span_2.json
  tests/unit/data/test_otel_spans/generation_span.json
  tests/unit/data/test_otel_spans/record_root_span.json
  tests/unit/data/test_otel_spans/retrieval_span.json
  tests/unit/static/golden/test_otel_feedback_computation__test_feedback_computation.csv
  tests/unit/static/golden/test_otel_tru_basic__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
Labels: size:M

#1961 Add more storybook tests for RecordTree
  src/dashboard/react_components/record_viewer_otel/src/Details/NodeDetails.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/Details/NodeDetails.tsx
  src/dashboard/react_components/record_viewer_otel/src/Details/Section.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/Details/Section.tsx
  src/dashboard/react_components/record_viewer_otel/src/Details/TracePanel.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/Details/TracePanel.tsx
  src/dashboard/react_components/record_viewer_otel/src/Details/styles.ts
  src/dashboard/react_components/record_viewer_otel/src/RecordInfo.tsx
  src/dashboard/react_components/record_viewer_otel/src/RecordTree/Details/Details.tsx
  src/dashboard/react_components/record_viewer_otel/src/RecordTree/RecordTree.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/RecordTree/SpanTypeTag.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/functions/formatters.ts
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-nodedetails--default.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-nodedetails--generation-span-type.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-nodedetails--many-attributes.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-nodedetails--tool-invocation-span-type.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-nodedetails--without-input-id.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-nodedetails--without-span-type.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-panel--expanded-content.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-panel--hidden-content.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtree--default.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtree--with-long-duration.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtree--with-multiple-children.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtree--with-nested-nodes.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtree--with-selected-node.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtree-spantypetag--default.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtree-spantypetag--different-span-type.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtree-spantypetag--with-custom-styling.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-section--default.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-section--long-content.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-section--with-children.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-section--without-body.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-section--without-subtitle.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-traceattributes--complex-attributes.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-traceattributes--cost-attributes.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-traceattributes--eval-attributes.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-traceattributes--generation-attributes.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-traceattributes--retrieval-attributes.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tracepanel--default.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tracepanel--with-complex-data.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tracepanel--with-empty-data.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-tracepanel--with-error.png
Labels: size:L

#1965 Add valid app info columns for get_records_and_feedback
  examples/experimental/test_otel_quickstart.ipynb
  src/core/trulens/core/database/base.py
  src/core/trulens/core/database/connector/base.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/session.py
  src/dashboard/trulens/dashboard/pages/Compare.py
  src/dashboard/trulens/dashboard/pages/Records.py
  src/dashboard/trulens/dashboard/utils/dashboard_utils.py
  src/hotspots/trulens/hotspots/tru_hotspots.py
  tests/unit/test_otel_get_records_and_feedback.py
Labels: size:XL

#1962 Add storybook tests for deep nodes + test refactoring
  src/dashboard/react_components/record_viewer_otel/src/Details/Section.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/Details/Section.tsx
  src/dashboard/react_components/record_viewer_otel/src/RecordInfo.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/RecordTable/RecordTable.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/RecordTable/RecordTable.tsx
  src/dashboard/react_components/record_viewer_otel/src/RecordTree/RecordTree.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/RecordTree/RecordTree.tsx
  src/dashboard/react_components/record_viewer_otel/src/__testing__/nodes.ts
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordinfo--complex-tree.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordinfo--deep-nested-tree.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordinfo--default.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordinfo--with-nested-nodes.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtable--default.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtable--with-deeply-nested-nodes.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtable--with-long-duration.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtable--with-multiple-children.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtable--with-nested-nodes.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtable--with-selected-node.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtree--deep-nested-tree.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtree--default.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtree--with-long-duration.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtree--with-multiple-children.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtree--with-nested-nodes.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtree--with-selected-node.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-section--long-content.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-section--with-children.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-section--without-body.png
  tests/Jenkinsfile
Labels: javascript, size:XL

#1970 [Feat] Add Report a Bug button
  src/dashboard/trulens/dashboard/utils/dashboard_utils.py
Labels: size:S

#1971 Allow for feedbacks in OTEL and kick them off via a new `TruApp::compute_feedback` function.
  src/core/trulens/core/app.py
  src/core/trulens/core/database/base.py
  src/core/trulens/core/database/connector/base.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/feedback/feedback.py
  src/core/trulens/core/feedback/feedback_function_input.py
  src/core/trulens/core/feedback/selector.py
  src/feedback/trulens/feedback/computer.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/test_otel_feedback_computation.py
  tests/unit/test_otel_selector.py
  tests/util/df_comparison.py
Labels: size:L

#1975 Consolidate checking of `TRULENS_OTEL_TRACING` env variable to check if running in OTel mode.
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  src/core/trulens/core/app.py
  src/core/trulens/core/database/migrations/versions/10_create_event_table.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/experimental/__init__.py
  src/core/trulens/core/feedback/feedback.py
  src/core/trulens/core/otel/utils.py
Labels: size:M

#1968 [Fix] Update latency from milliseconds to seconds
  examples/experimental/test_otel_quickstart.ipynb
  src/core/trulens/core/database/sqlalchemy.py
  tests/unit/test_otel_get_records_and_feedback.py
Labels: size:L

#1972 [Fix] Allow _json_extract_otel helper method to access other JSON columns in the Event ORM table
  src/core/trulens/core/database/sqlalchemy.py
Labels: size:S

#1963 Add handling for orphaned nodes
  src/dashboard/react_components/record_viewer_otel/src/RecordTable/RecordTable.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/RecordTable/RecordTableRow.tsx
  src/dashboard/react_components/record_viewer_otel/src/RecordTree/RecordTree.stories.tsx
  src/dashboard/react_components/record_viewer_otel/src/RecordTree/RecordTreeCell.tsx
  src/dashboard/react_components/record_viewer_otel/src/SpanTooltip/SpanTooltip.tsx
  src/dashboard/react_components/record_viewer_otel/src/__testing__/nodes.ts
  src/dashboard/react_components/record_viewer_otel/src/constants/node.ts
  src/dashboard/react_components/record_viewer_otel/src/functions/createTreeFromCalls.test.ts
  src/dashboard/react_components/record_viewer_otel/src/functions/createTreeFromCalls.ts
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtable--with-orphaned-nodes.png
  src/dashboard/react_components/record_viewer_otel/test/snapshots/components-recordtree--orphaned-children.png
Labels: javascript, size:L

#1964 Connect Streamlit <> OTEL Record viewer
  src/dashboard/trulens/dashboard/components/record_viewer_otel/__init__.py
  src/dashboard/trulens/dashboard/components/record_viewer_otel/dist/assets/SourceCodePro-Bold-C5Vtz9WP.ttf
  src/dashboard/trulens/dashboard/components/record_viewer_otel/dist/assets/SourceCodePro-Regular-BoGDH3YB.ttf
  src/dashboard/trulens/dashboard/components/record_viewer_otel/dist/assets/SourceCodePro-SemiBold-R6YWw784.ttf
  src/dashboard/trulens/dashboard/components/record_viewer_otel/dist/assets/index-DT9k41iQ.css
  src/dashboard/trulens/dashboard/components/record_viewer_otel/dist/assets/index-EomrdMmy.js
  src/dashboard/trulens/dashboard/components/record_viewer_otel/dist/index.html
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: javascript, size:XL

#1973 [Fix] Update groundedness measure return to 0.0 instead of NaN when no non-trivial statements are found.
  src/feedback/trulens/feedback/llm_provider.py
Labels: size:S

#1977 Don't recompute feedback functions if already done.
  src/core/trulens/core/app.py
  src/feedback/trulens/feedback/computer.py
  tests/unit/test_otel_feedback_computation.py
Labels: size:L

#1979 Deprecate SnowflakeFeedback
  examples/experimental/snowflake_feedbacks.ipynb
  src/core/trulens/core/feedback/feedback.py
Labels: size:L

#1976 Update langgraph/cortex example span attributes
  examples/expositional/frameworks/langchain/langgraph-multi-agent-snowflake-tools.ipynb
Labels: size:L

#1982 Create automatic job to compute feedbacks.
  src/core/trulens/core/app.py
  src/core/trulens/core/database/base.py
  src/core/trulens/core/database/connector/base.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/utils/evaluator.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/test_otel_evaluator.py
  tests/unit/test_otel_feedback_computation.py
Labels: size:L

#1983 Check that wrapped apps are garbage collected correctly.
  tests/unit/test_otel_apps_table.py
  tests/unit/test_otel_tru_basic.py
  tests/unit/test_otel_tru_chain.py
  tests/unit/test_otel_tru_custom.py
  tests/unit/test_otel_tru_llama.py
Labels: size:M

#1984 Start evaluator immediately and also require that `FeedbackMode` must be `WITH_APP_THREAD` (the default).
  src/core/trulens/core/app.py
  src/core/trulens/core/session.py
  src/core/trulens/core/utils/evaluator.py
  tests/unit/test_otel_feedback_computation.py
Labels: size:S

#1985 Allow use of `Feedback`'s `on_input`, `on_output`, `on_input_output`, `on_default` methods.
  src/core/trulens/core/feedback/feedback.py
  src/core/trulens/core/feedback/selector.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/test_otel_feedback.py
Labels: size:L

#1981 [SNOW-2061186, SNOW-2105931] Connect record_viewer_otel (FE) to Event table (BE)
  src/core/trulens/core/database/sqlalchemy.py
  src/dashboard/trulens/dashboard/pages/Compare.py
  src/dashboard/trulens/dashboard/pages/Records.py
  src/dashboard/trulens/dashboard/streamlit.py
  src/dashboard/trulens/dashboard/utils/dashboard_utils.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: size:L

#1986 Update vscode settings to automatically handle line length better for python files.
  .vscode/settings.json
Labels: size:XS

#1988 [SNOW-2111562] Render feedback visualizations for OTEL records
  src/core/trulens/core/database/sqlalchemy.py
Labels: size:XS

#1980 Consistently use TruApp in place of TruCustomApp
  .grit/dealias_trulens_eval.grit
  .grit/patterns/trulens_eval_migration.md
  docs/blog/posts/release_blog_1dot.md
  docs/component_guides/evaluation/running_feedback_functions/existing_data.md
  docs/component_guides/instrumentation/index.md
  docs/getting_started/core_concepts/index.md
  examples/dev/dummy_app/agent.py
  examples/dev/dummy_app/app.py
  examples/dev/dummy_app/dummy_app_example.ipynb
  examples/dev/dummy_app/filter_apps.ipynb
  examples/dev/dummy_app/llm.py
  examples/dev/dummy_app/memory.py
  examples/dev/dummy_app/reranker.py
  examples/dev/dummy_app/retriever.py
  examples/dev/dummy_app/template.py
  examples/dev/dummy_app/tool.py
  examples/experimental/appui_example.ipynb
  examples/experimental/dashboard_appui.ipynb
  examples/experimental/db_populate.ipynb
  examples/experimental/deferred_example.ipynb
  examples/experimental/export_dummy_example.ipynb
  examples/experimental/load_virtual_groundtruth.ipynb
  examples/experimental/random_evaluation.ipynb
  examples/experimental/streamlit_appui_example.ipynb
  examples/experimental/test_otel_quickstart.ipynb
  examples/expositional/frameworks/crewai/surprise_trip/src/surprise_travel/crew.py
  examples/expositional/frameworks/crewai/surprise_trip/src/surprise_travel/main.py
  examples/expositional/frameworks/crewai/surprise_trip/src/surprise_travel/notebook.ipynb
  examples/expositional/frameworks/llama_index/llama_index_agents.ipynb
  examples/expositional/frameworks/openai_assistants/openai_assistants_api.ipynb
  examples/expositional/models/anthropic/claude3_quickstart.ipynb
  examples/expositional/models/google/gemini_multi_modal.ipynb
  examples/expositional/models/local_and_OSS_models/Vectara_HHEM_evaluator.ipynb
  examples/expositional/models/local_and_OSS_models/litellm_quickstart.ipynb
  examples/expositional/models/local_and_OSS_models/local_vs_remote_huggingface_feedback_functions.ipynb
  examples/expositional/models/snowflake_cortex/cortex_finetuning_experiments.ipynb
  examples/expositional/models/snowflake_cortex/cortex_llm_quickstart.ipynb
  examples/expositional/use_cases/snowflake_auth_methods.ipynb
  examples/expositional/use_cases/summarization_eval.ipynb
  examples/expositional/use_cases/summarization_hotspots.ipynb
  examples/quickstart/blocking_guardrails.ipynb
  examples/quickstart/custom_stream.ipynb
  examples/quickstart/groundtruth_dataset_persistence.ipynb
  examples/quickstart/groundtruth_evals.ipynb
  examples/quickstart/groundtruth_evals_for_retrieval_systems.ipynb
  examples/quickstart/human_feedback.ipynb
  examples/quickstart/quickstart.ipynb
  src/benchmark/trulens/benchmark/benchmark_frameworks/tru_benchmark_experiment.py
  src/trulens_eval/trulens_eval/tru_custom_app.py
  tests/e2e/test_context_variables.py
  tests/e2e/test_dummy.py
Labels: documentation, size:L

#1991 Progress towards otel quickstart readiness
  examples/experimental/test_otel_quickstart.ipynb
Labels: size:M

#1992 let dashboard pick up env variable instead of using flag
  examples/experimental/test_otel_quickstart.ipynb
  src/dashboard/trulens/dashboard/run.py
  src/trulens_eval/trulens_eval/tru_custom_app.py
Labels: size:S

#1995 [Minor] Update WITH_OTEL_TRACING to TRULENS_OTEL_TRACING
  examples/expositional/frameworks/crewai/surprise_trip/src/surprise_travel/main.py
Labels: size:XS

#1997 Create `Recording` when using a `App` as a context manager.
  src/core/trulens/core/otel/function_call_context_manager.py
  src/core/trulens/core/otel/instrument.py
  tests/unit/test_otel_legacy_compatibility.py
  tests/unit/test_otel_recording_contexts.py
Labels: size:M

#1996 [Minor] Allow trulens_trace to handle both record (pre-otel) and record id string (otel)
  src/dashboard/trulens/dashboard/streamlit.py
Labels: size:S

#1994 Update OTEL feedback score rendering and columns
  src/core/trulens/core/database/sqlalchemy.py
  tests/unit/test_otel_get_records_and_feedback.py
Labels: size:L

#2006 Have `recording.get` wait for record to show up in event table before giving to user.
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/core/session.py
Labels: size:S

#2005 Fix OpenAI provider in python 3.12+ to work with the changed @cached_property behavior
  src/core/trulens/core/utils/pyschema.py
  tests/unit/test_pyschema_safe_getattr.py
Labels: size:L

#2009 Don't require a main method.
  src/apps/langchain/trulens/apps/langchain/tru_chain.py
  src/apps/llamaindex/trulens/apps/llamaindex/tru_llama.py
  src/core/trulens/apps/app.py
  src/core/trulens/apps/basic.py
  src/core/trulens/core/app.py
  src/core/trulens/core/otel/function_call_context_manager.py
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/core/otel/utils.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  src/otel/semconv/trulens/otel/semconv/constants.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/test_otel_feedback_computation__test_feedback_computation.csv
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/test_otel_feedback_computation.py
  tests/unit/test_otel_get_records_and_feedback.py
  tests/unit/test_otel_instrument.py
  tests/unit/test_otel_legacy_compatibility.py
  tests/unit/test_otel_record_root.py
  tests/unit/test_otel_span.py
  tests/unit/test_otel_tru_chain.py
  tests/unit/test_otel_tru_custom.py
  tests/unit/test_otel_tru_llama.py
  tests/util/otel_test_case.py
  tests/utils.py
Labels: size:XL

#2013 UI updates to agent demo
  examples/expositional/use_cases/snowflake-ai-stack-agentic-eval/app.py
  examples/expositional/use_cases/snowflake-ai-stack-agentic-eval/src/agentic_evals.py
  examples/expositional/use_cases/snowflake-ai-stack-agentic-eval/src/graph.py
Labels: size:M

#2010 Fix TruLens nits
  src/dashboard/trulens/dashboard/Leaderboard.py
  src/dashboard/trulens/dashboard/run.py
  src/dashboard/trulens/dashboard/utils/dashboard_utils.py
  src/dashboard/trulens/dashboard/utils/records_utils.py
  src/dashboard/trulens/dashboard/utils/streamlit_compat.py
Labels: size:M

#2016 Display generated charts in the agent demo
  examples/expositional/use_cases/snowflake-ai-stack-agentic-eval/app.py
  examples/expositional/use_cases/snowflake-ai-stack-agentic-eval/src/graph.py
Labels: size:M

#2017 Remove "name" span attribute.
  src/core/trulens/core/feedback/selector.py
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/experimental/otel_tracing/core/exporter/utils.py
  src/feedback/trulens/feedback/computer.py
  tests/unit/static/golden/test_otel_feedback_computation__test_feedback_computation.csv
  tests/unit/static/golden/test_otel_tru_basic__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
  tests/unit/test_otel_selector.py
  tests/util/otel_test_case.py
Labels: size:M

#2027 fix app version search and advanced filters search
  src/dashboard/trulens/dashboard/utils/dashboard_utils.py
Labels: size:S

#2022 use on_context for ffs in quickstart
  examples/experimental/test_otel_quickstart.ipynb
Labels: size:S

#2029 Fix how OTEL mode is being checked
  src/core/trulens/core/database/sqlalchemy.py
  src/dashboard/trulens/dashboard/utils/dashboard_utils.py
Labels: size:S

#2023 Don't use session state api for metadata dropdown
  src/dashboard/trulens/dashboard/Leaderboard.py
Labels: size:S

#2031 Nit: Clean up and standardize otel tracing params
  examples/experimental/test_otel_quickstart.ipynb
  src/dashboard/trulens/dashboard/run.py
Labels: size:XS

#1999 Move app info to resource attributes.
  src/connectors/snowflake/trulens/connectors/snowflake/otel_exporter.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/experimental/otel_tracing/core/exporter/utils.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  src/feedback/trulens/feedback/computer.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/load/test_snowflake.py
  tests/unit/data/test_otel_spans/eval_root_span.json
  tests/unit/data/test_otel_spans/eval_span_1.json
  tests/unit/data/test_otel_spans/eval_span_2.json
  tests/unit/data/test_otel_spans/generation_span.json
  tests/unit/data/test_otel_spans/record_root_span.json
  tests/unit/data/test_otel_spans/retrieval_span.json
  tests/unit/data/test_otel_spans/template_record_root_span.json
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/test_otel_feedback_computation__test_feedback_computation.csv
  tests/unit/static/golden/test_otel_tru_basic__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
  tests/unit/test_otel_distributed.py
  tests/unit/test_otel_feedback_computation.py
  tests/unit/test_otel_get_records_and_feedback.py
  tests/unit/test_otel_recording_contexts.py
  tests/unit/test_otel_span_processor.py
Labels: size:L
