Repository truera/trulens, pull requests merged in 2025-08, with the labels that each got.

#2159 add trulens-apps-langgraph to optional requirements
  src/core/trulens/core/utils/requirements.optional.txt
Labels: dependencies, size:XS

#2158 [Snowflake] Live OTEL tracing with Snowflake Run
  examples/experimental/snowflake_live_tracing_with_run.ipynb
  src/connectors/snowflake/trulens/connectors/snowflake/dao/enums.py
  src/core/trulens/core/app.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: size:XL

#2161 custom attribute instrumentation + langgraph instrumentation docs
  docs/component_guides/instrumentation/index.md
  docs/component_guides/instrumentation/langgraph.md
  mkdocs.yml
Labels: documentation, size:L

#2165 Supply host to dashboard.
  src/dashboard/trulens/dashboard/run.py
  src/dashboard/trulens/dashboard/utils/dashboard_utils.py
Labels: size:XS

#2163 Dropped "trajectory" prefix from agent evals
  src/feedback/trulens/feedback/llm_provider.py
  src/feedback/trulens/feedback/prompts.py
  src/feedback/trulens/feedback/v2/feedback.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: documentation, size:XL

#2168 update notebooks to new gpa-naming for agent evals
  examples/expositional/frameworks/langchain/langgraph-multi-agent-snowflake-tools.ipynb
  examples/expositional/frameworks/langchain/langgraph_quickstart.ipynb
Labels: documentation, size:M

#2169 Add context for inline evals
  examples/expositional/frameworks/langchain/langgraph-multi-agent-snowflake-tools.ipynb
  src/apps/langgraph/trulens/apps/langgraph/inline_evaluations.py
  tests/unit/test_otel_inline_evaluations.py
Labels: size:L

#2170 TruLens v2.2.0
  poetry.lock
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/langgraph/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/hotspots/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#2171 Record page UI updates
  src/dashboard/trulens/dashboard/pages/Records.py
Labels: size:L

#2172 [Langgraph auto instrumentation] Improve instrumentation for Graph API
  .gitignore
  examples/expositional/frameworks/langchain/otel_tru_graph_example.ipynb
  src/apps/langgraph/trulens/apps/langgraph/tru_graph.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/unit/static/golden/test_otel_tru_graph_test_function_api_smoke.csv
  tests/unit/static/golden/test_otel_tru_graph_test_smoke.csv
  tests/unit/test_otel_tru_graph.py
Labels: size:XL

#2179 Use app versions instead of app ids when we can.
  src/core/trulens/core/database/base.py
  src/core/trulens/core/database/connector/base.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/session.py
  src/dashboard/trulens/dashboard/tabs/Compare.py
  src/dashboard/trulens/dashboard/tabs/Leaderboard.py
  src/dashboard/trulens/dashboard/tabs/Records.py
  src/dashboard/trulens/dashboard/utils/dashboard_utils.py
Labels: size:M

#2180 `TruLens` version `2.2.3`.
  poetry.lock
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/langgraph/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/hotspots/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/google/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#2184 Allow the use of your own lock for `compute_now`.
  src/core/trulens/core/utils/evaluator.py
Labels: size:S

#2186 Bugfix: Clean up syntax, hanging vars, bugs in LangGraph quickstart nb
  examples/expositional/frameworks/langchain/langgraph_quickstart.ipynb
Labels: size:S

#2187 silence get_group warning
  examples/quickstart/quickstart.ipynb
  src/feedback/trulens/feedback/computer.py
Labels: size:S

#2185 Add Tutorial for Multimodal Evaluation with Gemini (Text, Audio, Video)
  examples/expositional/models/google/gemini_multi_modal_evaluation.ipynb
Labels: documentation, size:XL

#2182 Allow main input specification for trace_with_run decorator (live tracing)
  examples/experimental/snowflake_live_tracing_with_run.ipynb
  src/core/trulens/core/app.py
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/experimental/otel_tracing/core/span.py
Labels: size:L

#2193 Fix groundedness support for bedrock.
  src/feedback/trulens/feedback/prompts.py
  src/providers/bedrock/trulens/providers/bedrock/provider.py
  src/trulens_eval/trulens_eval/feedback/prompts.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: size:L

#2195 default str handler for llm provider
  src/feedback/trulens/feedback/computer.py
  src/feedback/trulens/feedback/llm_provider.py
Labels: size:S
