Repository truera/trulens, pull requests merged in 2025-01, with the labels that each got.

#1705 Custom criteria for feedback
  docs/component_guides/evaluation/feedback_implementations/custom_feedback_functions.ipynb
  src/core/trulens/core/feedback/feedback.py
  src/core/trulens/core/schema/feedback.py
  src/feedback/trulens/feedback/llm_provider.py
  src/feedback/trulens/feedback/prompts.py
  src/feedback/trulens/feedback/v2/feedback.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: documentation, size:XXL

#1701 Update docs to use postgres + psycopg in order to avoid known issues with psycopg2
  docs/blog/posts/release_blog_1dot.md
  docs/component_guides/logging/where_to_log/index.md
  examples/expositional/use_cases/summarization_eval.ipynb
  tests/integration/test_database.py
Labels: documentation, size:S

#1709 Poetry < 2.0.0
  .azure_pipelines/templates/env-setup.yaml
  poetry.lock
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1710 Update groundedness criteria (with more optimized prompt)
  src/feedback/trulens/feedback/v2/feedback.py
Labels: size:XS

#1712 Update prpr example notebook to reflect latest Cortex provider API
  examples/quickstart/snowflake_ai_observability_example.ipynb
Labels: size:XS

#1706 Move `main_input`, `main_output`, and `_extract_content` out of app.py
  src/core/trulens/core/app.py
  src/core/trulens/core/utils/signature.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/test_signature_utils.py
Labels: size:XL

#1715 Remove / retire sql instrumentation in Cortex Endpoint
  src/providers/cortex/trulens/providers/cortex/endpoint.py
Labels: size:S

#1707 Move span-related validation + setting logic out of instrument.py
  examples/experimental/otel_exporter.ipynb
  src/core/trulens/core/app.py
  src/core/trulens/experimental/otel_tracing/core/instrument.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
  tests/unit/static/golden/test_otel_instrument__test_instrument_decorator.csv
  tests/unit/test_otel_instrument.py
  tests/unit/test_otel_span.py
Labels: size:XXL

#1714 Fix cortex notebooks using snowpark connector instead of session
  examples/expositional/models/snowflake_cortex/cortex_finetuning_experiments.ipynb
  src/benchmark/trulens/benchmark/benchmark_frameworks/meta_evaluation_examples.ipynb
Labels: size:S

#1713 Resolve performance issues when initializing a Thread/Threadpool
  src/core/trulens/core/utils/threading.py
Labels: size:XS

#1721 Update Cortex model cost table
  src/providers/cortex/trulens/providers/cortex/config/cortex_model_costs.json
  src/providers/cortex/trulens/providers/cortex/endpoint.py
Labels: size:S

#1718 TruLens 1.3.0
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/pyproject.toml
  src/core/pyproject.toml
  src/dashboard/pyproject.toml
  src/feedback/pyproject.toml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1719 Set default isolation level to AUTOCOMMIT for snowflake
  src/core/trulens/core/database/sqlalchemy.py
Labels: size:S

#1722 Update Snowflake quickstart from using arctic to more general Cortex LLMs
  examples/expositional/models/snowflake_cortex/cortex_llm_quickstart.ipynb
Labels: documentation, size:S

#1723 TruLens 1.3.1
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/pyproject.toml
  src/core/pyproject.toml
  src/dashboard/pyproject.toml
  src/feedback/pyproject.toml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1726 Handle pydantic upgrade that now handles `model_fields` as a `property` that can resolve to a `dict` when there's nothing.
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/utils.py
Labels: size:S

#1725 Fix type hint for fewshot prompt construction
  poetry.lock
  src/feedback/trulens/feedback/v2/feedback.py
Labels: size:S

#1728 TruLens 1.3.2
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/pyproject.toml
  src/core/pyproject.toml
  src/dashboard/pyproject.toml
  src/feedback/pyproject.toml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1729 1.3.2: update conda build recipes
  src/connectors/snowflake/meta.yaml
  src/core/meta.yaml
  src/dashboard/meta.yaml
  src/feedback/meta.yaml
  src/otel/semconv/meta.yaml
  src/providers/cortex/meta.yaml
Labels: size:S

#1720 Add protobuf-related utilities
  Makefile
  src/core/pyproject.toml
  src/core/trulens/core/utils/requirements.txt
  src/core/trulens/experimental/otel_tracing/_feature.py
  src/core/trulens/experimental/otel_tracing/core/exporter.py
  tests/unit/static/golden/test_otel_instrument__test_instrument_decorator.csv
  tests/unit/test_exporter.py
Labels: size:L

#1730 groundedness: update user prompt to be consistent with system prompt
  src/feedback/trulens/feedback/v2/feedback.py
Labels: size:XS

#1708 Enable exporting spans to snowflake stage if a `TruLensSnowflakeSpanExporter` is provided
  examples/experimental/otel_exporter.ipynb
  src/core/trulens/core/app.py
  src/core/trulens/core/session.py
  src/core/trulens/experimental/otel_tracing/core/app.py
  src/core/trulens/experimental/otel_tracing/core/exporter/connector.py
  src/core/trulens/experimental/otel_tracing/core/exporter/snowflake.py
  src/core/trulens/experimental/otel_tracing/core/exporter/utils.py
  src/core/trulens/experimental/otel_tracing/core/init.py
  src/core/trulens/experimental/otel_tracing/core/instrument.py
  src/core/trulens/experimental/otel_tracing/core/instruments.py
  src/core/trulens/experimental/otel_tracing/core/session.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
  tests/unit/static/golden/test_otel_instrument__test_instrument_decorator.csv
  tests/unit/test_exporter.py
  tests/unit/test_otel_instrument.py
Labels: size:XXL

#1727 Allow `TruChain`/`TruLlama`/`TruRails` to use OTEL spans.
  Makefile
  src/apps/langchain/trulens/apps/langchain/tru_chain.py
  src/apps/llamaindex/trulens/apps/llamaindex/tru_llama.py
  src/apps/nemo/trulens/apps/nemo/tru_rails.py
  src/core/trulens/apps/basic.py
  src/core/trulens/core/instruments.py
  src/core/trulens/experimental/otel_tracing/core/instrument.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  tests/test.py
  tests/unit/data/attention_is_all_you_need.pdf
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/test_otel_tru_chain.py
  tests/unit/test_otel_tru_custom.py
  tests/util/df_comparison.py
  tests/util/otel_app_test_case.py
Labels: size:XL

#1732 move `poetry-core` restrictions to az pipeline
  .azure_pipelines/templates/env-setup.yaml
  poetry.lock
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/pyproject.toml
  src/feedback/pyproject.toml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:S

#1738 Get `TruChain` main input/output working.
  src/apps/langchain/trulens/apps/langchain/tru_chain.py
  src/core/trulens/experimental/otel_tracing/core/instrument.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/test_otel_span.py
Labels: size:L

#1743 Get TruLlama working with OTEL.
  src/apps/langchain/trulens/apps/langchain/tru_chain.py
  src/apps/llamaindex/trulens/apps/llamaindex/tru_llama.py
  src/core/trulens/core/app.py
  src/core/trulens/experimental/otel_tracing/core/instrument.py
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
  tests/unit/test_otel_tru_chain.py
  tests/unit/test_otel_tru_custom.py
  tests/unit/test_otel_tru_llama.py
  tests/util/otel_app_test_case.py
Labels: size:L

#1744 Updated CoT prompt for context relevance (using the latest search prompt) and remove verb confidence prompt
  poetry.lock
  src/feedback/trulens/feedback/llm_provider.py
  src/feedback/trulens/feedback/prompts.py
  src/feedback/trulens/feedback/v2/feedback.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: size:XL

#1745 Write all args as kwargs to spans of "UNKNOWN" type without attributes declared.
  src/core/trulens/experimental/otel_tracing/core/instrument.py
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
  tests/util/df_comparison.py
Labels: size:M

#1740 Print local URL instead of network
  src/dashboard/trulens/dashboard/run.py
Labels: size:XS

#1746 Handle async functions with OTEL `@instrument` decorator.
  src/core/trulens/core/session.py
  src/core/trulens/experimental/otel_tracing/core/instrument.py
  src/core/trulens/experimental/otel_tracing/core/session.py
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/test_otel_instrument.py
  tests/unit/test_otel_tru_chain.py
  tests/unit/test_otel_tru_llama.py
Labels: size:L

#1747 Add multithreading test for OTEL.
  tests/unit/test_otel_multithreaded.py
Labels: size:M

#1741 TruLens 1.3.3
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1750 Validation for sis dashboard names
  src/connectors/snowflake/trulens/connectors/snowflake/utils/sis_dashboard_artifacts.py
Labels: size:S

#1751 update 1.3.3 hash for conda recipe
  src/connectors/snowflake/meta.yaml
  src/core/meta.yaml
  src/dashboard/meta.yaml
  src/feedback/meta.yaml
  src/otel/semconv/meta.yaml
  src/providers/cortex/meta.yaml
Labels: dependencies, size:S

#1748 Handle sync and async generators with the OTEL `@instrument` decorator.
  src/apps/langchain/trulens/apps/langchain/tru_chain.py
  src/core/trulens/experimental/otel_tracing/core/instrument.py
  tests/unit/test_otel_instrument.py
Labels: size:L

#1752 Require version of snowflake ml python >= 1.7.2
  src/connectors/snowflake/meta.yaml
  src/core/meta.yaml
  src/dashboard/meta.yaml
  src/feedback/meta.yaml
  src/otel/semconv/meta.yaml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
Labels: dependencies, size:S

#1753 Write returns for "UNKNOWN" spans.
  src/core/trulens/experimental/otel_tracing/core/instrument.py
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
  tests/unit/test_otel_tru_llama.py
  tests/util/df_comparison.py
  tests/util/otel_app_test_case.py
Labels: size:M

#1754 Set up basic E2E test.
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  src/core/trulens/core/app.py
  src/core/trulens/core/experimental/__init__.py
  src/core/trulens/core/instruments.py
  src/core/trulens/experimental/otel_tracing/core/exporter/snowflake.py
  src/core/trulens/experimental/otel_tracing/core/instrument.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/e2e/test_snowflake_event_table_exporter.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/test_otel_instrument__test_instrument_decorator.csv
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
  tests/unit/test_otel_instrument.py
  tests/unit/test_otel_multithreaded.py
  tests/util/otel_app_test_case.py
Labels: size:L

#1755 Handle sync functions that aren't generators but return a generator.
  src/core/trulens/experimental/otel_tracing/core/exporter/snowflake.py
  src/core/trulens/experimental/otel_tracing/core/instrument.py
  tests/unit/test_otel_instrument.py
Labels: size:L

#1756 Track OpenAI and Cortex costs in a similar manner to the non-OTEL world.
  src/core/trulens/apps/custom.py
  src/core/trulens/core/instruments.py
  src/core/trulens/core/session.py
  src/core/trulens/experimental/otel_tracing/core/instrument.py
  src/core/trulens/experimental/otel_tracing/core/session.py
  src/providers/cortex/trulens/providers/cortex/endpoint.py
  src/providers/openai/trulens/providers/openai/endpoint.py
  tests/e2e/test_otel_costs.py
  tests/e2e/test_snowflake_event_table_exporter.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
  tests/unit/test_otel_tru_llama.py
  tests/util/llama_index_mock_embedder.py
  tests/util/otel_app_test_case.py
Labels: size:XL

#1759 Remove some old OTEL logic.
  src/core/trulens/_mods.py
  src/core/trulens/core/app.py
  src/core/trulens/core/feedback/endpoint.py
  src/core/trulens/core/feedback/feedback.py
  src/core/trulens/core/schema/base.py
  src/core/trulens/core/schema/record.py
  src/core/trulens/core/schema/select.py
  src/core/trulens/experimental/otel_tracing/core/feedback/endpoint.py
  src/core/trulens/experimental/otel_tracing/core/otel.py
  src/core/trulens/experimental/otel_tracing/core/trace.py
  src/feedback/trulens/feedback/dummy/endpoint.py
  src/providers/bedrock/trulens/providers/bedrock/endpoint.py
  src/providers/huggingface/trulens/providers/huggingface/endpoint.py
  src/providers/litellm/trulens/providers/litellm/endpoint.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: size:XXL

#1761 Have llama-index emit context-retrieval spans.
  src/apps/llamaindex/trulens/apps/llamaindex/tru_llama.py
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
Labels: size:M

#1762 Change base scope from "ai_observability" to "ai.observability". Also…
  src/apps/llamaindex/trulens/apps/llamaindex/tru_llama.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/e2e/test_otel_costs.py
  tests/e2e/test_snowflake_event_table_exporter.py
  tests/unit/static/golden/test_otel_instrument__test_instrument_decorator.csv
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
  tests/unit/test_otel_instrument.py
  tests/unit/test_otel_multithreaded.py
Labels: size:M

#1764 Test guardrails with OTEL setup.
  tests/unit/test_otel_guardrail.py
Labels: size:M

#1766 Make OTEL flow for users more natural by only having to set an environment variable and importing from non-experimental code.
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  src/connectors/snowflake/trulens/connectors/snowflake/otel_exporter.py
  src/core/trulens/core/app.py
  src/core/trulens/core/experimental/__init__.py
  src/core/trulens/core/instruments.py
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/core/session.py
  src/core/trulens/experimental/otel_tracing/core/session.py
  tests/e2e/test_otel_costs.py
  tests/e2e/test_snowflake_event_table_exporter.py
  tests/unit/test_otel_guardrail.py
  tests/unit/test_otel_instrument.py
  tests/unit/test_otel_multithreaded.py
  tests/unit/test_otel_span.py
  tests/unit/test_otel_tru_chain.py
  tests/unit/test_otel_tru_custom.py
  tests/util/otel_app_test_case.py
Labels: size:L

#1768 Add in Snowflake OTEL e2e tests for tru_chain and tru_llama.
  examples/experimental/otel_exporter.ipynb
  src/connectors/snowflake/trulens/connectors/snowflake/otel_exporter.py
  tests/e2e/test_snowflake_event_table_exporter.py
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/test_otel_tru_custom.py
Labels: size:L

#1760 clean up old benchmark notebooks
  docs/component_guides/evaluation_benchmarks/answer_relevance_benchmark_small.ipynb
  docs/component_guides/evaluation_benchmarks/comprehensiveness_benchmark.ipynb
  docs/component_guides/evaluation_benchmarks/context_relevance_benchmark.ipynb
  docs/component_guides/evaluation_benchmarks/context_relevance_benchmark_calibration.ipynb
  docs/component_guides/evaluation_benchmarks/context_relevance_benchmark_small.ipynb
  docs/component_guides/evaluation_benchmarks/groundedness_benchmark.ipynb
  docs/component_guides/evaluation_benchmarks/index.md
  src/benchmark/trulens/benchmark/answer_relevance_benchmark_small.ipynb
  src/benchmark/trulens/benchmark/comprehensiveness_benchmark.ipynb
  src/benchmark/trulens/benchmark/context_relevance_benchmark.ipynb
  src/benchmark/trulens/benchmark/context_relevance_benchmark_calibration.ipynb
  src/benchmark/trulens/benchmark/context_relevance_benchmark_small.ipynb
  src/benchmark/trulens/benchmark/groundedness_benchmark_snowflake_arctic.ipynb
Labels: documentation, size:XXL
