Repository truera/trulens, pull requests merged in 2025-03, with the labels that each got.

#1854 Create load test.
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/load/data/test_snowflake_load_test_app_data.csv
  tests/load/test_snowflake.py
  tests/unit/static/golden/test_otel_feedback_computation__test_feedback_computation.csv
  tests/util/mock_otel_feedback_computation.py
  tests/util/snowflake_test_case.py
Labels: size:L

#1849 Update Snowflake OTEL E2E tests to use Snowflake runs.
  examples/experimental/otel_exporter.ipynb
  tests/e2e/data/staged_packages_with_otel.ipynb
  tests/e2e/test_otel_costs.py
  tests/e2e/test_snowflake_event_table_exporter.py
Labels: size:L

#1856 SDK - app/ snowflake object name case resolution and fixing span attributes validation in dataset_spec
  src/connectors/snowflake/trulens/connectors/snowflake/dao/external_agent.py
  src/connectors/snowflake/trulens/connectors/snowflake/dao/run.py
  src/connectors/snowflake/trulens/connectors/snowflake/otel_exporter.py
  src/core/trulens/core/run.py
  tests/e2e/test_snowflake_event_table_exporter.py
  tests/load/test_snowflake.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/test_snowflake_external_agent_dao.py
  tests/unit/test_snowflake_run_dao.py
Labels: size:L

#1858 Make CUJ work with local LLM
  examples/experimental/pupr_e2e_cuj.ipynb
Labels: size:S

#1860 Remove mention of cortex guard tokens.
  src/otel/semconv/trulens/otel/semconv/trace.py
  src/providers/cortex/trulens/providers/cortex/endpoint.py
Labels: size:XS

#1864 Call feedbacks with feedback.__call__
  src/core/trulens/core/feedback/feedback.py
Labels: size:XS

#1863 Update latest cortex cost table
  src/providers/cortex/trulens/providers/cortex/config/cortex_model_costs.json
Labels: size:XS

#1866 Run compute metric returning statuses instead of async job
  examples/experimental/otel_exporter.ipynb
  src/connectors/snowflake/trulens/connectors/snowflake/dao/external_agent.py
  src/core/trulens/core/run.py
Labels: size:S

#1867 TruLens 1.4.5
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/hotspots/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1871 bump otel version
  src/core/meta.yaml
  src/core/pyproject.toml
Labels: dependencies, size:S

#1872 Sync conda deps with pyproject deps
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/hotspots/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
Labels: dependencies, size:M

#1870 Fix MySQL setup
  src/core/trulens/core/database/migrations/versions/4_set_ff_id_not_null.py
  src/core/trulens/core/database/migrations/versions/7_app_name_version_not_null.py
Labels: size:XS

#1868 SDK: Fix run metadata field masks logic and expose description and label as optional and update-able fields
  src/connectors/snowflake/trulens/connectors/snowflake/dao/external_agent.py
  src/connectors/snowflake/trulens/connectors/snowflake/dao/run.py
  src/core/trulens/core/run.py
  tests/unit/test_snowflake_run_dao.py
Labels: size:L

#1874 TruLens 1.4.6
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/hotspots/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1875 Fix some e2e test issues.
  poetry.lock
  src/providers/openai/trulens/providers/openai/endpoint.py
  tests/e2e/test_tru_chain.py
Labels: dependencies, size:M

#1876 Add quickstart notebook for PuPr
  examples/quickstart/RAG_EVALUATION.ipynb
Labels: size:L

#1877 Rename PuPr quickstart path to be lowercase
  examples/quickstart/rag_evaluation.ipynb
Labels: size:XS

#1878 [SNOW-1967293] Fix cortex cost tracking - only tallying requests at the end of the streamed SSE
  examples/expositional/models/snowflake_cortex/cortex_llm_quickstart.ipynb
  src/providers/cortex/trulens/providers/cortex/endpoint.py
  src/providers/cortex/trulens/providers/cortex/provider.py
Labels: size:M

#1879 [SNOW-1983345] SDK: app deletion and delete current version
  src/connectors/snowflake/trulens/connectors/snowflake/dao/external_agent.py
  src/core/trulens/core/app.py
  tests/e2e/test_snowflake_agents_and_runs.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
  tests/unit/test_snowflake_external_agent_dao.py
Labels: size:L

#1880 [SNOW-1956008] SDK: implement run.cancel() and cancellation logic
  src/core/trulens/core/run.py
  tests/e2e/test_snowflake_agents_and_runs.py
  tests/unit/static/golden/api.trulens.3.11.yaml
Labels: size:L

#1882 TruLens 1.4.7
  pyproject.toml
  src/apps/langchain/meta.yaml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/hotspots/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1881 Fix `tests/e2e/test_providers.py::TestProviders::test_llmcompletion_calibration`.
  src/feedback/trulens/feedback/llm_provider.py
  src/feedback/trulens/feedback/v2/feedback.py
  tests/e2e/test_providers.py
  tests/unit/static/golden/api.trulens.3.11.yaml
Labels: size:L

#1886 Fix azure openai e2e tests
  tests/e2e/test_endpoints.py
Labels: size:S

#1883 Fix `test_endpoints.py`.
  src/core/trulens/core/schema/base.py
  src/feedback/trulens/feedback/dummy/endpoint.py
  src/providers/huggingface/trulens/providers/huggingface/provider.py
  tests/e2e/test_endpoints.py
  tests/e2e/test_providers.py
Labels: size:S

#1887 Fix litellm e2e tests with Azure Openai
  src/providers/litellm/trulens/providers/litellm/provider.py
  tests/e2e/test_endpoints.py
Labels: size:M

#1891 Add documentation on how to run single tests.
  DEVELOPMENT.md
Labels: documentation, size:S
