Repository truera/trulens, pull requests merged in 2025-09, with the labels that each got.

#2202 style: cleanup bedrock provider imports
  src/providers/bedrock/trulens/providers/bedrock/endpoint.py
  src/providers/bedrock/trulens/providers/bedrock/provider.py
Labels: size:S

#2115 Add Litellm structured outputs
  src/providers/litellm/trulens/providers/litellm/provider.py
Labels: size:XS

#2215 Update gitignore to ignore generated .csv files in experimental folder
  .gitignore
Labels: size:XS

#2217 Structured output parsing take 2
  src/feedback/trulens/feedback/llm_provider.py
Labels: size:L

#2228 Update model costs in cortex_model_costs.json
  src/providers/cortex/trulens/providers/cortex/config/cortex_model_costs.json
Labels: size:S

#2229 Fix typo in model cost JSON key
  src/providers/cortex/trulens/providers/cortex/config/cortex_model_costs.json
Labels: size:XS

#2232 [Snowflake] web search agent example with snowflake ai obs
  examples/experimental/web-search-agent-evaluation-snowflake-evals.ipynb
Labels: size:XXL

#2240 Fix Cortex cost/usage tracking with latest REST API
  src/providers/cortex/trulens/providers/cortex/endpoint.py
Labels: size:S
