Repository truera/trulens, pull requests merged in 2025-06, with the labels that each got.

#2028 set otel os env var from streamlit flag
  src/dashboard/trulens/dashboard/utils/dashboard_utils.py
Labels: size:S

#2014 Add explanations and fix groundedness calls in streamlit
  src/core/trulens/core/database/sqlalchemy.py
  src/dashboard/trulens/dashboard/display.py
  src/dashboard/trulens/dashboard/streamlit.py
  src/dashboard/trulens/dashboard/utils/records_utils.py
Labels: size:M

#2033 Rename `call_feedback_function_per_entry_in_list` to `collect_list` and change polarity of the boolean.
  examples/experimental/test_otel_quickstart.ipynb
  src/core/trulens/core/feedback/feedback.py
  src/core/trulens/core/feedback/feedback_function_input.py
  src/core/trulens/core/feedback/selector.py
  src/feedback/trulens/feedback/computer.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/test_otel_feedback_computation.py
  tests/unit/test_otel_rag_triad.py
Labels: size:M

#2034 Fix some e2e tests.
  tests/e2e/test_context_variables.py
  tests/e2e/test_snowflake_event_table_exporter.py
Labels: size:M

#2026 Prepare agent for demo
  examples/expositional/use_cases/snowflake-ai-stack-agentic-eval/app.py
  examples/expositional/use_cases/snowflake-ai-stack-agentic-eval/run_app.sh
  examples/expositional/use_cases/snowflake-ai-stack-agentic-eval/run_app1.sh
  examples/expositional/use_cases/snowflake-ai-stack-agentic-eval/run_app2.sh
  examples/expositional/use_cases/snowflake-ai-stack-agentic-eval/src/agentic_evals.py
  examples/expositional/use_cases/snowflake-ai-stack-agentic-eval/src/graph.py
Labels: size:L

#2038 Fail if trying to run a pre-OTel only function in OTel mode.
  src/core/trulens/core/app.py
  src/core/trulens/core/database/connector/base.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/session.py
Labels: size:M

#2044 Clean up `TruSession` before tests as previous tests can interfere with each other.
  tests/test.py
  tests/util/otel_test_case.py
  tests/util/snowflake_test_case.py
Labels: size:M

#2035 Summit agentic eval demo - streamlit feedback pill and result display
  docs/component_guides/guardrails/input_blocking_guardrails.png
  examples/expositional/use_cases/snowflake-ai-stack-agentic-eval/app.py
  examples/expositional/use_cases/snowflake-ai-stack-agentic-eval/src/agentic_evals.py
  src/dashboard/trulens/dashboard/streamlit.py
  src/dashboard/trulens/dashboard/utils/records_utils.py
Labels: size:L

#2037 OTel Blog + Examples for pre-release
  docs/blog/assets/trulens_otel/langgraph_trace.png
  docs/blog/posts/trulens_otel.md
  docs/overrides/home.html
  examples/experimental/otel/groundtruth_evals_otel.ipynb
  examples/experimental/otel/langchain_quickstart_otel.ipynb
  examples/experimental/otel/langgraph_quickstart_otel.ipynb
  examples/experimental/otel/llama_index_quickstart_otel.ipynb
  examples/experimental/otel/quickstart_otel.ipynb
  mkdocs.yml
Labels: size:XXL

#2046 blog link fix
  docs/blog/posts/trulens_otel.md
Labels: documentation, size:XS

#2048 Update tooltips for cost and latency based on delta value
  src/dashboard/trulens/dashboard/pages/Records.py
Labels: size:XS

#2050 Safely drop columns as sometimes the "output" column isn't there.
  src/dashboard/trulens/dashboard/utils/records_utils.py
Labels: size:XS

#2052 TruLens 1.5.1.
  poetry.lock
  pyproject.toml
  src/apps/langchain/meta.yaml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/hotspots/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#2018 Call `model_fields` and `model_computed_fields` from the class and not the instance.
  src/core/trulens/core/app.py
  src/core/trulens/core/instruments.py
  src/core/trulens/core/schema/base.py
  src/core/trulens/core/utils/json.py
  src/core/trulens/core/utils/serial.py
  tests/test.py
Labels: size:S

#2054 [Nit] Sans serif font fix
  src/dashboard/trulens/dashboard/run.py
Labels: size:XS

#2057 Add initial UI tests for Streamlit components, interactions, and Leaderboard
  tests/unit/streamlit/README.md
  tests/unit/streamlit/test_streamlit_components.py
  tests/unit/streamlit/test_streamlit_interactions.py
  tests/unit/streamlit/test_streamlit_leaderboard.py
  tests/unit/streamlit/test_streamlit_utils.py
Labels: size:XXL

#2065 Update feat/bug assignee to Nikhil for triage
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size:S

#2066 [Bugfix] Update dedup logic for feedback calls to gracefully handle both OTel and non-OTel spans
  src/core/trulens/core/database/sqlalchemy.py
  src/dashboard/trulens/dashboard/utils/records_utils.py
  tests/unit/test_records_utils.py
Labels: size:XL

#2070 Add makefile recipe to install all subpackages
  Makefile
Labels: size:XS

#2069 Support python3.12 for snowflake-adjacent packages
  examples/__init__.py
  poetry.lock
  pyproject.toml
  src/connectors/snowflake/pyproject.toml
  src/dashboard/pyproject.toml
  src/hotspots/poetry.lock
  src/providers/cortex/pyproject.toml
Labels: dependencies, size:S

#2068 Remove deprecated trulens-core extras
  poetry.lock
  pyproject.toml
Labels: dependencies, size:XS

#2071 TruLens 1.5.2
  poetry.lock
  pyproject.toml
  src/apps/langchain/meta.yaml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/hotspots/poetry.lock
  src/hotspots/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#2078 [Docs] Improve and standardize language for instrumentation-specific docs, fix grammar and spelling errors
  docs/component_guides/instrumentation/index.md
  docs/component_guides/instrumentation/langchain.md
  docs/component_guides/instrumentation/llama_index.md
  docs/component_guides/instrumentation/nemo.md
Labels: documentation, size:M

#2079 [Docs] Fix code examples, update grammar, spelling for logging-specific docs
  docs/component_guides/logging/logging.ipynb
  docs/component_guides/logging/where_to_log/index.md
  docs/component_guides/logging/where_to_log/log_in_snowflake.md
Labels: documentation, size:M

#1969 [SDK][Major Version Change] SDK (Snowflake) uses LLM orchestration layer
  src/connectors/snowflake/trulens/connectors/snowflake/dao/run.py
  src/connectors/snowflake/trulens/connectors/snowflake/otel_exporter.py
  src/core/trulens/core/app.py
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/core/run.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  src/otel/semconv/trulens/otel/semconv/trace.py
Labels: size:L, lgtm

#2082 Update instrumentation component guides for OTEL
  docs/component_guides/instrumentation/index.md
  docs/component_guides/instrumentation/langchain.md
  docs/component_guides/instrumentation/llama_index.md
  docs/component_guides/instrumentation/nemo.md
Labels: documentation, size:L

#2084 remove outdated eval benchmarks from nav
  mkdocs.yml
Labels: documentation, size:XS

#2083 update selecting components page for OTel
  docs/component_guides/evaluation/feedback_selectors/selecting_components.md
Labels: documentation, size:L

#2072 [Docs] Fix grammatical and spelling errors and standardize language for evaluation-specific component guides and notebooks
  docs/component_guides/evaluation/feedback_aggregation.md
  docs/component_guides/evaluation/feedback_anatomy.md
  docs/component_guides/evaluation/feedback_implementations/custom_feedback_functions.ipynb
  docs/component_guides/evaluation/feedback_implementations/index.md
  docs/component_guides/evaluation/feedback_implementations/stock.md
  docs/component_guides/evaluation/feedback_providers.md
  docs/component_guides/evaluation/feedback_selectors/index.md
  docs/component_guides/evaluation/feedback_selectors/selecting_components.md
  docs/component_guides/evaluation/feedback_selectors/selector_shortcuts.md
  docs/component_guides/evaluation/generate_test_cases.md
  docs/component_guides/evaluation/index.md
  docs/component_guides/evaluation/running_feedback_functions/existing_data.md
  docs/component_guides/evaluation/running_feedback_functions/with_app.md
Labels: documentation, size:L

#2088 Add DeepWiki badge to README
  README.md
Labels: documentation, size:XS

#2086 [Snowflake] Add test dataset notebook for LLM GA work with orchestration layer
  examples/experimental/snowflake_pupr_to_ga_test.ipynb
Labels: size:L, lgtm

#2095 Fix issues with using JSON in Snowflake regular tables.
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  src/core/trulens/core/app.py
  src/core/trulens/core/database/base.py
  src/core/trulens/core/database/connector/base.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/utils/evaluator.py
  src/core/trulens/experimental/otel_tracing/core/session.py
  tests/e2e/test_otel_snowflake_regular_tables.py
  tests/unit/test_otel_connector.py
  tests/util/otel_test_case.py
Labels: size:L

#2091 [Snowflake] [major version release] Remove deprecated SDK orchestration code.
  src/connectors/snowflake/trulens/connectors/snowflake/dao/run.py
  tests/unit/test_snowflake_run_dao.py
  tests/unit/test_snowflake_run_status.py
Labels: size:XL

#2096 Allow ignoring None values.
  src/core/trulens/core/feedback/selector.py
  src/core/trulens/experimental/otel_tracing/core/exporter/utils.py
  src/feedback/trulens/feedback/computer.py
  tests/unit/static/golden/api.trulens.3.11.yaml
Labels: size:M

#2097 Fix optionals for criteria ranges
  src/feedback/trulens/feedback/llm_provider.py
Labels: size:L

#2100 [Experimental] Add WIP notebook to directly compute feedbacks on OTel spans
  examples/experimental/otel/compute_direct_feedbacks.ipynb
Labels: size:L

#2099 Enable OTel event queries with app_version
  src/core/trulens/core/database/base.py
  src/core/trulens/core/database/connector/base.py
  src/core/trulens/core/database/sqlalchemy.py
  src/core/trulens/core/session.py
  tests/unit/test_otel_get_records_and_feedback.py
Labels: size:L

#2098 Add structured outputs to feedback providers
  examples/experimental/otel/compute_direct_feedbacks.ipynb
  src/feedback/trulens/feedback/dummy/provider.py
  src/feedback/trulens/feedback/llm_provider.py
  src/feedback/trulens/feedback/output_schemas.py
  src/providers/bedrock/trulens/providers/bedrock/provider.py
  src/providers/cortex/trulens/providers/cortex/endpoint.py
  src/providers/cortex/trulens/providers/cortex/provider.py
  src/providers/langchain/trulens/providers/langchain/provider.py
  src/providers/litellm/trulens/providers/litellm/provider.py
  src/providers/openai/trulens/providers/openai/provider.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: size:L

#2102 Validate openai models support for structured output
  src/providers/openai/trulens/providers/openai/provider.py
  tests/e2e/test_providers.py
Labels: size:M
