Repository truera/trulens, pull requests merged in 2025-04, with the labels that each got.

#1869 SDK: Add compute metric check to avoid re-computation and refactor run status flow
  src/connectors/snowflake/trulens/connectors/snowflake/dao/run.py
  src/core/trulens/core/run.py
  tests/unit/test_snowflake_run_status.py
Labels: size:XXL

#1894 [Docs] Fix minor typos
  docs/getting_started/core_concepts/feedback_functions.md
  docs/getting_started/core_concepts/honest_harmless_helpful_evals.md
  docs/getting_started/core_concepts/index.md
  docs/getting_started/core_concepts/rag_triad.md
  examples/expositional/use_cases/iterate_on_rag/3_harmless_eval.ipynb
  examples/expositional/use_cases/iterate_on_rag/4_harmless_rag.ipynb
  examples/expositional/use_cases/iterate_on_rag/5_helpful_eval.ipynb
Labels: documentation, size:M

#1885 SDK: Fix logic for ingestion E2E timeout
  src/connectors/snowflake/trulens/connectors/snowflake/dao/run.py
  src/connectors/snowflake/trulens/connectors/snowflake/dao/sql_utils.py
  src/connectors/snowflake/trulens/connectors/snowflake/otel_exporter.py
  src/core/trulens/core/run.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/test_snowflake_run_dao.py
Labels: size:L

#1898 Update poetry to trulens 1.4.8
  poetry.lock
Labels: dependencies, size:XS

#1895 Doc string spelling
  src/feedback/trulens/feedback/groundtruth.py
Labels: documentation, size:XS

#1901 [SNOW-2031737] Refresh symbolic links for notebooks to test
  tests/docs_notebooks/notebooks_to_test/langchain_faiss_example.ipynb
  tests/docs_notebooks/notebooks_to_test/langchain_instrumentation.ipynb
  tests/docs_notebooks/notebooks_to_test/llama_index_instrumentation.ipynb
  tests/docs_notebooks/notebooks_to_test/logging.ipynb
  tests/docs_notebooks/notebooks_to_test/trulens_instrumentation.ipynb
Labels: size:XS

#1904 [SNOW-2005231, SNOW-2033054, SNOW-2033730] Deflake E2E pipeline issues
  tests/Jenkinsfile
Labels: size:M

#1906 TruLens 1.4.9
  pyproject.toml
  src/apps/langchain/meta.yaml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/hotspots/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1896 Evaluate Weaviate Query Agents
  examples/expositional/vector_stores/weaviate/weaviate_query_agent.ipynb
Labels: size:L

#1907 [SNOW-2005227, SNOW-2037060] Add HuggingFace pytest annotation and deflake E2E test issues
  DEVELOPMENT.md
  Makefile
  conftest.py
  pyproject.toml
  src/providers/huggingface/trulens/providers/huggingface/endpoint.py
  src/providers/huggingface/trulens/providers/huggingface/provider.py
  tests/Jenkinsfile
  tests/e2e/test_endpoints.py
  tests/e2e/test_providers.py
  tests/e2e/test_tru_llama.py
Labels: size:L

#1908 move notebooks that shouldn't be in quickstarts to experimental
  examples/experimental/load_virtual_groundtruth.ipynb
  examples/experimental/snowflake_cortex_rag_evaluation.ipynb
  examples/quickstart/snowflake_ai_observability_example.ipynb
Labels: size:XS

#1909 [SNOW-2005236]: Removing outdated/obsolete notebooks
  examples/expositional/frameworks/canopy/canopy_quickstart.ipynb
  examples/expositional/frameworks/cortexchat/cortex_chat_quickstart.ipynb
  examples/expositional/frameworks/nemoguardrails/.gitignore
  examples/expositional/frameworks/nemoguardrails/nemoguardrails_feedback_action_example.ipynb
  examples/expositional/frameworks/nemoguardrails/nemoguardrails_trurails_example.ipynb
  examples/quickstart/prototype_evals.ipynb
Labels: size:XXL

#1910 Fix `test_dummy.py` and `test_session.py` E2E tests.
  tests/Jenkinsfile
  tests/e2e/golden/dummy.json
  tests/e2e/test_tru_session.py
Labels: size:S

#1912 snowflake ai stack
  examples/expositional/use_cases/snowflake-ai-stack/README.md
  examples/expositional/use_cases/snowflake-ai-stack/app.py
  examples/expositional/use_cases/snowflake-ai-stack/data.txt
  examples/expositional/use_cases/snowflake-ai-stack/notebook_example.ipynb
  examples/expositional/use_cases/snowflake-ai-stack/requirements.txt
  examples/expositional/use_cases/snowflake-ai-stack/run_app1.sh
  examples/expositional/use_cases/snowflake-ai-stack/run_app2_filters.sh
  examples/expositional/use_cases/snowflake-ai-stack/src/__init__.py
  examples/expositional/use_cases/snowflake-ai-stack/src/generation.py
  examples/expositional/use_cases/snowflake-ai-stack/src/observability.py
  examples/expositional/use_cases/snowflake-ai-stack/src/rag.py
  examples/expositional/use_cases/snowflake-ai-stack/src/retrieval.py
Labels: size:XL

#1913 [E2E] Revert temporary change for e2e testing
  tests/Jenkinsfile
Labels: size:XS

#1914 gpt-4.1
  examples/quickstart/blocking_guardrails.ipynb
  examples/quickstart/langchain_quickstart.ipynb
  examples/quickstart/llama_index_quickstart.ipynb
  examples/quickstart/quickstart.ipynb
Labels: size:S

#1915 Update contribution guide
  docs/contributing/index.md
Labels: documentation, size:S

#1917 Restore rag evaluation quickstart notebook
  examples/experimental/snowflake_cortex_rag_evaluation.ipynb
  examples/quickstart/rag_evaluation.ipynb
Labels: size:XL

#1916 Fix `test_serial.py`.
  tests/e2e/golden/customapp.json
  tests/e2e/golden/customapp_context_relevance.def.json
  tests/e2e/golden/customapp_context_relevance.result.json
  tests/e2e/golden/customapp_language_match.def.json
  tests/e2e/golden/customapp_language_match.result.json
  tests/e2e/golden/customapp_record.json
Labels: size:M

#1905 Set up algorithm for feedback selectors 2.0.
  src/feedback/trulens/feedback/computer.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/test_otel_feedback_computation.py
Labels: size:XL

#1919 Nit: Flakiness fix for test_tru_llama
  tests/e2e/test_tru_llama.py
Labels: size:XS

#1922 Add function name to span attribute `ai.observability.call.function`.
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  tests/unit/static/golden/test_otel_feedback_computation__test_feedback_computation.csv
  tests/unit/static/golden/test_otel_tru_basic__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
Labels: size:S

#1921 Fix "future" issue on E2E tests.
  tests/e2e/test_serial.py
Labels: size:XS

#1923 Add experimental langgraph multi-agent demo
  examples/experimental/langgraph_saved_images/G7_GDP_Growth_Rates.png
  examples/experimental/langgraph_saved_images/UK_GDP_2018_2023.png
  examples/experimental/langgraph_saved_images/UK_GDP_Last_5_Years.png
  examples/experimental/langgraph_saved_images/g7_gdp_growth_2000_2024.png
  examples/experimental/langgraph_saved_images/g7_gdp_growth_2003_2023.png
  examples/experimental/langgraph_saved_images/gdp_growth_g7_countries.png
  examples/experimental/langgraph_saved_images/income_inequality_gini_index_2023.png
  examples/experimental/langgraph_saved_images/magnificent_7_stock_prices.png
  examples/experimental/langgraph_saved_images/magnificent_7_stocks.png
  examples/experimental/langgraph_saved_images/stock_prices_comparison.png
  examples/experimental/langgraph_saved_images/top_5_income_inequality_2023.png
  examples/experimental/langgraph_saved_images/top_income_inequality_countries.png
  examples/experimental/langgraph_saved_images/uber_lyft_2023_comparison.png
  examples/experimental/langgraph_saved_images/uber_lyft_october_2023.png
  examples/experimental/langgraph_saved_images/uk_gdp_2018_2022.png
  examples/experimental/langgraph_saved_images/uk_gdp_2019_2023.png
  examples/experimental/langgraph_saved_images/uk_gdp_5_years.png
  examples/experimental/langgraph_saved_images/uk_gdp_chart.png
  examples/experimental/langgraph_saved_images/uk_gdp_line_chart.png
  examples/experimental/multi-agent-collaboration.ipynb
Labels: size:XS

#1925 Add dashboard GIFs to weaviate query agents notebook
  examples/expositional/vector_stores/weaviate/assets/trulens_weaviate_identify_issues.gif
  examples/expositional/vector_stores/weaviate/assets/trulens_weaviate_validate.gif
  examples/expositional/vector_stores/weaviate/weaviate_query_agent.ipynb
Labels: documentation, size:M

#1926 Track langgraph saved images with Git LFS, fix formatting nit
  examples/experimental/langgraph_saved_images/G7_GDP_Growth_Rates.png
  examples/experimental/langgraph_saved_images/UK_GDP_2018_2023.png
  examples/experimental/langgraph_saved_images/UK_GDP_Last_5_Years.png
  examples/experimental/langgraph_saved_images/g7_gdp_growth_2000_2024.png
  examples/experimental/langgraph_saved_images/g7_gdp_growth_2003_2023.png
  examples/experimental/langgraph_saved_images/gdp_growth_g7_countries.png
  examples/experimental/langgraph_saved_images/income_inequality_gini_index_2023.png
  examples/experimental/langgraph_saved_images/magnificent_7_stock_prices.png
  examples/experimental/langgraph_saved_images/magnificent_7_stocks.png
  examples/experimental/langgraph_saved_images/stock_prices_comparison.png
  examples/experimental/langgraph_saved_images/top_5_income_inequality_2023.png
  examples/experimental/langgraph_saved_images/top_income_inequality_countries.png
  examples/experimental/langgraph_saved_images/uber_lyft_2023_comparison.png
  examples/experimental/langgraph_saved_images/uber_lyft_october_2023.png
  examples/experimental/langgraph_saved_images/uk_gdp_2018_2022.png
  examples/experimental/langgraph_saved_images/uk_gdp_2019_2023.png
  examples/experimental/langgraph_saved_images/uk_gdp_5_years.png
  examples/experimental/langgraph_saved_images/uk_gdp_chart.png
  examples/experimental/langgraph_saved_images/uk_gdp_line_chart.png
  examples/experimental/multi-agent-collaboration.ipynb
Labels: size:XS

#1930 Unlock poetry > 2.0
  poetry.lock
  pyproject.toml
Labels: dependencies, size:XS

#1931 Small E2E test fixes.
  examples/experimental/otel_exporter.ipynb
  tests/e2e/test_otel_costs.py
Labels: size:XS

#1932 Allow enabling/disabling OTEL instrumentation.
  Makefile
  src/core/trulens/core/otel/instrument.py
  tests/Jenkinsfile
  tests/e2e/test_snowflake_agents_and_runs.py
  tests/e2e/test_snowflake_event_table_exporter.py
  tests/load/test_snowflake.py
  tests/unit/test_otel_instrument.py
  tests/util/otel_test_case.py
Labels: size:L

#1933 Fix `test_tru_llama.py` tests.
  src/core/trulens/core/instruments.py
Labels: size:S

#1935 Clear dummy stack after `test_dummy.py` so that it doesn't affect other tests.
  Makefile
  examples/dev/dummy_app/tool.py
  tests/Jenkinsfile
  tests/e2e/test_dummy.py
Labels: size:S

#1936 add backlinks to weaviate
  examples/expositional/vector_stores/weaviate/weaviate_query_agent.ipynb
Labels: documentation, size:S

#1938 Allow feedback `Selector` for OTEL selectors to have more options.
  src/feedback/trulens/feedback/computer.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/test_otel_feedback_computation.py
Labels: size:L

#1942 Add missing dependency in requirements.txt (chromadb) for snowflake ai stack demo
  examples/expositional/use_cases/snowflake-ai-stack/requirements.txt
Labels: dependencies, size:XS

#1943 Update `CALL` semantic convention.
  src/otel/semconv/trulens/otel/semconv/trace.py
Labels: size:M

#1941 [SNOW-2005237] Fix notebook E2E tests
  .gitignore
  Makefile
  examples/expositional/vector_stores/faiss/langchain_faiss_example.ipynb
  examples/quickstart/groundtruth_evals.ipynb
  examples/quickstart/human_feedback.ipynb
  examples/quickstart/langchain_quickstart.ipynb
  examples/quickstart/llama_index_quickstart.ipynb
  examples/quickstart/quickstart.ipynb
  poetry.lock
  release_dbs/1.4.9/default.sqlite
  src/apps/llamaindex/trulens/apps/llamaindex/guardrails.py
  src/core/trulens/core/database/legacy/migration.py
  src/core/trulens/core/utils/python.py
  tests/Jenkinsfile
  tests/docs_notebooks/notebooks_to_test/prototype_evals.ipynb
  tests/docs_notebooks/test_notebooks.py
Labels: size:M

#1944 Increase Cortex complete timeout to 60s for tests.
  src/providers/cortex/trulens/providers/cortex/provider.py
  tests/e2e/data/staged_packages.ipynb
  tests/e2e/test_otel_costs.py
  tests/e2e/test_snowflake_feedback_evaluation.py
Labels: size:S

#1946 Convert `ai.observability.eval_root.result` to `ai.observability.eval_root.score` as that's what Snowflake metric computation does.
  src/feedback/trulens/feedback/computer.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/unit/static/golden/test_otel_feedback_computation__test_feedback_computation.csv
  tests/unit/test_otel_feedback_computation.py
Labels: size:XS

#1945 Pin certifi version to unblock e2e pipeline
  Makefile
Labels: dependencies, size:XS

#1939 [SNOW-2005227] v0 OTEL implementation of get_records_and_feedback
  .gitignore
  src/core/trulens/core/database/connector/base.py
  src/core/trulens/core/database/sqlalchemy.py
  src/dashboard/trulens/dashboard/run.py
  src/dashboard/trulens/dashboard/utils/dashboard_utils.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/unit/data/test_otel_spans/eval_root_span.json
  tests/unit/data/test_otel_spans/eval_span_1.json
  tests/unit/data/test_otel_spans/eval_span_2.json
  tests/unit/data/test_otel_spans/generation_span.json
  tests/unit/data/test_otel_spans/record_root_span.json
  tests/unit/data/test_otel_spans/retrieval_span.json
  tests/unit/test_otel_get_records_and_feedback.py
Labels: size:XXL
