Repository truera/trulens, pull requests merged in 2025-07, with the labels that each got.

#2103 trace level selection docs
  docs/component_guides/evaluation/feedback_selectors/selecting_components.md
  mkdocs.yml
Labels: documentation, size:L

#2111 Allow `ignore_none_values` to be set for `Selector` and set to `False` by default.
  src/core/trulens/core/feedback/selector.py
Labels: size:XS

#2108 Trajectory Evals (experimental)
  examples/expositional/frameworks/langchain/langgraph_quickstart.ipynb
  src/core/trulens/core/utils/evaluator.py
  src/feedback/trulens/feedback/computer.py
  src/feedback/trulens/feedback/llm_provider.py
  src/feedback/trulens/feedback/prompts.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
Labels: size:L

#2117 Feat: Update and standardize docstrings for llm_provider.py
  src/feedback/trulens/feedback/llm_provider.py
Labels: documentation, size:L

#2122 Docs: Update docs website year, fix homepage link
  docs/assets/favicon/site.webmanifest
  docs/overrides/home.html
Labels: documentation, size:S

#2121 Feat: Modernize trajectory evals to v2 feedback system with few-shot example support
  examples/expositional/frameworks/langchain/langgraph_quickstart.ipynb
  src/core/trulens/core/feedback/feedback.py
  src/feedback/trulens/feedback/llm_provider.py
  src/feedback/trulens/feedback/prompts.py
  src/feedback/trulens/feedback/v2/feedback.py
  tests/unit/static/golden/api.trulens.3.11.yaml
Labels: size:L

#2119 Create `trulens.apps.langgraph` package.
  poetry.lock
  pyproject.toml
  src/apps/langgraph/README.md
  src/apps/langgraph/meta.yaml
  src/apps/langgraph/pyproject.toml
  src/apps/langgraph/trulens/apps/langgraph/__init__.py
Labels: size:L

#2125 Update `snowflake-connector-python` version dependency as the old one doesn't work for some auth stuff.
  poetry.lock
  src/providers/cortex/pyproject.toml
Labels: dependencies, size:XS

#2128 Accept Anaconda's TOS.
  .azure_pipelines/templates/build-conda-packages.yaml
Labels: size:XS

#2124 Fix: Handle division by zero errors in feedback, groundtruth, and hotspots, improve test coverage for groundtruth
  src/feedback/trulens/feedback/generated.py
  src/feedback/trulens/feedback/groundtruth.py
  src/feedback/trulens/feedback/v2/feedback.py
  src/hotspots/trulens/hotspots/hotspots.py
  tests/unit/test_groundtruth_aggregator.py
Labels: size:XXL

#2133 Fix conda build issues by restricting `smmap` version.
  src/dashboard/meta.yaml
Labels: dependencies, size:XS

#2114 Implement TruGraph for Langgraph instrumentation
  Makefile
  examples/expositional/frameworks/langchain/otel_tru_graph_example.ipynb
  src/apps/langgraph/README.md
  src/apps/langgraph/meta.yaml
  src/apps/langgraph/pyproject.toml
  src/apps/langgraph/trulens/apps/langgraph/__init__.py
  src/apps/langgraph/trulens/apps/langgraph/tru_graph.py
  src/core/trulens/core/_utils/optional.py
  src/core/trulens/core/instruments.py
  src/core/trulens/core/run.py
  src/core/trulens/core/session.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/unit/static/golden/test_otel_tru_graph_test_function_api_smoke.csv
  tests/unit/static/golden/test_otel_tru_graph_test_smoke.csv
  tests/unit/test_otel_tru_graph.py
Labels: documentation, dependencies, size:XXL

#2131 Handle when the spans don't have app ids in the UI.
  src/core/trulens/core/database/sqlalchemy.py
Labels: size:S

#2138 Allow TruLens to use reasoning models in OpenAI provider
  src/core/trulens/core/schema/base.py
  src/feedback/trulens/feedback/llm_provider.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  src/providers/openai/trulens/providers/openai/endpoint.py
  src/providers/openai/trulens/providers/openai/provider.py
  tests/unit/static/golden/api.trulens.3.11.yaml
Labels: size:L

#2135 TruLens v2.1
  examples/expositional/frameworks/langchain/langgraph-multi-agent-snowflake-tools.ipynb
  examples/expositional/frameworks/langchain/langgraph_quickstart.ipynb
  poetry.lock
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/langgraph/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/pyproject.toml
  src/feedback/pyproject.toml
  src/hotspots/pyproject.toml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: documentation, dependencies, size:L

#2141 Updated meta.yaml for release 2.1.0
  src/apps/langchain/meta.yaml
  src/apps/langgraph/meta.yaml
  src/connectors/snowflake/meta.yaml
  src/core/meta.yaml
  src/dashboard/meta.yaml
  src/feedback/meta.yaml
  src/otel/semconv/meta.yaml
  src/providers/cortex/meta.yaml
Labels: dependencies, size:M

#2143 In-line evals notebook
  examples/expositional/frameworks/langchain/langgraph-multi-agent-snowflake-tools.ipynb
Labels: size:XXL

#2146 Address feedback on the data agents notebook
  examples/expositional/frameworks/langchain/langgraph-multi-agent-snowflake-tools.ipynb
Labels: size:M

#2145 Make empty events warning quieter
  src/feedback/trulens/feedback/computer.py
Labels: size:XS

#2147 improve groundedness reliability
  src/dashboard/trulens/dashboard/display.py
  src/dashboard/trulens/dashboard/utils/records_utils.py
  src/feedback/trulens/feedback/llm_provider.py
  src/feedback/trulens/feedback/prompts.py
  src/feedback/trulens/feedback/v2/feedback.py
Labels: size:L

#2149 Sort siblings in the record viewer by their start time.
  src/dashboard/react_components/record_viewer_otel/src/functions/createTreeFromCalls.test.ts
  src/dashboard/react_components/record_viewer_otel/src/functions/createTreeFromCalls.ts
  src/dashboard/trulens/dashboard/components/record_viewer_otel/dist/assets/index-C42FDsR8.js
  src/dashboard/trulens/dashboard/components/record_viewer_otel/dist/index.html
Labels: javascript, size:L

#2150 Lower Langgraph version required in `trulens-apps-langgraph`
  .pre-commit-config.yaml
  src/apps/langgraph/pyproject.toml
Labels: dependencies, size:XS

#2151 Make trulens-core no longer depend on trulens-feedback
  src/core/meta.yaml
  src/core/pyproject.toml
  src/core/trulens/core/app.py
Labels: dependencies, size:S

#2154 Update span name to task name for Langgraph tracing
  src/apps/langgraph/pyproject.toml
  src/apps/langgraph/trulens/apps/langgraph/tru_graph.py
  src/apps/llamaindex/trulens/apps/llamaindex/tru_llama.py
  tests/unit/static/golden/test_otel_tru_graph_test_function_api_smoke.csv
Labels: size:S

#2157 Trulens 2.1.2
  poetry.lock
  pyproject.toml
  src/apps/langchain/meta.yaml
  src/apps/langchain/pyproject.toml
  src/apps/langgraph/meta.yaml
  src/apps/langgraph/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/hotspots/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M
