Repository truera/trulens, pull requests merged in 2025-02, with the labels that each got.

#1777 Set kwargs, return, and exception on all spans in the `ai.observability.call` span attribute scope.
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
Labels: size:M

#1778 Patch groundedness configs
  src/core/trulens/core/feedback/feedback.py
Labels: size:XS

#1779 fix broken link on homepage
  docs/overrides/home.html
Labels: documentation, size:XS

#1780 Disable python <3.9
  .azure_pipelines/ci-eval-pr.yaml
  .azure_pipelines/templates/env-setup.yaml
  poetry.lock
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1769 Add in some minor test improvements.
  tests/e2e/test_snowflake_event_table_exporter.py
  tests/unit/static/golden/test_otel_tru_basic__test_smoke.csv
  tests/unit/test_otel_tru_basic.py
Labels: size:M

#1771 make main_method required for app base class for OTEL
  src/core/trulens/apps/app.py
  src/core/trulens/core/app.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
  tests/unit/test_otel_guardrail.py
  tests/unit/test_otel_main_method.py
  tests/unit/test_otel_multithreaded.py
  tests/unit/test_otel_tru_basic.py
  tests/unit/test_otel_tru_chain.py
  tests/unit/test_otel_tru_custom.py
  tests/unit/test_otel_tru_llama.py
Labels: size:L

#1783 Quieter Instrumentation
  src/core/trulens/apps/app.py
  src/core/trulens/core/app.py
  src/core/trulens/core/feedback/endpoint.py
  src/core/trulens/core/instruments.py
Labels: size:S

#1782 Create OTEL notebook tests.
  examples/experimental/otel_exporter.ipynb
  tests/e2e/test_otel_notebooks.py
  tests/e2e/test_snowflake_event_table_exporter.py
Labels: size:L

#1785 Run an E2E notebook on Snowflake notebooks (via staging the trulens packages).
  src/connectors/snowflake/trulens/connectors/snowflake/otel_exporter.py
  src/core/trulens/experimental/otel_tracing/core/exporter/utils.py
  tests/e2e/data/staged_packages_with_otel.ipynb
  tests/e2e/test_snowflake_notebooks.py
Labels: size:L

#1781 Cost track `litellm.completion`.
  src/core/trulens/core/session.py
  src/core/trulens/experimental/otel_tracing/core/session.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  src/providers/cortex/trulens/providers/cortex/endpoint.py
  src/providers/litellm/trulens/providers/litellm/endpoint.py
  src/providers/openai/trulens/providers/openai/endpoint.py
  tests/e2e/test_otel_costs.py
  tests/e2e/test_snowflake_event_table_exporter.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/test_otel_guardrail.py
  tests/unit/test_otel_multithreaded.py
  tests/util/otel_app_test_case.py
Labels: size:L

#1786 Use new SPROC and UDTF, and verify more for OTEL Snowflake exporter.
  examples/experimental/otel_exporter.ipynb
  src/connectors/snowflake/trulens/connectors/snowflake/otel_exporter.py
  tests/e2e/test_otel_costs.py
  tests/e2e/test_snowflake_event_table_exporter.py
Labels: size:L

#1788 Use `pytest` for grouping required/optional tests.
  .azure_pipelines/ci-eval-pr.yaml
  .azure_pipelines/templates/run-optional-tests.yaml
  .azure_pipelines/templates/run-tests.yaml
  DEVELOPMENT.md
  Makefile
  conftest.py
  poetry.lock
  pyproject.toml
  src/connectors/snowflake/trulens/connectors/snowflake/otel_exporter.py
  tests/e2e/test_context_variables.py
  tests/e2e/test_endpoints.py
  tests/e2e/test_otel_costs.py
  tests/e2e/test_providers.py
  tests/e2e/test_snowflake_connection.py
  tests/e2e/test_snowflake_event_table_exporter.py
  tests/e2e/test_snowflake_feedback_evaluation.py
  tests/e2e/test_tru_chain.py
  tests/e2e/test_tru_llama.py
  tests/e2e/test_tru_session.py
  tests/legacy/test_trulens_eval_notebooks.py
  tests/test.py
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/test_api.py
  tests/unit/static/test_deprecation.py
  tests/unit/static/test_static.py
  tests/unit/test_otel_snowflake_event_table_exporter.py
  tests/unit/test_otel_tru_chain.py
  tests/unit/test_otel_tru_llama.py
Labels: size:L

#1790 Remove `pytest.ini` as it's interfering with the `pyproject.toml`.
  pytest.ini
Labels: size:XS

#1791 TruLens 1.3.4
  poetry.lock
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1792 Fix `snowflake-sqlalchemy` autocommit issue.
  src/core/trulens/core/database/sqlalchemy.py
Labels: size:S

#1793 TruLens 1.3.5
  Makefile
  poetry.lock
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1794 Create very general function to compute feedbacks.
  src/core/trulens/core/app.py
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/experimental/otel_tracing/core/exporter/utils.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  src/feedback/trulens/feedback/computer.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/e2e/data/staged_packages_with_otel.ipynb
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
  tests/unit/test_otel_feedback_computation.py
  tests/unit/test_otel_tru_chain.py
Labels: size:XXL

#1795 even quieter logging
  src/core/trulens/core/instruments.py
Labels: size:XS

#1789 Create distributed OTEL test.
  tests/unit/test_otel_distributed.py
Labels: size:L

#1757 Trulens hotspots
  .gitignore
  examples/expositional/use_cases/hotspots_output.png
  examples/expositional/use_cases/summarization_hotspots.ipynb
  examples/quickstart/hotspots.ipynb
  poetry.lock
  pyproject.toml
  src/hotspots/README.md
  src/hotspots/poetry.lock
  src/hotspots/pyproject.toml
  src/hotspots/sample_screenshot.png
  src/hotspots/trulens/hotspots/__init__.py
  src/hotspots/trulens/hotspots/hotspots.py
  src/hotspots/trulens/hotspots/hotspots_streamlit.py
  src/hotspots/trulens/hotspots/tru_hotspots.py
  tests/files/sample.csv.gz
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/test_hotspots.py
Labels: size:XXL

#1796 Clean up tests a bit and remove `ai.observability.domain` as a span attribute.
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/docs_notebooks/test_notebooks.py
  tests/e2e/test_context_variables.py
  tests/e2e/test_dummy.py
  tests/e2e/test_embedding_feedback.py
  tests/e2e/test_endpoints.py
  tests/e2e/test_otel_costs.py
  tests/e2e/test_otel_notebooks.py
  tests/e2e/test_providers.py
  tests/e2e/test_serial.py
  tests/e2e/test_snowflake_connection.py
  tests/e2e/test_snowflake_event_table_exporter.py
  tests/e2e/test_snowflake_feedback_evaluation.py
  tests/e2e/test_snowflake_notebooks.py
  tests/e2e/test_tru_chain.py
  tests/e2e/test_tru_llama.py
  tests/integration/test_database.py
  tests/unit/static/golden/test_otel_tru_basic__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
  tests/unit/static/test_api.py
  tests/unit/static/test_deprecation.py
  tests/unit/static/test_static.py
  tests/unit/test_app.py
  tests/unit/test_exporter.py
  tests/unit/test_feedback.py
  tests/unit/test_guardrails.py
  tests/unit/test_lens.py
  tests/unit/test_otel_distributed.py
  tests/unit/test_otel_guardrail.py
  tests/unit/test_otel_instrument.py
  tests/unit/test_otel_main_method.py
  tests/unit/test_otel_multithreaded.py
  tests/unit/test_otel_snowflake_event_table_exporter.py
  tests/unit/test_otel_span.py
  tests/unit/test_otel_tru_basic.py
  tests/unit/test_otel_tru_custom.py
  tests/unit/test_otel_tru_llama.py
  tests/unit/test_signature_utils.py
  tests/unit/test_tru_app.py
  tests/unit/test_tru_basic_app.py
  tests/unit/test_tru_custom.py
  tests/util/snowflake_test_case.py
Labels: size:L

#1797 Update semantic convention for EVAL and EVAL_ROOT and update test to use this.
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/unit/static/golden/test_otel_feedback_computation__test_feedback_computation.csv
  tests/unit/test_otel_feedback_computation.py
Labels: size:L

#1772 SDK app wrapper (EXTERNAL_AGENT ) CRUD
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  src/connectors/snowflake/trulens/connectors/snowflake/dao/enums.py
  src/connectors/snowflake/trulens/connectors/snowflake/dao/external_agent.py
  src/connectors/snowflake/trulens/connectors/snowflake/dao/run.py
  src/connectors/snowflake/trulens/connectors/snowflake/dao/sql_utils.py
  src/core/pyproject.toml
  src/core/trulens/core/app.py
  src/core/trulens/core/run.py
  tests/e2e/test_snowflake_external_agent.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
  tests/unit/test_external_agent_dao.py
Labels: size:XL

#1798 Create Snowflake E2E version of the feedback computation test.
  examples/experimental/otel_exporter.ipynb
  src/connectors/snowflake/trulens/connectors/snowflake/otel_exporter.py
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  src/feedback/trulens/feedback/computer.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/e2e/data/staged_packages_with_otel.ipynb
  tests/e2e/test_snowflake_event_table_exporter.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/test_otel_feedback_computation__test_feedback_computation.csv
  tests/unit/static/golden/test_otel_instrument__test_instrument_decorator.csv
  tests/unit/static/golden/test_otel_tru_basic__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
  tests/unit/test_otel_distributed.py
  tests/unit/test_otel_feedback_computation.py
  tests/util/mock_otel_feedback_computation.py
Labels: size:L

#1799 Allow for `ground_truth_output` to be specified to recorder and also clean up semantic conventions
  src/core/trulens/core/app.py
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/experimental/otel_tracing/core/exporter/utils.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/e2e/data/staged_packages_with_otel.ipynb
  tests/e2e/test_snowflake_event_table_exporter.py
  tests/unit/static/golden/test_otel_feedback_computation__test_feedback_computation.csv
  tests/unit/static/golden/test_otel_tru_basic__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
  tests/unit/test_otel_feedback_computation.py
Labels: size:M

#1767 add llamaindex/langchain conda build recipes
  src/apps/langchain/meta.yaml
Labels: size:M

#1800 Create OTEL span processor that can add trulens span attributes into spans not originated by trulens.
  src/core/trulens/experimental/otel_tracing/core/session.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  tests/unit/test_otel_span_processor.py
  tests/unit/test_otel_tru_chain.py
Labels: size:L

#1802 Make main_method required only for TruChain and TruLlama
  src/apps/langchain/trulens/apps/langchain/tru_chain.py
  src/apps/llamaindex/trulens/apps/llamaindex/tru_llama.py
  src/core/trulens/core/app.py
  tests/e2e/test_snowflake_external_agent.py
  tests/unit/test_otel_main_method.py
  tests/unit/test_otel_tru_chain.py
  tests/unit/test_otel_tru_llama.py
Labels: size:M

#1805 Set up new context managers to record.
  examples/experimental/otel_exporter.ipynb
  src/apps/langchain/trulens/apps/langchain/tru_chain.py
  src/apps/llamaindex/trulens/apps/llamaindex/tru_llama.py
  src/connectors/snowflake/trulens/connectors/snowflake/utils/server_side_evaluation_artifacts.py
  src/core/trulens/apps/basic.py
  src/core/trulens/core/app.py
  src/core/trulens/core/otel/function_call_context_manager.py
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  src/otel/semconv/trulens/otel/semconv/constants.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/e2e/data/staged_packages_with_otel.ipynb
  tests/e2e/test_otel_costs.py
  tests/e2e/test_snowflake_event_table_exporter.py
  tests/e2e/test_snowflake_notebooks.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/test_otel_feedback_computation__test_feedback_computation.csv
  tests/unit/static/golden/test_otel_tru_basic__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
  tests/unit/test_otel_distributed.py
  tests/unit/test_otel_feedback_computation.py
  tests/unit/test_otel_guardrail.py
  tests/unit/test_otel_multithreaded.py
  tests/unit/test_otel_recording_contexts.py
  tests/unit/test_otel_span_processor.py
  tests/unit/test_otel_tru_basic.py
  tests/unit/test_otel_tru_chain.py
  tests/unit/test_otel_tru_custom.py
  tests/unit/test_otel_tru_llama.py
Labels: size:XL

#1807 Bump to 1.4.0.
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/pyproject.toml
  src/core/pyproject.toml
  src/dashboard/pyproject.toml
  src/feedback/pyproject.toml
  src/hotspots/pyproject.toml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1808 Update `meta.yaml` files for 1.4.0 release.
  src/connectors/snowflake/meta.yaml
  src/core/meta.yaml
  src/dashboard/meta.yaml
  src/feedback/meta.yaml
  src/otel/semconv/meta.yaml
  src/providers/cortex/meta.yaml
Labels: size:S

#1809 Bugfix: Avoid ingestion of incorrectly generated spans.
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  src/connectors/snowflake/trulens/connectors/snowflake/otel_exporter.py
  src/core/trulens/experimental/otel_tracing/core/exporter/utils.py
Labels: size:M

#1811 Clean up semantic conventions.
  src/otel/semconv/trulens/otel/semconv/trace.py
Labels: size:L

#1812 Don't output a lot of span attributes if they're `None`.
  src/core/trulens/core/app.py
  src/core/trulens/experimental/otel_tracing/core/exporter/utils.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/test_otel_multithreaded.py
  tests/unit/test_otel_span_processor.py
  tests/unit/test_otel_tru_basic.py
  tests/unit/test_otel_tru_chain.py
  tests/unit/test_otel_tru_custom.py
  tests/unit/test_otel_tru_llama.py
Labels: size:M

#1814 Set default host for snowflake connector if not provided
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
Labels: size:XS

#1813 Test conda build in PR pipeline.
  .azure_pipelines/ci-eval-pr.yaml
  .azure_pipelines/ci-eval.yaml
  .azure_pipelines/templates/build-conda-packages.yaml
  src/connectors/snowflake/meta.yaml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/feedback/meta.yaml
  src/otel/semconv/meta.yaml
  src/providers/cortex/meta.yaml
  zip_wheels.sh
Labels: dependencies, size:M

#1818 Ensure there's only one record root span and also discern the main method if none given for `TruApp`/`TruCustomApp`.
  src/core/trulens/apps/app.py
  src/core/trulens/core/otel/instrument.py
  tests/unit/test_otel_record_root.py
Labels: size:L

#1819 OTEL -> Otel to follow general naming conventions and keep things consistent.
  src/core/trulens/core/app.py
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/experimental/otel_tracing/core/exporter/connector.py
  src/core/trulens/experimental/otel_tracing/core/session.py
  src/feedback/trulens/feedback/computer.py
  tests/unit/test_otel_span.py
Labels: size:M

#1817 TruLens 1.4.1
  poetry.lock
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/hotspots/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1784 [SNOW-1901834] SDK: Run APIs: CREATE, GET, LIST, and DELETE and run.start()
  examples/experimental/pupr_e2e_cuj.ipynb
  src/connectors/snowflake/trulens/connectors/snowflake/connector.py
  src/connectors/snowflake/trulens/connectors/snowflake/dao/enums.py
  src/connectors/snowflake/trulens/connectors/snowflake/dao/external_agent.py
  src/connectors/snowflake/trulens/connectors/snowflake/dao/run.py
  src/connectors/snowflake/trulens/connectors/snowflake/dao/sql_utils.py
  src/core/trulens/core/app.py
  src/core/trulens/core/run.py
  tests/e2e/test_snowflake_agents_and_runs.py
  tests/e2e/test_snowflake_external_agent.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/api.trulens_eval.3.11.yaml
  tests/unit/test_snowflake_external_agent_dao.py
  tests/unit/test_snowflake_run_dao.py
Labels: size:XXL

#1820 TruLens 1.4.2
  poetry.lock
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/hotspots/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1822 Add test dataset for bugbash
  examples/experimental/pupr_e2e_cuj.ipynb
  examples/experimental/test_data/ms_marco_hard_neg_balanced.csv
Labels: size:M

#1821 Filipg/fix hotspots for release
  src/hotspots/README.md
  src/hotspots/trulens/hotspots/__init__.py
  src/hotspots/trulens/hotspots/__main__.py
  src/hotspots/trulens/hotspots/hotspots.py
  src/hotspots/trulens/hotspots/hotspots_streamlit.py
  tests/unit/static/golden/api.trulens.3.11.yaml
Labels: size:M

#1810 Fix issue where for `llama-index` apps, we don't handle the app specific record root correctly.
  src/core/trulens/apps/basic.py
  src/core/trulens/core/app.py
  src/core/trulens/core/otel/instrument.py
  tests/e2e/test_otel_costs.py
  tests/e2e/test_snowflake_event_table_exporter.py
  tests/unit/test_otel_tru_llama.py
Labels: size:M

#1826 Redefine span attribute dictionary so that the values of the dictionary map to kwargs of the function decorated or the return.
  src/core/trulens/core/otel/instrument.py
  tests/unit/test_otel_span.py
  tests/unit/test_otel_tru_chain.py
  tests/unit/test_otel_tru_custom.py
Labels: size:S

#1827 Replace `attributes` with `full_scoped_attributes`.
  examples/experimental/otel_exporter.ipynb
  examples/experimental/pupr_e2e_cuj.ipynb
  src/apps/llamaindex/trulens/apps/llamaindex/tru_llama.py
  src/core/trulens/core/app.py
  src/core/trulens/core/instruments.py
  src/core/trulens/core/otel/instrument.py
  src/core/trulens/experimental/otel_tracing/core/session.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/test_otel_distributed.py
  tests/unit/test_otel_guardrail.py
  tests/unit/test_otel_instrument.py
  tests/unit/test_otel_multithreaded.py
  tests/unit/test_otel_tru_chain.py
  tests/unit/test_otel_tru_custom.py
  tests/util/mock_otel_feedback_computation.py
Labels: size:L

#1828 Rename `main_input`/`main_output`/`main_error` to `input`/`output`/`error`.
  src/core/trulens/core/app.py
  src/core/trulens/experimental/otel_tracing/core/span.py
  src/otel/semconv/trulens/otel/semconv/trace.py
  tests/unit/static/golden/test_otel_feedback_computation__test_feedback_computation.csv
  tests/unit/static/golden/test_otel_instrument__test_instrument_decorator.csv
  tests/unit/static/golden/test_otel_tru_basic__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_chain__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_custom__test_smoke.csv
  tests/unit/static/golden/test_otel_tru_llama__test_smoke.csv
  tests/unit/test_otel_multithreaded.py
Labels: size:S

#1832 SDK - run.describe() to return Run object directly #1831
  src/core/trulens/core/run.py
Labels: size:M

#1833 [non-OTEL] Don't track feedback functions.
  src/core/trulens/core/instruments.py
  src/core/trulens/core/schema/app.py
  tests/unit/test_feedback.py
Labels: size:M

#1838 [non-OTEL] Use context variables instead of thread_local since the latter doesn't actually inherit values from the parent threads.
  src/core/trulens/core/instruments.py
  src/core/trulens/core/schema/app.py
  tests/unit/static/golden/api.trulens.3.11.yaml
  tests/unit/test_feedback.py
Labels: size:M

#1835 change link from slack to snowflake discourse
  docs/overrides/home.html
Labels: documentation, size:S

#1841 update the README with community link
  README.md
Labels: documentation, size:XS

#1837 Clean up tests a bit and add a test to check if span attributes fail, then everything fails.
  tests/unit/test_otel_instrument.py
  tests/unit/test_otel_multithreaded.py
  tests/unit/test_otel_tru_custom.py
Labels: size:M

#1839 remove redundant header in streamlit pills
  src/dashboard/trulens/dashboard/streamlit.py
Labels: size:XS

#1842 Handle the possible creation of `TruSession` when `connector` argument is given to the tru app.
  src/apps/langchain/trulens/apps/langchain/tru_chain.py
  src/apps/llamaindex/trulens/apps/llamaindex/tru_llama.py
  src/core/trulens/apps/app.py
  src/core/trulens/core/app.py
  tests/unit/test_otel_tru_custom.py
Labels: size:M

#1843 SDK run.start() should take ground_truth_output from dataset_spec
  examples/experimental/pupr_e2e_cuj.ipynb
  src/core/trulens/core/run.py
Labels: size:S

#1829 LiteLLM fixes
  src/feedback/trulens/feedback/llm_provider.py
  src/providers/litellm/trulens/providers/litellm/endpoint.py
  src/providers/litellm/trulens/providers/litellm/provider.py
Labels: size:M

#1846 TruLens 1.4.3
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/pyproject.toml
  src/core/pyproject.toml
  src/dashboard/pyproject.toml
  src/feedback/pyproject.toml
  src/hotspots/pyproject.toml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: documentation, size:M

#1845 Add hotpotqa data to pupr notebook
  examples/experimental/pupr_e2e_cuj.ipynb
  src/core/trulens/core/run.py
Labels: size:L

#1844 Have all of the `TestOtelTruBasic`/`TestOtelTruChain`/`TestOtelTruCustom`/`TestOtelTruLlama` be subclasses of a superclass that has shared tests for all of them.
  src/core/trulens/apps/basic.py
  tests/e2e/test_otel_costs.py
  tests/unit/test_otel_distributed.py
  tests/unit/test_otel_feedback_computation.py
  tests/unit/test_otel_guardrail.py
  tests/unit/test_otel_multithreaded.py
  tests/unit/test_otel_record_root.py
  tests/unit/test_otel_recording_contexts.py
  tests/unit/test_otel_span_processor.py
  tests/unit/test_otel_tru_basic.py
  tests/unit/test_otel_tru_chain.py
  tests/unit/test_otel_tru_custom.py
  tests/unit/test_otel_tru_llama.py
  tests/util/otel_test_case.py
  tests/util/otel_tru_app_test_case.py
Labels: size:L

#1848 Handle Japanese (and other non-ascii languages) better.
  src/core/trulens/core/utils/json.py
  tests/e2e/test_snowflake_feedback_evaluation.py
  tests/unit/test_otel_tru_basic.py
Labels: size:M

#1840 [SNOW-1943864] SDK Run status tracking for invocations, computations, and metrics
  examples/experimental/pupr_e2e_cuj.ipynb
  src/connectors/snowflake/trulens/connectors/snowflake/dao/run.py
  src/core/trulens/core/run.py
  tests/unit/static/golden/api.trulens.3.11.yaml
Labels: size:XL

#1851 SDK: Map Span attributes to dataset_spec for Run + misc fixes
  src/core/trulens/core/run.py
  tests/unit/static/golden/api.trulens.3.11.yaml
Labels: size:M

#1852 TruLens 1.4.4
  pyproject.toml
  src/apps/langchain/pyproject.toml
  src/apps/llamaindex/pyproject.toml
  src/apps/nemo/pyproject.toml
  src/benchmark/pyproject.toml
  src/connectors/snowflake/meta.yaml
  src/connectors/snowflake/pyproject.toml
  src/core/meta.yaml
  src/core/pyproject.toml
  src/dashboard/meta.yaml
  src/dashboard/pyproject.toml
  src/feedback/meta.yaml
  src/feedback/pyproject.toml
  src/hotspots/pyproject.toml
  src/otel/semconv/meta.yaml
  src/otel/semconv/pyproject.toml
  src/providers/bedrock/pyproject.toml
  src/providers/cortex/meta.yaml
  src/providers/cortex/pyproject.toml
  src/providers/huggingface/pyproject.toml
  src/providers/langchain/pyproject.toml
  src/providers/litellm/pyproject.toml
  src/providers/openai/pyproject.toml
  src/trulens_eval/pyproject.toml
Labels: dependencies, size:M

#1853 Fix double quotes issue in run operation system function / method
  src/connectors/snowflake/trulens/connectors/snowflake/dao/run.py
  src/connectors/snowflake/trulens/connectors/snowflake/dao/sql_utils.py
  tests/e2e/test_snowflake_agents_and_runs.py
  tests/unit/test_snowflake_external_agent_dao.py
  tests/unit/test_snowflake_run_dao.py
Labels: size:M
